/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from "node:process";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));

import * as runtime from "@prisma/client/runtime/client";
import * as $Enums from "./enums";
import * as $Class from "./internal/class";
import * as Prisma from "./internal/prismaNamespace";

export * as $Enums from "./enums";
export * from "./enums";
/**
 * ## Prisma Client
 *
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 *
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass();
export type PrismaClient<
  LogOpts extends Prisma.LogLevel = never,
  OmitOpts extends Prisma.PrismaClientOptions["omit"] =
    Prisma.PrismaClientOptions["omit"],
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>;
export { Prisma };

/**
 * Model User
 *
 */
export type User = Prisma.UserModel;
/**
 * Model Session
 *
 */
export type Session = Prisma.SessionModel;
/**
 * Model SystemAccess
 *
 */
export type SystemAccess = Prisma.SystemAccessModel;
/**
 * Model WorkspaceAccount
 *
 */
export type WorkspaceAccount = Prisma.WorkspaceAccountModel;
/**
 * Model Release
 *
 */
export type Release = Prisma.ReleaseModel;
/**
 * Model Track
 *
 */
export type Track = Prisma.TrackModel;
/**
 * Model Video
 *
 */
export type Video = Prisma.VideoModel;
/**
 * Model Ringtone
 *
 */
export type Ringtone = Prisma.RingtoneModel;
/**
 * Model Artist
 *
 */
export type Artist = Prisma.ArtistModel;
/**
 * Model Performer
 *
 */
export type Performer = Prisma.PerformerModel;
/**
 * Model ProducerAndEngineer
 *
 */
export type ProducerAndEngineer = Prisma.ProducerAndEngineerModel;
/**
 * Model ArtistPerformerProducerAndEngineer
 *
 */
export type ArtistPerformerProducerAndEngineer =
  Prisma.ArtistPerformerProducerAndEngineerModel;
/**
 * Model Writer
 *
 */
export type Writer = Prisma.WriterModel;
/**
 * Model Publisher
 *
 */
export type Publisher = Prisma.PublisherModel;
/**
 * Model Label
 *
 */
export type Label = Prisma.LabelModel;
/**
 * Model Transaction
 *
 */
export type Transaction = Prisma.TransactionModel;
/**
 * Model Withdrawal
 *
 */
export type Withdrawal = Prisma.WithdrawalModel;
/**
 * Model SharedWorkspaceAccountAccess
 *
 */
export type SharedWorkspaceAccountAccess =
  Prisma.SharedWorkspaceAccountAccessModel;
/**
 * Model RightsManagement
 *
 */
export type RightsManagement = Prisma.RightsManagementModel;
/**
 * Model AuditLog
 *
 */
export type AuditLog = Prisma.AuditLogModel;
