/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client";
import * as $Enums from "./enums";
import type * as Prisma from "./internal/prismaNamespace";

export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  mode?: Prisma.QueryMode;
  not?: Prisma.NestedStringFilter<$PrismaModel> | string;
};

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  mode?: Prisma.QueryMode;
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null;
};

export type JsonNullableFilter<$PrismaModel = never> =
  | Prisma.PatchUndefined<
      Prisma.Either<
        Required<JsonNullableFilterBase<$PrismaModel>>,
        Exclude<keyof Required<JsonNullableFilterBase<$PrismaModel>>, "path">
      >,
      Required<JsonNullableFilterBase<$PrismaModel>>
    >
  | Prisma.OptionalFlat<
      Omit<Required<JsonNullableFilterBase<$PrismaModel>>, "path">
    >;

export type JsonNullableFilterBase<$PrismaModel = never> = {
  equals?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
  path?: string[];
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>;
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  array_starts_with?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | null;
  array_ends_with?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | null;
  array_contains?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | null;
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>;
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>;
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>;
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>;
  not?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
};

export type EnumROLEFilter<$PrismaModel = never> = {
  equals?: $Enums.ROLE | Prisma.EnumROLEFieldRefInput<$PrismaModel>;
  in?: $Enums.ROLE[] | Prisma.ListEnumROLEFieldRefInput<$PrismaModel>;
  notIn?: $Enums.ROLE[] | Prisma.ListEnumROLEFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumROLEFilter<$PrismaModel> | $Enums.ROLE;
};

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string;
};

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null;
  in?:
    | Date[]
    | string[]
    | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
    | null;
  notIn?:
    | Date[]
    | string[]
    | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
    | null;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedDateTimeNullableFilter<$PrismaModel>
    | Date
    | string
    | null;
};

export type SortOrderInput = {
  sort: Prisma.SortOrder;
  nulls?: Prisma.NullsOrder;
};

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  mode?: Prisma.QueryMode;
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedStringFilter<$PrismaModel>;
  _max?: Prisma.NestedStringFilter<$PrismaModel>;
};

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  mode?: Prisma.QueryMode;
  not?:
    | Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel>
    | string
    | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>;
};

export type JsonNullableWithAggregatesFilter<$PrismaModel = never> =
  | Prisma.PatchUndefined<
      Prisma.Either<
        Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>,
        Exclude<
          keyof Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>,
          "path"
        >
      >,
      Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>
    >
  | Prisma.OptionalFlat<
      Omit<Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>, "path">
    >;

export type JsonNullableWithAggregatesFilterBase<$PrismaModel = never> = {
  equals?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
  path?: string[];
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>;
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  array_starts_with?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | null;
  array_ends_with?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | null;
  array_contains?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | null;
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>;
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>;
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>;
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>;
  not?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedJsonNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedJsonNullableFilter<$PrismaModel>;
};

export type EnumROLEWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ROLE | Prisma.EnumROLEFieldRefInput<$PrismaModel>;
  in?: $Enums.ROLE[] | Prisma.ListEnumROLEFieldRefInput<$PrismaModel>;
  notIn?: $Enums.ROLE[] | Prisma.ListEnumROLEFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumROLEWithAggregatesFilter<$PrismaModel> | $Enums.ROLE;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumROLEFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumROLEFilter<$PrismaModel>;
};

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>;
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>;
};

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null;
  in?:
    | Date[]
    | string[]
    | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
    | null;
  notIn?:
    | Date[]
    | string[]
    | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
    | null;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel>
    | Date
    | string
    | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>;
};

export type EnumSESSION_DEVICE_TYPEFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.SESSION_DEVICE_TYPE
    | Prisma.EnumSESSION_DEVICE_TYPEFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.SESSION_DEVICE_TYPE[]
    | Prisma.ListEnumSESSION_DEVICE_TYPEFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.SESSION_DEVICE_TYPE[]
    | Prisma.ListEnumSESSION_DEVICE_TYPEFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumSESSION_DEVICE_TYPEFilter<$PrismaModel>
    | $Enums.SESSION_DEVICE_TYPE;
};

export type EnumSESSION_DEVICE_TYPEWithAggregatesFilter<$PrismaModel = never> =
  {
    equals?:
      | $Enums.SESSION_DEVICE_TYPE
      | Prisma.EnumSESSION_DEVICE_TYPEFieldRefInput<$PrismaModel>;
    in?:
      | $Enums.SESSION_DEVICE_TYPE[]
      | Prisma.ListEnumSESSION_DEVICE_TYPEFieldRefInput<$PrismaModel>;
    notIn?:
      | $Enums.SESSION_DEVICE_TYPE[]
      | Prisma.ListEnumSESSION_DEVICE_TYPEFieldRefInput<$PrismaModel>;
    not?:
      | Prisma.NestedEnumSESSION_DEVICE_TYPEWithAggregatesFilter<$PrismaModel>
      | $Enums.SESSION_DEVICE_TYPE;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedEnumSESSION_DEVICE_TYPEFilter<$PrismaModel>;
    _max?: Prisma.NestedEnumSESSION_DEVICE_TYPEFilter<$PrismaModel>;
  };

export type EnumWORKSPACE_ACCOUNT_TYPEFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.WORKSPACE_ACCOUNT_TYPE
    | Prisma.EnumWORKSPACE_ACCOUNT_TYPEFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.WORKSPACE_ACCOUNT_TYPE[]
    | Prisma.ListEnumWORKSPACE_ACCOUNT_TYPEFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.WORKSPACE_ACCOUNT_TYPE[]
    | Prisma.ListEnumWORKSPACE_ACCOUNT_TYPEFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumWORKSPACE_ACCOUNT_TYPEFilter<$PrismaModel>
    | $Enums.WORKSPACE_ACCOUNT_TYPE;
};

export type EnumWORKSPACE_ACCOUNT_TYPEWithAggregatesFilter<
  $PrismaModel = never,
> = {
  equals?:
    | $Enums.WORKSPACE_ACCOUNT_TYPE
    | Prisma.EnumWORKSPACE_ACCOUNT_TYPEFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.WORKSPACE_ACCOUNT_TYPE[]
    | Prisma.ListEnumWORKSPACE_ACCOUNT_TYPEFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.WORKSPACE_ACCOUNT_TYPE[]
    | Prisma.ListEnumWORKSPACE_ACCOUNT_TYPEFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumWORKSPACE_ACCOUNT_TYPEWithAggregatesFilter<$PrismaModel>
    | $Enums.WORKSPACE_ACCOUNT_TYPE;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumWORKSPACE_ACCOUNT_TYPEFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumWORKSPACE_ACCOUNT_TYPEFilter<$PrismaModel>;
};

export type EnumRELEASE_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.RELEASE_STATUS
    | Prisma.EnumRELEASE_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.RELEASE_STATUS[]
    | Prisma.ListEnumRELEASE_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.RELEASE_STATUS[]
    | Prisma.ListEnumRELEASE_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumRELEASE_STATUSFilter<$PrismaModel>
    | $Enums.RELEASE_STATUS;
};

export type EnumRELEASE_STATUSWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.RELEASE_STATUS
    | Prisma.EnumRELEASE_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.RELEASE_STATUS[]
    | Prisma.ListEnumRELEASE_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.RELEASE_STATUS[]
    | Prisma.ListEnumRELEASE_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumRELEASE_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.RELEASE_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumRELEASE_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumRELEASE_STATUSFilter<$PrismaModel>;
};

export type EnumTRACK_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.TRACK_STATUS
    | Prisma.EnumTRACK_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.TRACK_STATUS[]
    | Prisma.ListEnumTRACK_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.TRACK_STATUS[]
    | Prisma.ListEnumTRACK_STATUSFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumTRACK_STATUSFilter<$PrismaModel> | $Enums.TRACK_STATUS;
};

export type EnumTRACK_STATUSWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.TRACK_STATUS
    | Prisma.EnumTRACK_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.TRACK_STATUS[]
    | Prisma.ListEnumTRACK_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.TRACK_STATUS[]
    | Prisma.ListEnumTRACK_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumTRACK_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.TRACK_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumTRACK_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumTRACK_STATUSFilter<$PrismaModel>;
};

export type EnumVIDEO_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.VIDEO_STATUS
    | Prisma.EnumVIDEO_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.VIDEO_STATUS[]
    | Prisma.ListEnumVIDEO_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.VIDEO_STATUS[]
    | Prisma.ListEnumVIDEO_STATUSFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumVIDEO_STATUSFilter<$PrismaModel> | $Enums.VIDEO_STATUS;
};

export type EnumVIDEO_STATUSWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.VIDEO_STATUS
    | Prisma.EnumVIDEO_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.VIDEO_STATUS[]
    | Prisma.ListEnumVIDEO_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.VIDEO_STATUS[]
    | Prisma.ListEnumVIDEO_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumVIDEO_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.VIDEO_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumVIDEO_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumVIDEO_STATUSFilter<$PrismaModel>;
};

export type EnumRINGTONE_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.RINGTONE_STATUS
    | Prisma.EnumRINGTONE_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.RINGTONE_STATUS[]
    | Prisma.ListEnumRINGTONE_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.RINGTONE_STATUS[]
    | Prisma.ListEnumRINGTONE_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumRINGTONE_STATUSFilter<$PrismaModel>
    | $Enums.RINGTONE_STATUS;
};

export type EnumRINGTONE_STATUSWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.RINGTONE_STATUS
    | Prisma.EnumRINGTONE_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.RINGTONE_STATUS[]
    | Prisma.ListEnumRINGTONE_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.RINGTONE_STATUS[]
    | Prisma.ListEnumRINGTONE_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumRINGTONE_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.RINGTONE_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumRINGTONE_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumRINGTONE_STATUSFilter<$PrismaModel>;
};

export type EnumARTIST_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.ARTIST_STATUS
    | Prisma.EnumARTIST_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.ARTIST_STATUS[]
    | Prisma.ListEnumARTIST_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.ARTIST_STATUS[]
    | Prisma.ListEnumARTIST_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumARTIST_STATUSFilter<$PrismaModel>
    | $Enums.ARTIST_STATUS;
};

export type EnumARTIST_STATUSWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.ARTIST_STATUS
    | Prisma.EnumARTIST_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.ARTIST_STATUS[]
    | Prisma.ListEnumARTIST_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.ARTIST_STATUS[]
    | Prisma.ListEnumARTIST_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumARTIST_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.ARTIST_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumARTIST_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumARTIST_STATUSFilter<$PrismaModel>;
};

export type EnumPERFORMER_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.PERFORMER_STATUS
    | Prisma.EnumPERFORMER_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.PERFORMER_STATUS[]
    | Prisma.ListEnumPERFORMER_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.PERFORMER_STATUS[]
    | Prisma.ListEnumPERFORMER_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumPERFORMER_STATUSFilter<$PrismaModel>
    | $Enums.PERFORMER_STATUS;
};

export type EnumPERFORMER_STATUSWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.PERFORMER_STATUS
    | Prisma.EnumPERFORMER_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.PERFORMER_STATUS[]
    | Prisma.ListEnumPERFORMER_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.PERFORMER_STATUS[]
    | Prisma.ListEnumPERFORMER_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumPERFORMER_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.PERFORMER_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumPERFORMER_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumPERFORMER_STATUSFilter<$PrismaModel>;
};

export type EnumPRODUCER_AND_ENGINEER_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.PRODUCER_AND_ENGINEER_STATUS
    | Prisma.EnumPRODUCER_AND_ENGINEER_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.PRODUCER_AND_ENGINEER_STATUS[]
    | Prisma.ListEnumPRODUCER_AND_ENGINEER_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.PRODUCER_AND_ENGINEER_STATUS[]
    | Prisma.ListEnumPRODUCER_AND_ENGINEER_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumPRODUCER_AND_ENGINEER_STATUSFilter<$PrismaModel>
    | $Enums.PRODUCER_AND_ENGINEER_STATUS;
};

export type EnumPRODUCER_AND_ENGINEER_STATUSWithAggregatesFilter<
  $PrismaModel = never,
> = {
  equals?:
    | $Enums.PRODUCER_AND_ENGINEER_STATUS
    | Prisma.EnumPRODUCER_AND_ENGINEER_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.PRODUCER_AND_ENGINEER_STATUS[]
    | Prisma.ListEnumPRODUCER_AND_ENGINEER_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.PRODUCER_AND_ENGINEER_STATUS[]
    | Prisma.ListEnumPRODUCER_AND_ENGINEER_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumPRODUCER_AND_ENGINEER_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.PRODUCER_AND_ENGINEER_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumPRODUCER_AND_ENGINEER_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumPRODUCER_AND_ENGINEER_STATUSFilter<$PrismaModel>;
};

export type EnumWRITER_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.WRITER_STATUS
    | Prisma.EnumWRITER_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.WRITER_STATUS[]
    | Prisma.ListEnumWRITER_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.WRITER_STATUS[]
    | Prisma.ListEnumWRITER_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumWRITER_STATUSFilter<$PrismaModel>
    | $Enums.WRITER_STATUS;
};

export type EnumWRITER_STATUSWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.WRITER_STATUS
    | Prisma.EnumWRITER_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.WRITER_STATUS[]
    | Prisma.ListEnumWRITER_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.WRITER_STATUS[]
    | Prisma.ListEnumWRITER_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumWRITER_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.WRITER_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumWRITER_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumWRITER_STATUSFilter<$PrismaModel>;
};

export type EnumPUBLISHER_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.PUBLISHER_STATUS
    | Prisma.EnumPUBLISHER_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.PUBLISHER_STATUS[]
    | Prisma.ListEnumPUBLISHER_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.PUBLISHER_STATUS[]
    | Prisma.ListEnumPUBLISHER_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumPUBLISHER_STATUSFilter<$PrismaModel>
    | $Enums.PUBLISHER_STATUS;
};

export type EnumPUBLISHER_STATUSWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.PUBLISHER_STATUS
    | Prisma.EnumPUBLISHER_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.PUBLISHER_STATUS[]
    | Prisma.ListEnumPUBLISHER_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.PUBLISHER_STATUS[]
    | Prisma.ListEnumPUBLISHER_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumPUBLISHER_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.PUBLISHER_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumPUBLISHER_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumPUBLISHER_STATUSFilter<$PrismaModel>;
};

export type EnumLABEL_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.LABEL_STATUS
    | Prisma.EnumLABEL_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.LABEL_STATUS[]
    | Prisma.ListEnumLABEL_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.LABEL_STATUS[]
    | Prisma.ListEnumLABEL_STATUSFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumLABEL_STATUSFilter<$PrismaModel> | $Enums.LABEL_STATUS;
};

export type EnumLABEL_STATUSWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.LABEL_STATUS
    | Prisma.EnumLABEL_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.LABEL_STATUS[]
    | Prisma.ListEnumLABEL_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.LABEL_STATUS[]
    | Prisma.ListEnumLABEL_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumLABEL_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.LABEL_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumLABEL_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumLABEL_STATUSFilter<$PrismaModel>;
};

export type EnumTRANSACTION_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.TRANSACTION_STATUS
    | Prisma.EnumTRANSACTION_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.TRANSACTION_STATUS[]
    | Prisma.ListEnumTRANSACTION_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.TRANSACTION_STATUS[]
    | Prisma.ListEnumTRANSACTION_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumTRANSACTION_STATUSFilter<$PrismaModel>
    | $Enums.TRANSACTION_STATUS;
};

export type EnumTRANSACTION_STATUSWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.TRANSACTION_STATUS
    | Prisma.EnumTRANSACTION_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.TRANSACTION_STATUS[]
    | Prisma.ListEnumTRANSACTION_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.TRANSACTION_STATUS[]
    | Prisma.ListEnumTRANSACTION_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumTRANSACTION_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.TRANSACTION_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumTRANSACTION_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumTRANSACTION_STATUSFilter<$PrismaModel>;
};

export type EnumWITHDRAWAL_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.WITHDRAWAL_STATUS
    | Prisma.EnumWITHDRAWAL_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.WITHDRAWAL_STATUS[]
    | Prisma.ListEnumWITHDRAWAL_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.WITHDRAWAL_STATUS[]
    | Prisma.ListEnumWITHDRAWAL_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumWITHDRAWAL_STATUSFilter<$PrismaModel>
    | $Enums.WITHDRAWAL_STATUS;
};

export type EnumWITHDRAWAL_STATUSWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.WITHDRAWAL_STATUS
    | Prisma.EnumWITHDRAWAL_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.WITHDRAWAL_STATUS[]
    | Prisma.ListEnumWITHDRAWAL_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.WITHDRAWAL_STATUS[]
    | Prisma.ListEnumWITHDRAWAL_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumWITHDRAWAL_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.WITHDRAWAL_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumWITHDRAWAL_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumWITHDRAWAL_STATUSFilter<$PrismaModel>;
};

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean;
};

export type EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE[]
    | Prisma.ListEnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE[]
    | Prisma.ListEnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumWORKSPACE_ACCOUNT_ACCESS_ROLEFilter<$PrismaModel>
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
};

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedBoolFilter<$PrismaModel>;
  _max?: Prisma.NestedBoolFilter<$PrismaModel>;
};

export type EnumWORKSPACE_ACCOUNT_ACCESS_ROLEWithAggregatesFilter<
  $PrismaModel = never,
> = {
  equals?:
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE[]
    | Prisma.ListEnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE[]
    | Prisma.ListEnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumWORKSPACE_ACCOUNT_ACCESS_ROLEWithAggregatesFilter<$PrismaModel>
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumWORKSPACE_ACCOUNT_ACCESS_ROLEFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumWORKSPACE_ACCOUNT_ACCESS_ROLEFilter<$PrismaModel>;
};

export type EnumRIGHTS_MANAGEMENT_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.RIGHTS_MANAGEMENT_STATUS
    | Prisma.EnumRIGHTS_MANAGEMENT_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.RIGHTS_MANAGEMENT_STATUS[]
    | Prisma.ListEnumRIGHTS_MANAGEMENT_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.RIGHTS_MANAGEMENT_STATUS[]
    | Prisma.ListEnumRIGHTS_MANAGEMENT_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumRIGHTS_MANAGEMENT_STATUSFilter<$PrismaModel>
    | $Enums.RIGHTS_MANAGEMENT_STATUS;
};

export type EnumRIGHTS_MANAGEMENT_STATUSWithAggregatesFilter<
  $PrismaModel = never,
> = {
  equals?:
    | $Enums.RIGHTS_MANAGEMENT_STATUS
    | Prisma.EnumRIGHTS_MANAGEMENT_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.RIGHTS_MANAGEMENT_STATUS[]
    | Prisma.ListEnumRIGHTS_MANAGEMENT_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.RIGHTS_MANAGEMENT_STATUS[]
    | Prisma.ListEnumRIGHTS_MANAGEMENT_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumRIGHTS_MANAGEMENT_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.RIGHTS_MANAGEMENT_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumRIGHTS_MANAGEMENT_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumRIGHTS_MANAGEMENT_STATUSFilter<$PrismaModel>;
};

export type EnumAUDIT_LOG_ACTIONFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.AUDIT_LOG_ACTION
    | Prisma.EnumAUDIT_LOG_ACTIONFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.AUDIT_LOG_ACTION[]
    | Prisma.ListEnumAUDIT_LOG_ACTIONFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.AUDIT_LOG_ACTION[]
    | Prisma.ListEnumAUDIT_LOG_ACTIONFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumAUDIT_LOG_ACTIONFilter<$PrismaModel>
    | $Enums.AUDIT_LOG_ACTION;
};

export type EnumAUDIT_LOG_ENTITYFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.AUDIT_LOG_ENTITY
    | Prisma.EnumAUDIT_LOG_ENTITYFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.AUDIT_LOG_ENTITY[]
    | Prisma.ListEnumAUDIT_LOG_ENTITYFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.AUDIT_LOG_ENTITY[]
    | Prisma.ListEnumAUDIT_LOG_ENTITYFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumAUDIT_LOG_ENTITYFilter<$PrismaModel>
    | $Enums.AUDIT_LOG_ENTITY;
};

export type EnumAUDIT_LOG_ACTIONWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.AUDIT_LOG_ACTION
    | Prisma.EnumAUDIT_LOG_ACTIONFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.AUDIT_LOG_ACTION[]
    | Prisma.ListEnumAUDIT_LOG_ACTIONFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.AUDIT_LOG_ACTION[]
    | Prisma.ListEnumAUDIT_LOG_ACTIONFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumAUDIT_LOG_ACTIONWithAggregatesFilter<$PrismaModel>
    | $Enums.AUDIT_LOG_ACTION;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumAUDIT_LOG_ACTIONFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumAUDIT_LOG_ACTIONFilter<$PrismaModel>;
};

export type EnumAUDIT_LOG_ENTITYWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.AUDIT_LOG_ENTITY
    | Prisma.EnumAUDIT_LOG_ENTITYFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.AUDIT_LOG_ENTITY[]
    | Prisma.ListEnumAUDIT_LOG_ENTITYFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.AUDIT_LOG_ENTITY[]
    | Prisma.ListEnumAUDIT_LOG_ENTITYFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumAUDIT_LOG_ENTITYWithAggregatesFilter<$PrismaModel>
    | $Enums.AUDIT_LOG_ENTITY;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumAUDIT_LOG_ENTITYFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumAUDIT_LOG_ENTITYFilter<$PrismaModel>;
};

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedStringFilter<$PrismaModel> | string;
};

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null;
};

export type NestedEnumROLEFilter<$PrismaModel = never> = {
  equals?: $Enums.ROLE | Prisma.EnumROLEFieldRefInput<$PrismaModel>;
  in?: $Enums.ROLE[] | Prisma.ListEnumROLEFieldRefInput<$PrismaModel>;
  notIn?: $Enums.ROLE[] | Prisma.ListEnumROLEFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumROLEFilter<$PrismaModel> | $Enums.ROLE;
};

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string;
};

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null;
  in?:
    | Date[]
    | string[]
    | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
    | null;
  notIn?:
    | Date[]
    | string[]
    | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
    | null;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedDateTimeNullableFilter<$PrismaModel>
    | Date
    | string
    | null;
};

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedStringFilter<$PrismaModel>;
  _max?: Prisma.NestedStringFilter<$PrismaModel>;
};

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntFilter<$PrismaModel> | number;
};

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel>
    | string
    | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>;
};

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null;
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null;
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null;
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null;
};

export type NestedJsonNullableFilter<$PrismaModel = never> =
  | Prisma.PatchUndefined<
      Prisma.Either<
        Required<NestedJsonNullableFilterBase<$PrismaModel>>,
        Exclude<
          keyof Required<NestedJsonNullableFilterBase<$PrismaModel>>,
          "path"
        >
      >,
      Required<NestedJsonNullableFilterBase<$PrismaModel>>
    >
  | Prisma.OptionalFlat<
      Omit<Required<NestedJsonNullableFilterBase<$PrismaModel>>, "path">
    >;

export type NestedJsonNullableFilterBase<$PrismaModel = never> = {
  equals?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
  path?: string[];
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>;
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  array_starts_with?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | null;
  array_ends_with?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | null;
  array_contains?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | null;
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>;
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>;
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>;
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>;
  not?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
};

export type NestedEnumROLEWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ROLE | Prisma.EnumROLEFieldRefInput<$PrismaModel>;
  in?: $Enums.ROLE[] | Prisma.ListEnumROLEFieldRefInput<$PrismaModel>;
  notIn?: $Enums.ROLE[] | Prisma.ListEnumROLEFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumROLEWithAggregatesFilter<$PrismaModel> | $Enums.ROLE;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumROLEFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumROLEFilter<$PrismaModel>;
};

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>;
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>;
};

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null;
  in?:
    | Date[]
    | string[]
    | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
    | null;
  notIn?:
    | Date[]
    | string[]
    | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
    | null;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel>
    | Date
    | string
    | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>;
};

export type NestedEnumSESSION_DEVICE_TYPEFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.SESSION_DEVICE_TYPE
    | Prisma.EnumSESSION_DEVICE_TYPEFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.SESSION_DEVICE_TYPE[]
    | Prisma.ListEnumSESSION_DEVICE_TYPEFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.SESSION_DEVICE_TYPE[]
    | Prisma.ListEnumSESSION_DEVICE_TYPEFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumSESSION_DEVICE_TYPEFilter<$PrismaModel>
    | $Enums.SESSION_DEVICE_TYPE;
};

export type NestedEnumSESSION_DEVICE_TYPEWithAggregatesFilter<
  $PrismaModel = never,
> = {
  equals?:
    | $Enums.SESSION_DEVICE_TYPE
    | Prisma.EnumSESSION_DEVICE_TYPEFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.SESSION_DEVICE_TYPE[]
    | Prisma.ListEnumSESSION_DEVICE_TYPEFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.SESSION_DEVICE_TYPE[]
    | Prisma.ListEnumSESSION_DEVICE_TYPEFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumSESSION_DEVICE_TYPEWithAggregatesFilter<$PrismaModel>
    | $Enums.SESSION_DEVICE_TYPE;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumSESSION_DEVICE_TYPEFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumSESSION_DEVICE_TYPEFilter<$PrismaModel>;
};

export type NestedEnumWORKSPACE_ACCOUNT_TYPEFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.WORKSPACE_ACCOUNT_TYPE
    | Prisma.EnumWORKSPACE_ACCOUNT_TYPEFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.WORKSPACE_ACCOUNT_TYPE[]
    | Prisma.ListEnumWORKSPACE_ACCOUNT_TYPEFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.WORKSPACE_ACCOUNT_TYPE[]
    | Prisma.ListEnumWORKSPACE_ACCOUNT_TYPEFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumWORKSPACE_ACCOUNT_TYPEFilter<$PrismaModel>
    | $Enums.WORKSPACE_ACCOUNT_TYPE;
};

export type NestedEnumWORKSPACE_ACCOUNT_TYPEWithAggregatesFilter<
  $PrismaModel = never,
> = {
  equals?:
    | $Enums.WORKSPACE_ACCOUNT_TYPE
    | Prisma.EnumWORKSPACE_ACCOUNT_TYPEFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.WORKSPACE_ACCOUNT_TYPE[]
    | Prisma.ListEnumWORKSPACE_ACCOUNT_TYPEFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.WORKSPACE_ACCOUNT_TYPE[]
    | Prisma.ListEnumWORKSPACE_ACCOUNT_TYPEFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumWORKSPACE_ACCOUNT_TYPEWithAggregatesFilter<$PrismaModel>
    | $Enums.WORKSPACE_ACCOUNT_TYPE;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumWORKSPACE_ACCOUNT_TYPEFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumWORKSPACE_ACCOUNT_TYPEFilter<$PrismaModel>;
};

export type NestedEnumRELEASE_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.RELEASE_STATUS
    | Prisma.EnumRELEASE_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.RELEASE_STATUS[]
    | Prisma.ListEnumRELEASE_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.RELEASE_STATUS[]
    | Prisma.ListEnumRELEASE_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumRELEASE_STATUSFilter<$PrismaModel>
    | $Enums.RELEASE_STATUS;
};

export type NestedEnumRELEASE_STATUSWithAggregatesFilter<$PrismaModel = never> =
  {
    equals?:
      | $Enums.RELEASE_STATUS
      | Prisma.EnumRELEASE_STATUSFieldRefInput<$PrismaModel>;
    in?:
      | $Enums.RELEASE_STATUS[]
      | Prisma.ListEnumRELEASE_STATUSFieldRefInput<$PrismaModel>;
    notIn?:
      | $Enums.RELEASE_STATUS[]
      | Prisma.ListEnumRELEASE_STATUSFieldRefInput<$PrismaModel>;
    not?:
      | Prisma.NestedEnumRELEASE_STATUSWithAggregatesFilter<$PrismaModel>
      | $Enums.RELEASE_STATUS;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedEnumRELEASE_STATUSFilter<$PrismaModel>;
    _max?: Prisma.NestedEnumRELEASE_STATUSFilter<$PrismaModel>;
  };

export type NestedEnumTRACK_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.TRACK_STATUS
    | Prisma.EnumTRACK_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.TRACK_STATUS[]
    | Prisma.ListEnumTRACK_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.TRACK_STATUS[]
    | Prisma.ListEnumTRACK_STATUSFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumTRACK_STATUSFilter<$PrismaModel> | $Enums.TRACK_STATUS;
};

export type NestedEnumTRACK_STATUSWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.TRACK_STATUS
    | Prisma.EnumTRACK_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.TRACK_STATUS[]
    | Prisma.ListEnumTRACK_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.TRACK_STATUS[]
    | Prisma.ListEnumTRACK_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumTRACK_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.TRACK_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumTRACK_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumTRACK_STATUSFilter<$PrismaModel>;
};

export type NestedEnumVIDEO_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.VIDEO_STATUS
    | Prisma.EnumVIDEO_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.VIDEO_STATUS[]
    | Prisma.ListEnumVIDEO_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.VIDEO_STATUS[]
    | Prisma.ListEnumVIDEO_STATUSFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumVIDEO_STATUSFilter<$PrismaModel> | $Enums.VIDEO_STATUS;
};

export type NestedEnumVIDEO_STATUSWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.VIDEO_STATUS
    | Prisma.EnumVIDEO_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.VIDEO_STATUS[]
    | Prisma.ListEnumVIDEO_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.VIDEO_STATUS[]
    | Prisma.ListEnumVIDEO_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumVIDEO_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.VIDEO_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumVIDEO_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumVIDEO_STATUSFilter<$PrismaModel>;
};

export type NestedEnumRINGTONE_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.RINGTONE_STATUS
    | Prisma.EnumRINGTONE_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.RINGTONE_STATUS[]
    | Prisma.ListEnumRINGTONE_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.RINGTONE_STATUS[]
    | Prisma.ListEnumRINGTONE_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumRINGTONE_STATUSFilter<$PrismaModel>
    | $Enums.RINGTONE_STATUS;
};

export type NestedEnumRINGTONE_STATUSWithAggregatesFilter<
  $PrismaModel = never,
> = {
  equals?:
    | $Enums.RINGTONE_STATUS
    | Prisma.EnumRINGTONE_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.RINGTONE_STATUS[]
    | Prisma.ListEnumRINGTONE_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.RINGTONE_STATUS[]
    | Prisma.ListEnumRINGTONE_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumRINGTONE_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.RINGTONE_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumRINGTONE_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumRINGTONE_STATUSFilter<$PrismaModel>;
};

export type NestedEnumARTIST_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.ARTIST_STATUS
    | Prisma.EnumARTIST_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.ARTIST_STATUS[]
    | Prisma.ListEnumARTIST_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.ARTIST_STATUS[]
    | Prisma.ListEnumARTIST_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumARTIST_STATUSFilter<$PrismaModel>
    | $Enums.ARTIST_STATUS;
};

export type NestedEnumARTIST_STATUSWithAggregatesFilter<$PrismaModel = never> =
  {
    equals?:
      | $Enums.ARTIST_STATUS
      | Prisma.EnumARTIST_STATUSFieldRefInput<$PrismaModel>;
    in?:
      | $Enums.ARTIST_STATUS[]
      | Prisma.ListEnumARTIST_STATUSFieldRefInput<$PrismaModel>;
    notIn?:
      | $Enums.ARTIST_STATUS[]
      | Prisma.ListEnumARTIST_STATUSFieldRefInput<$PrismaModel>;
    not?:
      | Prisma.NestedEnumARTIST_STATUSWithAggregatesFilter<$PrismaModel>
      | $Enums.ARTIST_STATUS;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedEnumARTIST_STATUSFilter<$PrismaModel>;
    _max?: Prisma.NestedEnumARTIST_STATUSFilter<$PrismaModel>;
  };

export type NestedEnumPERFORMER_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.PERFORMER_STATUS
    | Prisma.EnumPERFORMER_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.PERFORMER_STATUS[]
    | Prisma.ListEnumPERFORMER_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.PERFORMER_STATUS[]
    | Prisma.ListEnumPERFORMER_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumPERFORMER_STATUSFilter<$PrismaModel>
    | $Enums.PERFORMER_STATUS;
};

export type NestedEnumPERFORMER_STATUSWithAggregatesFilter<
  $PrismaModel = never,
> = {
  equals?:
    | $Enums.PERFORMER_STATUS
    | Prisma.EnumPERFORMER_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.PERFORMER_STATUS[]
    | Prisma.ListEnumPERFORMER_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.PERFORMER_STATUS[]
    | Prisma.ListEnumPERFORMER_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumPERFORMER_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.PERFORMER_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumPERFORMER_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumPERFORMER_STATUSFilter<$PrismaModel>;
};

export type NestedEnumPRODUCER_AND_ENGINEER_STATUSFilter<$PrismaModel = never> =
  {
    equals?:
      | $Enums.PRODUCER_AND_ENGINEER_STATUS
      | Prisma.EnumPRODUCER_AND_ENGINEER_STATUSFieldRefInput<$PrismaModel>;
    in?:
      | $Enums.PRODUCER_AND_ENGINEER_STATUS[]
      | Prisma.ListEnumPRODUCER_AND_ENGINEER_STATUSFieldRefInput<$PrismaModel>;
    notIn?:
      | $Enums.PRODUCER_AND_ENGINEER_STATUS[]
      | Prisma.ListEnumPRODUCER_AND_ENGINEER_STATUSFieldRefInput<$PrismaModel>;
    not?:
      | Prisma.NestedEnumPRODUCER_AND_ENGINEER_STATUSFilter<$PrismaModel>
      | $Enums.PRODUCER_AND_ENGINEER_STATUS;
  };

export type NestedEnumPRODUCER_AND_ENGINEER_STATUSWithAggregatesFilter<
  $PrismaModel = never,
> = {
  equals?:
    | $Enums.PRODUCER_AND_ENGINEER_STATUS
    | Prisma.EnumPRODUCER_AND_ENGINEER_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.PRODUCER_AND_ENGINEER_STATUS[]
    | Prisma.ListEnumPRODUCER_AND_ENGINEER_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.PRODUCER_AND_ENGINEER_STATUS[]
    | Prisma.ListEnumPRODUCER_AND_ENGINEER_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumPRODUCER_AND_ENGINEER_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.PRODUCER_AND_ENGINEER_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumPRODUCER_AND_ENGINEER_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumPRODUCER_AND_ENGINEER_STATUSFilter<$PrismaModel>;
};

export type NestedEnumWRITER_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.WRITER_STATUS
    | Prisma.EnumWRITER_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.WRITER_STATUS[]
    | Prisma.ListEnumWRITER_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.WRITER_STATUS[]
    | Prisma.ListEnumWRITER_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumWRITER_STATUSFilter<$PrismaModel>
    | $Enums.WRITER_STATUS;
};

export type NestedEnumWRITER_STATUSWithAggregatesFilter<$PrismaModel = never> =
  {
    equals?:
      | $Enums.WRITER_STATUS
      | Prisma.EnumWRITER_STATUSFieldRefInput<$PrismaModel>;
    in?:
      | $Enums.WRITER_STATUS[]
      | Prisma.ListEnumWRITER_STATUSFieldRefInput<$PrismaModel>;
    notIn?:
      | $Enums.WRITER_STATUS[]
      | Prisma.ListEnumWRITER_STATUSFieldRefInput<$PrismaModel>;
    not?:
      | Prisma.NestedEnumWRITER_STATUSWithAggregatesFilter<$PrismaModel>
      | $Enums.WRITER_STATUS;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedEnumWRITER_STATUSFilter<$PrismaModel>;
    _max?: Prisma.NestedEnumWRITER_STATUSFilter<$PrismaModel>;
  };

export type NestedEnumPUBLISHER_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.PUBLISHER_STATUS
    | Prisma.EnumPUBLISHER_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.PUBLISHER_STATUS[]
    | Prisma.ListEnumPUBLISHER_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.PUBLISHER_STATUS[]
    | Prisma.ListEnumPUBLISHER_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumPUBLISHER_STATUSFilter<$PrismaModel>
    | $Enums.PUBLISHER_STATUS;
};

export type NestedEnumPUBLISHER_STATUSWithAggregatesFilter<
  $PrismaModel = never,
> = {
  equals?:
    | $Enums.PUBLISHER_STATUS
    | Prisma.EnumPUBLISHER_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.PUBLISHER_STATUS[]
    | Prisma.ListEnumPUBLISHER_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.PUBLISHER_STATUS[]
    | Prisma.ListEnumPUBLISHER_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumPUBLISHER_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.PUBLISHER_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumPUBLISHER_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumPUBLISHER_STATUSFilter<$PrismaModel>;
};

export type NestedEnumLABEL_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.LABEL_STATUS
    | Prisma.EnumLABEL_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.LABEL_STATUS[]
    | Prisma.ListEnumLABEL_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.LABEL_STATUS[]
    | Prisma.ListEnumLABEL_STATUSFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumLABEL_STATUSFilter<$PrismaModel> | $Enums.LABEL_STATUS;
};

export type NestedEnumLABEL_STATUSWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.LABEL_STATUS
    | Prisma.EnumLABEL_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.LABEL_STATUS[]
    | Prisma.ListEnumLABEL_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.LABEL_STATUS[]
    | Prisma.ListEnumLABEL_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumLABEL_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.LABEL_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumLABEL_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumLABEL_STATUSFilter<$PrismaModel>;
};

export type NestedEnumTRANSACTION_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.TRANSACTION_STATUS
    | Prisma.EnumTRANSACTION_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.TRANSACTION_STATUS[]
    | Prisma.ListEnumTRANSACTION_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.TRANSACTION_STATUS[]
    | Prisma.ListEnumTRANSACTION_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumTRANSACTION_STATUSFilter<$PrismaModel>
    | $Enums.TRANSACTION_STATUS;
};

export type NestedEnumTRANSACTION_STATUSWithAggregatesFilter<
  $PrismaModel = never,
> = {
  equals?:
    | $Enums.TRANSACTION_STATUS
    | Prisma.EnumTRANSACTION_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.TRANSACTION_STATUS[]
    | Prisma.ListEnumTRANSACTION_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.TRANSACTION_STATUS[]
    | Prisma.ListEnumTRANSACTION_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumTRANSACTION_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.TRANSACTION_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumTRANSACTION_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumTRANSACTION_STATUSFilter<$PrismaModel>;
};

export type NestedEnumWITHDRAWAL_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.WITHDRAWAL_STATUS
    | Prisma.EnumWITHDRAWAL_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.WITHDRAWAL_STATUS[]
    | Prisma.ListEnumWITHDRAWAL_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.WITHDRAWAL_STATUS[]
    | Prisma.ListEnumWITHDRAWAL_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumWITHDRAWAL_STATUSFilter<$PrismaModel>
    | $Enums.WITHDRAWAL_STATUS;
};

export type NestedEnumWITHDRAWAL_STATUSWithAggregatesFilter<
  $PrismaModel = never,
> = {
  equals?:
    | $Enums.WITHDRAWAL_STATUS
    | Prisma.EnumWITHDRAWAL_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.WITHDRAWAL_STATUS[]
    | Prisma.ListEnumWITHDRAWAL_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.WITHDRAWAL_STATUS[]
    | Prisma.ListEnumWITHDRAWAL_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumWITHDRAWAL_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.WITHDRAWAL_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumWITHDRAWAL_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumWITHDRAWAL_STATUSFilter<$PrismaModel>;
};

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean;
};

export type NestedEnumWORKSPACE_ACCOUNT_ACCESS_ROLEFilter<
  $PrismaModel = never,
> = {
  equals?:
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE[]
    | Prisma.ListEnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE[]
    | Prisma.ListEnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumWORKSPACE_ACCOUNT_ACCESS_ROLEFilter<$PrismaModel>
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
};

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedBoolFilter<$PrismaModel>;
  _max?: Prisma.NestedBoolFilter<$PrismaModel>;
};

export type NestedEnumWORKSPACE_ACCOUNT_ACCESS_ROLEWithAggregatesFilter<
  $PrismaModel = never,
> = {
  equals?:
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE[]
    | Prisma.ListEnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE[]
    | Prisma.ListEnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumWORKSPACE_ACCOUNT_ACCESS_ROLEWithAggregatesFilter<$PrismaModel>
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumWORKSPACE_ACCOUNT_ACCESS_ROLEFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumWORKSPACE_ACCOUNT_ACCESS_ROLEFilter<$PrismaModel>;
};

export type NestedEnumRIGHTS_MANAGEMENT_STATUSFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.RIGHTS_MANAGEMENT_STATUS
    | Prisma.EnumRIGHTS_MANAGEMENT_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.RIGHTS_MANAGEMENT_STATUS[]
    | Prisma.ListEnumRIGHTS_MANAGEMENT_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.RIGHTS_MANAGEMENT_STATUS[]
    | Prisma.ListEnumRIGHTS_MANAGEMENT_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumRIGHTS_MANAGEMENT_STATUSFilter<$PrismaModel>
    | $Enums.RIGHTS_MANAGEMENT_STATUS;
};

export type NestedEnumRIGHTS_MANAGEMENT_STATUSWithAggregatesFilter<
  $PrismaModel = never,
> = {
  equals?:
    | $Enums.RIGHTS_MANAGEMENT_STATUS
    | Prisma.EnumRIGHTS_MANAGEMENT_STATUSFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.RIGHTS_MANAGEMENT_STATUS[]
    | Prisma.ListEnumRIGHTS_MANAGEMENT_STATUSFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.RIGHTS_MANAGEMENT_STATUS[]
    | Prisma.ListEnumRIGHTS_MANAGEMENT_STATUSFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumRIGHTS_MANAGEMENT_STATUSWithAggregatesFilter<$PrismaModel>
    | $Enums.RIGHTS_MANAGEMENT_STATUS;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumRIGHTS_MANAGEMENT_STATUSFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumRIGHTS_MANAGEMENT_STATUSFilter<$PrismaModel>;
};

export type NestedEnumAUDIT_LOG_ACTIONFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.AUDIT_LOG_ACTION
    | Prisma.EnumAUDIT_LOG_ACTIONFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.AUDIT_LOG_ACTION[]
    | Prisma.ListEnumAUDIT_LOG_ACTIONFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.AUDIT_LOG_ACTION[]
    | Prisma.ListEnumAUDIT_LOG_ACTIONFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumAUDIT_LOG_ACTIONFilter<$PrismaModel>
    | $Enums.AUDIT_LOG_ACTION;
};

export type NestedEnumAUDIT_LOG_ENTITYFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.AUDIT_LOG_ENTITY
    | Prisma.EnumAUDIT_LOG_ENTITYFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.AUDIT_LOG_ENTITY[]
    | Prisma.ListEnumAUDIT_LOG_ENTITYFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.AUDIT_LOG_ENTITY[]
    | Prisma.ListEnumAUDIT_LOG_ENTITYFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumAUDIT_LOG_ENTITYFilter<$PrismaModel>
    | $Enums.AUDIT_LOG_ENTITY;
};

export type NestedEnumAUDIT_LOG_ACTIONWithAggregatesFilter<
  $PrismaModel = never,
> = {
  equals?:
    | $Enums.AUDIT_LOG_ACTION
    | Prisma.EnumAUDIT_LOG_ACTIONFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.AUDIT_LOG_ACTION[]
    | Prisma.ListEnumAUDIT_LOG_ACTIONFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.AUDIT_LOG_ACTION[]
    | Prisma.ListEnumAUDIT_LOG_ACTIONFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumAUDIT_LOG_ACTIONWithAggregatesFilter<$PrismaModel>
    | $Enums.AUDIT_LOG_ACTION;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumAUDIT_LOG_ACTIONFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumAUDIT_LOG_ACTIONFilter<$PrismaModel>;
};

export type NestedEnumAUDIT_LOG_ENTITYWithAggregatesFilter<
  $PrismaModel = never,
> = {
  equals?:
    | $Enums.AUDIT_LOG_ENTITY
    | Prisma.EnumAUDIT_LOG_ENTITYFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.AUDIT_LOG_ENTITY[]
    | Prisma.ListEnumAUDIT_LOG_ENTITYFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.AUDIT_LOG_ENTITY[]
    | Prisma.ListEnumAUDIT_LOG_ENTITYFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumAUDIT_LOG_ENTITYWithAggregatesFilter<$PrismaModel>
    | $Enums.AUDIT_LOG_ENTITY;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumAUDIT_LOG_ENTITYFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumAUDIT_LOG_ENTITYFilter<$PrismaModel>;
};
