/*
  Warnings:

  - The values [RELEASED] on the enum `RELEASE_STATUS` will be removed. If these variants are still used in the database, this will fail.
  - The values [TAKEDOWN] on the enum `RELEASE_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [RELEASED] on the enum `RINGTONE_STATUS` will be removed. If these variants are still used in the database, this will fail.
  - The values [TAKEDOWN] on the enum `RINGTONE_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [RELEASED] on the enum `VIDEO_STATUS` will be removed. If these variants are still used in the database, this will fail.
  - The values [TAKEDOWN] on the enum `VIDEO_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "RELEASE_STATUS_new" AS ENUM ('PENDING', 'PROCESSING', 'APPROVED', 'REJECTED', 'SUSPENDED', 'TAKENDOWN', 'DISTRIBUTED');
ALTER TABLE "public"."Release" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Release" ALTER COLUMN "status" TYPE "RELEASE_STATUS_new" USING ("status"::text::"RELEASE_STATUS_new");
ALTER TYPE "RELEASE_STATUS" RENAME TO "RELEASE_STATUS_old";
ALTER TYPE "RELEASE_STATUS_new" RENAME TO "RELEASE_STATUS";
DROP TYPE "public"."RELEASE_STATUS_old";
ALTER TABLE "Release" ALTER COLUMN "status" SET DEFAULT 'PENDING';
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "RELEASE_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'APPROVE', 'STATUS', 'CREATE', 'UPDATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "releasesAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "releasesAccessLevel" TYPE "RELEASE_SYSTEM_ACCESS_LEVEL_new"[] USING ("releasesAccessLevel"::text::"RELEASE_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "RELEASE_SYSTEM_ACCESS_LEVEL" RENAME TO "RELEASE_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "RELEASE_SYSTEM_ACCESS_LEVEL_new" RENAME TO "RELEASE_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."RELEASE_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "releasesAccessLevel" SET DEFAULT ARRAY[]::"RELEASE_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "RINGTONE_STATUS_new" AS ENUM ('PENDING', 'PROCESSING', 'APPROVED', 'REJECTED', 'SUSPENDED', 'TAKENDOWN', 'DISTRIBUTED');
ALTER TABLE "public"."Ringtone" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Ringtone" ALTER COLUMN "status" TYPE "RINGTONE_STATUS_new" USING ("status"::text::"RINGTONE_STATUS_new");
ALTER TYPE "RINGTONE_STATUS" RENAME TO "RINGTONE_STATUS_old";
ALTER TYPE "RINGTONE_STATUS_new" RENAME TO "RINGTONE_STATUS";
DROP TYPE "public"."RINGTONE_STATUS_old";
ALTER TABLE "Ringtone" ALTER COLUMN "status" SET DEFAULT 'PENDING';
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "RINGTONE_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'APPROVE', 'STATUS', 'CREATE', 'UPDATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "ringtonesAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "ringtonesAccessLevel" TYPE "RINGTONE_SYSTEM_ACCESS_LEVEL_new"[] USING ("ringtonesAccessLevel"::text::"RINGTONE_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "RINGTONE_SYSTEM_ACCESS_LEVEL" RENAME TO "RINGTONE_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "RINGTONE_SYSTEM_ACCESS_LEVEL_new" RENAME TO "RINGTONE_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."RINGTONE_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "ringtonesAccessLevel" SET DEFAULT ARRAY[]::"RINGTONE_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "VIDEO_STATUS_new" AS ENUM ('PENDING', 'PROCESSING', 'APPROVED', 'REJECTED', 'SUSPENDED', 'TAKENDOWN', 'DISTRIBUTED');
ALTER TABLE "public"."Video" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Video" ALTER COLUMN "status" TYPE "VIDEO_STATUS_new" USING ("status"::text::"VIDEO_STATUS_new");
ALTER TYPE "VIDEO_STATUS" RENAME TO "VIDEO_STATUS_old";
ALTER TYPE "VIDEO_STATUS_new" RENAME TO "VIDEO_STATUS";
DROP TYPE "public"."VIDEO_STATUS_old";
ALTER TABLE "Video" ALTER COLUMN "status" SET DEFAULT 'PENDING';
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "VIDEO_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'APPROVE', 'STATUS', 'CREATE', 'UPDATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "videosAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "videosAccessLevel" TYPE "VIDEO_SYSTEM_ACCESS_LEVEL_new"[] USING ("videosAccessLevel"::text::"VIDEO_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "VIDEO_SYSTEM_ACCESS_LEVEL" RENAME TO "VIDEO_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "VIDEO_SYSTEM_ACCESS_LEVEL_new" RENAME TO "VIDEO_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."VIDEO_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "videosAccessLevel" SET DEFAULT ARRAY[]::"VIDEO_SYSTEM_ACCESS_LEVEL"[];
COMMIT;
