-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "AUDIT_LOG_ENTITY" ADD VALUE 'RELEASE';
ALTER TYPE "AUDIT_LOG_ENTITY" ADD VALUE 'TRACK';
ALTER TYPE "AUDIT_LOG_ENTITY" ADD VALUE 'VIDEO';
ALTER TYPE "AUDIT_LOG_ENTITY" ADD VALUE 'RINGTONE';
ALTER TYPE "AUDIT_LOG_ENTITY" ADD VALUE 'ARTIST';
ALTER TYPE "AUDIT_LOG_ENTITY" ADD VALUE 'PERFORMER';
ALTER TYPE "AUDIT_LOG_ENTITY" ADD VALUE 'PRODUCER_AND_ENGINEER';
ALTER TYPE "AUDIT_LOG_ENTITY" ADD VALUE 'WRITER';
ALTER TYPE "AUDIT_LOG_ENTITY" ADD VALUE 'PUBLISHER';
ALTER TYPE "AUDIT_LOG_ENTITY" ADD VALUE 'LABEL';
ALTER TYPE "AUDIT_LOG_ENTITY" ADD VALUE 'TRANSACTION';
ALTER TYPE "AUDIT_LOG_ENTITY" ADD VALUE 'WITHDRAWAL';
