/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `RightsManagement` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums";
import type * as Prisma from "../internal/prismaNamespace";

/**
 * Model RightsManagement
 *
 */
export type RightsManagementModel =
  runtime.Types.Result.DefaultSelection<Prisma.$RightsManagementPayload>;

export type AggregateRightsManagement = {
  _count: RightsManagementCountAggregateOutputType | null;
  _min: RightsManagementMinAggregateOutputType | null;
  _max: RightsManagementMaxAggregateOutputType | null;
};

export type RightsManagementMinAggregateOutputType = {
  id: string | null;
  userId: string | null;
  status: $Enums.RIGHTS_MANAGEMENT_STATUS | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type RightsManagementMaxAggregateOutputType = {
  id: string | null;
  userId: string | null;
  status: $Enums.RIGHTS_MANAGEMENT_STATUS | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type RightsManagementCountAggregateOutputType = {
  id: number;
  userId: number;
  metadata: number;
  status: number;
  createdAt: number;
  updatedAt: number;
  _all: number;
};

export type RightsManagementMinAggregateInputType = {
  id?: true;
  userId?: true;
  status?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type RightsManagementMaxAggregateInputType = {
  id?: true;
  userId?: true;
  status?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type RightsManagementCountAggregateInputType = {
  id?: true;
  userId?: true;
  metadata?: true;
  status?: true;
  createdAt?: true;
  updatedAt?: true;
  _all?: true;
};

export type RightsManagementAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which RightsManagement to aggregate.
   */
  where?: Prisma.RightsManagementWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of RightsManagements to fetch.
   */
  orderBy?:
    | Prisma.RightsManagementOrderByWithRelationInput
    | Prisma.RightsManagementOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.RightsManagementWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` RightsManagements from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` RightsManagements.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned RightsManagements
   **/
  _count?: true | RightsManagementCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: RightsManagementMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: RightsManagementMaxAggregateInputType;
};

export type GetRightsManagementAggregateType<
  T extends RightsManagementAggregateArgs,
> = {
  [P in keyof T & keyof AggregateRightsManagement]: P extends "_count" | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRightsManagement[P]>
    : Prisma.GetScalarType<T[P], AggregateRightsManagement[P]>;
};

export type RightsManagementGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.RightsManagementWhereInput;
  orderBy?:
    | Prisma.RightsManagementOrderByWithAggregationInput
    | Prisma.RightsManagementOrderByWithAggregationInput[];
  by:
    | Prisma.RightsManagementScalarFieldEnum[]
    | Prisma.RightsManagementScalarFieldEnum;
  having?: Prisma.RightsManagementScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: RightsManagementCountAggregateInputType | true;
  _min?: RightsManagementMinAggregateInputType;
  _max?: RightsManagementMaxAggregateInputType;
};

export type RightsManagementGroupByOutputType = {
  id: string;
  userId: string;
  metadata: runtime.JsonValue | null;
  status: $Enums.RIGHTS_MANAGEMENT_STATUS;
  createdAt: Date;
  updatedAt: Date;
  _count: RightsManagementCountAggregateOutputType | null;
  _min: RightsManagementMinAggregateOutputType | null;
  _max: RightsManagementMaxAggregateOutputType | null;
};

type GetRightsManagementGroupByPayload<T extends RightsManagementGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<RightsManagementGroupByOutputType, T["by"]> & {
        [P in keyof T &
          keyof RightsManagementGroupByOutputType]: P extends "_count"
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RightsManagementGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RightsManagementGroupByOutputType[P]>;
      }
    >
  >;

export type RightsManagementWhereInput = {
  AND?: Prisma.RightsManagementWhereInput | Prisma.RightsManagementWhereInput[];
  OR?: Prisma.RightsManagementWhereInput[];
  NOT?: Prisma.RightsManagementWhereInput | Prisma.RightsManagementWhereInput[];
  id?: Prisma.StringFilter<"RightsManagement"> | string;
  userId?: Prisma.StringFilter<"RightsManagement"> | string;
  metadata?: Prisma.JsonNullableFilter<"RightsManagement">;
  status?:
    | Prisma.EnumRIGHTS_MANAGEMENT_STATUSFilter<"RightsManagement">
    | $Enums.RIGHTS_MANAGEMENT_STATUS;
  createdAt?: Prisma.DateTimeFilter<"RightsManagement"> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<"RightsManagement"> | Date | string;
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
};

export type RightsManagementOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  user?: Prisma.UserOrderByWithRelationInput;
};

export type RightsManagementWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    AND?:
      | Prisma.RightsManagementWhereInput
      | Prisma.RightsManagementWhereInput[];
    OR?: Prisma.RightsManagementWhereInput[];
    NOT?:
      | Prisma.RightsManagementWhereInput
      | Prisma.RightsManagementWhereInput[];
    userId?: Prisma.StringFilter<"RightsManagement"> | string;
    metadata?: Prisma.JsonNullableFilter<"RightsManagement">;
    status?:
      | Prisma.EnumRIGHTS_MANAGEMENT_STATUSFilter<"RightsManagement">
      | $Enums.RIGHTS_MANAGEMENT_STATUS;
    createdAt?: Prisma.DateTimeFilter<"RightsManagement"> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<"RightsManagement"> | Date | string;
    user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
  },
  "id"
>;

export type RightsManagementOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  _count?: Prisma.RightsManagementCountOrderByAggregateInput;
  _max?: Prisma.RightsManagementMaxOrderByAggregateInput;
  _min?: Prisma.RightsManagementMinOrderByAggregateInput;
};

export type RightsManagementScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.RightsManagementScalarWhereWithAggregatesInput
    | Prisma.RightsManagementScalarWhereWithAggregatesInput[];
  OR?: Prisma.RightsManagementScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.RightsManagementScalarWhereWithAggregatesInput
    | Prisma.RightsManagementScalarWhereWithAggregatesInput[];
  id?: Prisma.StringWithAggregatesFilter<"RightsManagement"> | string;
  userId?: Prisma.StringWithAggregatesFilter<"RightsManagement"> | string;
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"RightsManagement">;
  status?:
    | Prisma.EnumRIGHTS_MANAGEMENT_STATUSWithAggregatesFilter<"RightsManagement">
    | $Enums.RIGHTS_MANAGEMENT_STATUS;
  createdAt?:
    | Prisma.DateTimeWithAggregatesFilter<"RightsManagement">
    | Date
    | string;
  updatedAt?:
    | Prisma.DateTimeWithAggregatesFilter<"RightsManagement">
    | Date
    | string;
};

export type RightsManagementCreateInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.RIGHTS_MANAGEMENT_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  user: Prisma.UserCreateNestedOneWithoutRightsManagementsInput;
};

export type RightsManagementUncheckedCreateInput = {
  id?: string;
  userId: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.RIGHTS_MANAGEMENT_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type RightsManagementUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumRIGHTS_MANAGEMENT_STATUSFieldUpdateOperationsInput
    | $Enums.RIGHTS_MANAGEMENT_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  user?: Prisma.UserUpdateOneRequiredWithoutRightsManagementsNestedInput;
};

export type RightsManagementUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumRIGHTS_MANAGEMENT_STATUSFieldUpdateOperationsInput
    | $Enums.RIGHTS_MANAGEMENT_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type RightsManagementCreateManyInput = {
  id?: string;
  userId: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.RIGHTS_MANAGEMENT_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type RightsManagementUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumRIGHTS_MANAGEMENT_STATUSFieldUpdateOperationsInput
    | $Enums.RIGHTS_MANAGEMENT_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type RightsManagementUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumRIGHTS_MANAGEMENT_STATUSFieldUpdateOperationsInput
    | $Enums.RIGHTS_MANAGEMENT_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type RightsManagementListRelationFilter = {
  every?: Prisma.RightsManagementWhereInput;
  some?: Prisma.RightsManagementWhereInput;
  none?: Prisma.RightsManagementWhereInput;
};

export type RightsManagementOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type RightsManagementCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  metadata?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type RightsManagementMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type RightsManagementMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type RightsManagementCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.RightsManagementCreateWithoutUserInput,
        Prisma.RightsManagementUncheckedCreateWithoutUserInput
      >
    | Prisma.RightsManagementCreateWithoutUserInput[]
    | Prisma.RightsManagementUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.RightsManagementCreateOrConnectWithoutUserInput
    | Prisma.RightsManagementCreateOrConnectWithoutUserInput[];
  createMany?: Prisma.RightsManagementCreateManyUserInputEnvelope;
  connect?:
    | Prisma.RightsManagementWhereUniqueInput
    | Prisma.RightsManagementWhereUniqueInput[];
};

export type RightsManagementUncheckedCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.RightsManagementCreateWithoutUserInput,
        Prisma.RightsManagementUncheckedCreateWithoutUserInput
      >
    | Prisma.RightsManagementCreateWithoutUserInput[]
    | Prisma.RightsManagementUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.RightsManagementCreateOrConnectWithoutUserInput
    | Prisma.RightsManagementCreateOrConnectWithoutUserInput[];
  createMany?: Prisma.RightsManagementCreateManyUserInputEnvelope;
  connect?:
    | Prisma.RightsManagementWhereUniqueInput
    | Prisma.RightsManagementWhereUniqueInput[];
};

export type RightsManagementUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.RightsManagementCreateWithoutUserInput,
        Prisma.RightsManagementUncheckedCreateWithoutUserInput
      >
    | Prisma.RightsManagementCreateWithoutUserInput[]
    | Prisma.RightsManagementUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.RightsManagementCreateOrConnectWithoutUserInput
    | Prisma.RightsManagementCreateOrConnectWithoutUserInput[];
  upsert?:
    | Prisma.RightsManagementUpsertWithWhereUniqueWithoutUserInput
    | Prisma.RightsManagementUpsertWithWhereUniqueWithoutUserInput[];
  createMany?: Prisma.RightsManagementCreateManyUserInputEnvelope;
  set?:
    | Prisma.RightsManagementWhereUniqueInput
    | Prisma.RightsManagementWhereUniqueInput[];
  disconnect?:
    | Prisma.RightsManagementWhereUniqueInput
    | Prisma.RightsManagementWhereUniqueInput[];
  delete?:
    | Prisma.RightsManagementWhereUniqueInput
    | Prisma.RightsManagementWhereUniqueInput[];
  connect?:
    | Prisma.RightsManagementWhereUniqueInput
    | Prisma.RightsManagementWhereUniqueInput[];
  update?:
    | Prisma.RightsManagementUpdateWithWhereUniqueWithoutUserInput
    | Prisma.RightsManagementUpdateWithWhereUniqueWithoutUserInput[];
  updateMany?:
    | Prisma.RightsManagementUpdateManyWithWhereWithoutUserInput
    | Prisma.RightsManagementUpdateManyWithWhereWithoutUserInput[];
  deleteMany?:
    | Prisma.RightsManagementScalarWhereInput
    | Prisma.RightsManagementScalarWhereInput[];
};

export type RightsManagementUncheckedUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.RightsManagementCreateWithoutUserInput,
        Prisma.RightsManagementUncheckedCreateWithoutUserInput
      >
    | Prisma.RightsManagementCreateWithoutUserInput[]
    | Prisma.RightsManagementUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.RightsManagementCreateOrConnectWithoutUserInput
    | Prisma.RightsManagementCreateOrConnectWithoutUserInput[];
  upsert?:
    | Prisma.RightsManagementUpsertWithWhereUniqueWithoutUserInput
    | Prisma.RightsManagementUpsertWithWhereUniqueWithoutUserInput[];
  createMany?: Prisma.RightsManagementCreateManyUserInputEnvelope;
  set?:
    | Prisma.RightsManagementWhereUniqueInput
    | Prisma.RightsManagementWhereUniqueInput[];
  disconnect?:
    | Prisma.RightsManagementWhereUniqueInput
    | Prisma.RightsManagementWhereUniqueInput[];
  delete?:
    | Prisma.RightsManagementWhereUniqueInput
    | Prisma.RightsManagementWhereUniqueInput[];
  connect?:
    | Prisma.RightsManagementWhereUniqueInput
    | Prisma.RightsManagementWhereUniqueInput[];
  update?:
    | Prisma.RightsManagementUpdateWithWhereUniqueWithoutUserInput
    | Prisma.RightsManagementUpdateWithWhereUniqueWithoutUserInput[];
  updateMany?:
    | Prisma.RightsManagementUpdateManyWithWhereWithoutUserInput
    | Prisma.RightsManagementUpdateManyWithWhereWithoutUserInput[];
  deleteMany?:
    | Prisma.RightsManagementScalarWhereInput
    | Prisma.RightsManagementScalarWhereInput[];
};

export type EnumRIGHTS_MANAGEMENT_STATUSFieldUpdateOperationsInput = {
  set?: $Enums.RIGHTS_MANAGEMENT_STATUS;
};

export type RightsManagementCreateWithoutUserInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.RIGHTS_MANAGEMENT_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type RightsManagementUncheckedCreateWithoutUserInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.RIGHTS_MANAGEMENT_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type RightsManagementCreateOrConnectWithoutUserInput = {
  where: Prisma.RightsManagementWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.RightsManagementCreateWithoutUserInput,
    Prisma.RightsManagementUncheckedCreateWithoutUserInput
  >;
};

export type RightsManagementCreateManyUserInputEnvelope = {
  data:
    | Prisma.RightsManagementCreateManyUserInput
    | Prisma.RightsManagementCreateManyUserInput[];
  skipDuplicates?: boolean;
};

export type RightsManagementUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.RightsManagementWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.RightsManagementUpdateWithoutUserInput,
    Prisma.RightsManagementUncheckedUpdateWithoutUserInput
  >;
  create: Prisma.XOR<
    Prisma.RightsManagementCreateWithoutUserInput,
    Prisma.RightsManagementUncheckedCreateWithoutUserInput
  >;
};

export type RightsManagementUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.RightsManagementWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.RightsManagementUpdateWithoutUserInput,
    Prisma.RightsManagementUncheckedUpdateWithoutUserInput
  >;
};

export type RightsManagementUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.RightsManagementScalarWhereInput;
  data: Prisma.XOR<
    Prisma.RightsManagementUpdateManyMutationInput,
    Prisma.RightsManagementUncheckedUpdateManyWithoutUserInput
  >;
};

export type RightsManagementScalarWhereInput = {
  AND?:
    | Prisma.RightsManagementScalarWhereInput
    | Prisma.RightsManagementScalarWhereInput[];
  OR?: Prisma.RightsManagementScalarWhereInput[];
  NOT?:
    | Prisma.RightsManagementScalarWhereInput
    | Prisma.RightsManagementScalarWhereInput[];
  id?: Prisma.StringFilter<"RightsManagement"> | string;
  userId?: Prisma.StringFilter<"RightsManagement"> | string;
  metadata?: Prisma.JsonNullableFilter<"RightsManagement">;
  status?:
    | Prisma.EnumRIGHTS_MANAGEMENT_STATUSFilter<"RightsManagement">
    | $Enums.RIGHTS_MANAGEMENT_STATUS;
  createdAt?: Prisma.DateTimeFilter<"RightsManagement"> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<"RightsManagement"> | Date | string;
};

export type RightsManagementCreateManyUserInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.RIGHTS_MANAGEMENT_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type RightsManagementUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumRIGHTS_MANAGEMENT_STATUSFieldUpdateOperationsInput
    | $Enums.RIGHTS_MANAGEMENT_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type RightsManagementUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumRIGHTS_MANAGEMENT_STATUSFieldUpdateOperationsInput
    | $Enums.RIGHTS_MANAGEMENT_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type RightsManagementUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumRIGHTS_MANAGEMENT_STATUSFieldUpdateOperationsInput
    | $Enums.RIGHTS_MANAGEMENT_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type RightsManagementSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    userId?: boolean;
    metadata?: boolean;
    status?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["rightsManagement"]
>;

export type RightsManagementSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    userId?: boolean;
    metadata?: boolean;
    status?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["rightsManagement"]
>;

export type RightsManagementSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    userId?: boolean;
    metadata?: boolean;
    status?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["rightsManagement"]
>;

export type RightsManagementSelectScalar = {
  id?: boolean;
  userId?: boolean;
  metadata?: boolean;
  status?: boolean;
  createdAt?: boolean;
  updatedAt?: boolean;
};

export type RightsManagementOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  "id" | "userId" | "metadata" | "status" | "createdAt" | "updatedAt",
  ExtArgs["result"]["rightsManagement"]
>;
export type RightsManagementInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};
export type RightsManagementIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};
export type RightsManagementIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};

export type $RightsManagementPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: "RightsManagement";
  objects: {
    user: Prisma.$UserPayload<ExtArgs>;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      userId: string;
      metadata: runtime.JsonValue | null;
      status: $Enums.RIGHTS_MANAGEMENT_STATUS;
      createdAt: Date;
      updatedAt: Date;
    },
    ExtArgs["result"]["rightsManagement"]
  >;
  composites: {};
};

export type RightsManagementGetPayload<
  S extends boolean | null | undefined | RightsManagementDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$RightsManagementPayload, S>;

export type RightsManagementCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<
  RightsManagementFindManyArgs,
  "select" | "include" | "distinct" | "omit"
> & {
  select?: RightsManagementCountAggregateInputType | true;
};

export interface RightsManagementDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["RightsManagement"];
    meta: { name: "RightsManagement" };
  };
  /**
   * Find zero or one RightsManagement that matches the filter.
   * @param {RightsManagementFindUniqueArgs} args - Arguments to find a RightsManagement
   * @example
   * // Get one RightsManagement
   * const rightsManagement = await prisma.rightsManagement.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RightsManagementFindUniqueArgs>(
    args: Prisma.SelectSubset<T, RightsManagementFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__RightsManagementClient<
    runtime.Types.Result.GetResult<
      Prisma.$RightsManagementPayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one RightsManagement that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RightsManagementFindUniqueOrThrowArgs} args - Arguments to find a RightsManagement
   * @example
   * // Get one RightsManagement
   * const rightsManagement = await prisma.rightsManagement.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RightsManagementFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, RightsManagementFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__RightsManagementClient<
    runtime.Types.Result.GetResult<
      Prisma.$RightsManagementPayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first RightsManagement that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RightsManagementFindFirstArgs} args - Arguments to find a RightsManagement
   * @example
   * // Get one RightsManagement
   * const rightsManagement = await prisma.rightsManagement.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RightsManagementFindFirstArgs>(
    args?: Prisma.SelectSubset<T, RightsManagementFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__RightsManagementClient<
    runtime.Types.Result.GetResult<
      Prisma.$RightsManagementPayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first RightsManagement that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RightsManagementFindFirstOrThrowArgs} args - Arguments to find a RightsManagement
   * @example
   * // Get one RightsManagement
   * const rightsManagement = await prisma.rightsManagement.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RightsManagementFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, RightsManagementFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__RightsManagementClient<
    runtime.Types.Result.GetResult<
      Prisma.$RightsManagementPayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more RightsManagements that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RightsManagementFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RightsManagements
   * const rightsManagements = await prisma.rightsManagement.findMany()
   *
   * // Get first 10 RightsManagements
   * const rightsManagements = await prisma.rightsManagement.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const rightsManagementWithIdOnly = await prisma.rightsManagement.findMany({ select: { id: true } })
   *
   */
  findMany<T extends RightsManagementFindManyArgs>(
    args?: Prisma.SelectSubset<T, RightsManagementFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$RightsManagementPayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >;

  /**
   * Create a RightsManagement.
   * @param {RightsManagementCreateArgs} args - Arguments to create a RightsManagement.
   * @example
   * // Create one RightsManagement
   * const RightsManagement = await prisma.rightsManagement.create({
   *   data: {
   *     // ... data to create a RightsManagement
   *   }
   * })
   *
   */
  create<T extends RightsManagementCreateArgs>(
    args: Prisma.SelectSubset<T, RightsManagementCreateArgs<ExtArgs>>
  ): Prisma.Prisma__RightsManagementClient<
    runtime.Types.Result.GetResult<
      Prisma.$RightsManagementPayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many RightsManagements.
   * @param {RightsManagementCreateManyArgs} args - Arguments to create many RightsManagements.
   * @example
   * // Create many RightsManagements
   * const rightsManagement = await prisma.rightsManagement.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends RightsManagementCreateManyArgs>(
    args?: Prisma.SelectSubset<T, RightsManagementCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many RightsManagements and returns the data saved in the database.
   * @param {RightsManagementCreateManyAndReturnArgs} args - Arguments to create many RightsManagements.
   * @example
   * // Create many RightsManagements
   * const rightsManagement = await prisma.rightsManagement.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many RightsManagements and only return the `id`
   * const rightsManagementWithIdOnly = await prisma.rightsManagement.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends RightsManagementCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<
      T,
      RightsManagementCreateManyAndReturnArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$RightsManagementPayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a RightsManagement.
   * @param {RightsManagementDeleteArgs} args - Arguments to delete one RightsManagement.
   * @example
   * // Delete one RightsManagement
   * const RightsManagement = await prisma.rightsManagement.delete({
   *   where: {
   *     // ... filter to delete one RightsManagement
   *   }
   * })
   *
   */
  delete<T extends RightsManagementDeleteArgs>(
    args: Prisma.SelectSubset<T, RightsManagementDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__RightsManagementClient<
    runtime.Types.Result.GetResult<
      Prisma.$RightsManagementPayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one RightsManagement.
   * @param {RightsManagementUpdateArgs} args - Arguments to update one RightsManagement.
   * @example
   * // Update one RightsManagement
   * const rightsManagement = await prisma.rightsManagement.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends RightsManagementUpdateArgs>(
    args: Prisma.SelectSubset<T, RightsManagementUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__RightsManagementClient<
    runtime.Types.Result.GetResult<
      Prisma.$RightsManagementPayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more RightsManagements.
   * @param {RightsManagementDeleteManyArgs} args - Arguments to filter RightsManagements to delete.
   * @example
   * // Delete a few RightsManagements
   * const { count } = await prisma.rightsManagement.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends RightsManagementDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, RightsManagementDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more RightsManagements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RightsManagementUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RightsManagements
   * const rightsManagement = await prisma.rightsManagement.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends RightsManagementUpdateManyArgs>(
    args: Prisma.SelectSubset<T, RightsManagementUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more RightsManagements and returns the data updated in the database.
   * @param {RightsManagementUpdateManyAndReturnArgs} args - Arguments to update many RightsManagements.
   * @example
   * // Update many RightsManagements
   * const rightsManagement = await prisma.rightsManagement.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more RightsManagements and only return the `id`
   * const rightsManagementWithIdOnly = await prisma.rightsManagement.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends RightsManagementUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<
      T,
      RightsManagementUpdateManyAndReturnArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$RightsManagementPayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one RightsManagement.
   * @param {RightsManagementUpsertArgs} args - Arguments to update or create a RightsManagement.
   * @example
   * // Update or create a RightsManagement
   * const rightsManagement = await prisma.rightsManagement.upsert({
   *   create: {
   *     // ... data to create a RightsManagement
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RightsManagement we want to update
   *   }
   * })
   */
  upsert<T extends RightsManagementUpsertArgs>(
    args: Prisma.SelectSubset<T, RightsManagementUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__RightsManagementClient<
    runtime.Types.Result.GetResult<
      Prisma.$RightsManagementPayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of RightsManagements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RightsManagementCountArgs} args - Arguments to filter RightsManagements to count.
   * @example
   * // Count the number of RightsManagements
   * const count = await prisma.rightsManagement.count({
   *   where: {
   *     // ... the filter for the RightsManagements we want to count
   *   }
   * })
   **/
  count<T extends RightsManagementCountArgs>(
    args?: Prisma.Subset<T, RightsManagementCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<
            T["select"],
            RightsManagementCountAggregateOutputType
          >
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a RightsManagement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RightsManagementAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends RightsManagementAggregateArgs>(
    args: Prisma.Subset<T, RightsManagementAggregateArgs>
  ): Prisma.PrismaPromise<GetRightsManagementAggregateType<T>>;

  /**
   * Group by RightsManagement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RightsManagementGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends RightsManagementGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RightsManagementGroupByArgs["orderBy"] }
      : { orderBy?: RightsManagementGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    "Field ",
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ];
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<
      T,
      RightsManagementGroupByArgs,
      OrderByArg
    > &
      InputErrors
  ): {} extends InputErrors
    ? GetRightsManagementGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the RightsManagement model
   */
  readonly fields: RightsManagementFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RightsManagement.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RightsManagementClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise";
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__UserClient<
    | runtime.Types.Result.GetResult<
        Prisma.$UserPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the RightsManagement model
 */
export interface RightsManagementFieldRefs {
  readonly id: Prisma.FieldRef<"RightsManagement", "String">;
  readonly userId: Prisma.FieldRef<"RightsManagement", "String">;
  readonly metadata: Prisma.FieldRef<"RightsManagement", "Json">;
  readonly status: Prisma.FieldRef<
    "RightsManagement",
    "RIGHTS_MANAGEMENT_STATUS"
  >;
  readonly createdAt: Prisma.FieldRef<"RightsManagement", "DateTime">;
  readonly updatedAt: Prisma.FieldRef<"RightsManagement", "DateTime">;
}

// Custom InputTypes
/**
 * RightsManagement findUnique
 */
export type RightsManagementFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RightsManagement
   */
  select?: Prisma.RightsManagementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the RightsManagement
   */
  omit?: Prisma.RightsManagementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RightsManagementInclude<ExtArgs> | null;
  /**
   * Filter, which RightsManagement to fetch.
   */
  where: Prisma.RightsManagementWhereUniqueInput;
};

/**
 * RightsManagement findUniqueOrThrow
 */
export type RightsManagementFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RightsManagement
   */
  select?: Prisma.RightsManagementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the RightsManagement
   */
  omit?: Prisma.RightsManagementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RightsManagementInclude<ExtArgs> | null;
  /**
   * Filter, which RightsManagement to fetch.
   */
  where: Prisma.RightsManagementWhereUniqueInput;
};

/**
 * RightsManagement findFirst
 */
export type RightsManagementFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RightsManagement
   */
  select?: Prisma.RightsManagementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the RightsManagement
   */
  omit?: Prisma.RightsManagementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RightsManagementInclude<ExtArgs> | null;
  /**
   * Filter, which RightsManagement to fetch.
   */
  where?: Prisma.RightsManagementWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of RightsManagements to fetch.
   */
  orderBy?:
    | Prisma.RightsManagementOrderByWithRelationInput
    | Prisma.RightsManagementOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for RightsManagements.
   */
  cursor?: Prisma.RightsManagementWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` RightsManagements from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` RightsManagements.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of RightsManagements.
   */
  distinct?:
    | Prisma.RightsManagementScalarFieldEnum
    | Prisma.RightsManagementScalarFieldEnum[];
};

/**
 * RightsManagement findFirstOrThrow
 */
export type RightsManagementFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RightsManagement
   */
  select?: Prisma.RightsManagementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the RightsManagement
   */
  omit?: Prisma.RightsManagementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RightsManagementInclude<ExtArgs> | null;
  /**
   * Filter, which RightsManagement to fetch.
   */
  where?: Prisma.RightsManagementWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of RightsManagements to fetch.
   */
  orderBy?:
    | Prisma.RightsManagementOrderByWithRelationInput
    | Prisma.RightsManagementOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for RightsManagements.
   */
  cursor?: Prisma.RightsManagementWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` RightsManagements from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` RightsManagements.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of RightsManagements.
   */
  distinct?:
    | Prisma.RightsManagementScalarFieldEnum
    | Prisma.RightsManagementScalarFieldEnum[];
};

/**
 * RightsManagement findMany
 */
export type RightsManagementFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RightsManagement
   */
  select?: Prisma.RightsManagementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the RightsManagement
   */
  omit?: Prisma.RightsManagementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RightsManagementInclude<ExtArgs> | null;
  /**
   * Filter, which RightsManagements to fetch.
   */
  where?: Prisma.RightsManagementWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of RightsManagements to fetch.
   */
  orderBy?:
    | Prisma.RightsManagementOrderByWithRelationInput
    | Prisma.RightsManagementOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing RightsManagements.
   */
  cursor?: Prisma.RightsManagementWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` RightsManagements from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` RightsManagements.
   */
  skip?: number;
  distinct?:
    | Prisma.RightsManagementScalarFieldEnum
    | Prisma.RightsManagementScalarFieldEnum[];
};

/**
 * RightsManagement create
 */
export type RightsManagementCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RightsManagement
   */
  select?: Prisma.RightsManagementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the RightsManagement
   */
  omit?: Prisma.RightsManagementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RightsManagementInclude<ExtArgs> | null;
  /**
   * The data needed to create a RightsManagement.
   */
  data: Prisma.XOR<
    Prisma.RightsManagementCreateInput,
    Prisma.RightsManagementUncheckedCreateInput
  >;
};

/**
 * RightsManagement createMany
 */
export type RightsManagementCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many RightsManagements.
   */
  data:
    | Prisma.RightsManagementCreateManyInput
    | Prisma.RightsManagementCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * RightsManagement createManyAndReturn
 */
export type RightsManagementCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RightsManagement
   */
  select?: Prisma.RightsManagementSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the RightsManagement
   */
  omit?: Prisma.RightsManagementOmit<ExtArgs> | null;
  /**
   * The data used to create many RightsManagements.
   */
  data:
    | Prisma.RightsManagementCreateManyInput
    | Prisma.RightsManagementCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RightsManagementIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * RightsManagement update
 */
export type RightsManagementUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RightsManagement
   */
  select?: Prisma.RightsManagementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the RightsManagement
   */
  omit?: Prisma.RightsManagementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RightsManagementInclude<ExtArgs> | null;
  /**
   * The data needed to update a RightsManagement.
   */
  data: Prisma.XOR<
    Prisma.RightsManagementUpdateInput,
    Prisma.RightsManagementUncheckedUpdateInput
  >;
  /**
   * Choose, which RightsManagement to update.
   */
  where: Prisma.RightsManagementWhereUniqueInput;
};

/**
 * RightsManagement updateMany
 */
export type RightsManagementUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update RightsManagements.
   */
  data: Prisma.XOR<
    Prisma.RightsManagementUpdateManyMutationInput,
    Prisma.RightsManagementUncheckedUpdateManyInput
  >;
  /**
   * Filter which RightsManagements to update
   */
  where?: Prisma.RightsManagementWhereInput;
  /**
   * Limit how many RightsManagements to update.
   */
  limit?: number;
};

/**
 * RightsManagement updateManyAndReturn
 */
export type RightsManagementUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RightsManagement
   */
  select?: Prisma.RightsManagementSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the RightsManagement
   */
  omit?: Prisma.RightsManagementOmit<ExtArgs> | null;
  /**
   * The data used to update RightsManagements.
   */
  data: Prisma.XOR<
    Prisma.RightsManagementUpdateManyMutationInput,
    Prisma.RightsManagementUncheckedUpdateManyInput
  >;
  /**
   * Filter which RightsManagements to update
   */
  where?: Prisma.RightsManagementWhereInput;
  /**
   * Limit how many RightsManagements to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RightsManagementIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * RightsManagement upsert
 */
export type RightsManagementUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RightsManagement
   */
  select?: Prisma.RightsManagementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the RightsManagement
   */
  omit?: Prisma.RightsManagementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RightsManagementInclude<ExtArgs> | null;
  /**
   * The filter to search for the RightsManagement to update in case it exists.
   */
  where: Prisma.RightsManagementWhereUniqueInput;
  /**
   * In case the RightsManagement found by the `where` argument doesn't exist, create a new RightsManagement with this data.
   */
  create: Prisma.XOR<
    Prisma.RightsManagementCreateInput,
    Prisma.RightsManagementUncheckedCreateInput
  >;
  /**
   * In case the RightsManagement was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.RightsManagementUpdateInput,
    Prisma.RightsManagementUncheckedUpdateInput
  >;
};

/**
 * RightsManagement delete
 */
export type RightsManagementDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RightsManagement
   */
  select?: Prisma.RightsManagementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the RightsManagement
   */
  omit?: Prisma.RightsManagementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RightsManagementInclude<ExtArgs> | null;
  /**
   * Filter which RightsManagement to delete.
   */
  where: Prisma.RightsManagementWhereUniqueInput;
};

/**
 * RightsManagement deleteMany
 */
export type RightsManagementDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which RightsManagements to delete
   */
  where?: Prisma.RightsManagementWhereInput;
  /**
   * Limit how many RightsManagements to delete.
   */
  limit?: number;
};

/**
 * RightsManagement without action
 */
export type RightsManagementDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RightsManagement
   */
  select?: Prisma.RightsManagementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the RightsManagement
   */
  omit?: Prisma.RightsManagementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RightsManagementInclude<ExtArgs> | null;
};
