/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `SharedWorkspaceAccountAccess` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums";
import type * as Prisma from "../internal/prismaNamespace";

/**
 * Model SharedWorkspaceAccountAccess
 *
 */
export type SharedWorkspaceAccountAccessModel =
  runtime.Types.Result.DefaultSelection<Prisma.$SharedWorkspaceAccountAccessPayload>;

export type AggregateSharedWorkspaceAccountAccess = {
  _count: SharedWorkspaceAccountAccessCountAggregateOutputType | null;
  _min: SharedWorkspaceAccountAccessMinAggregateOutputType | null;
  _max: SharedWorkspaceAccountAccessMaxAggregateOutputType | null;
};

export type SharedWorkspaceAccountAccessMinAggregateOutputType = {
  id: string | null;
  workspaceAccountId: string | null;
  userId: string | null;
  assignerId: string | null;
  role: $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE | null;
  status: $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type SharedWorkspaceAccountAccessMaxAggregateOutputType = {
  id: string | null;
  workspaceAccountId: string | null;
  userId: string | null;
  assignerId: string | null;
  role: $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE | null;
  status: $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type SharedWorkspaceAccountAccessCountAggregateOutputType = {
  id: number;
  workspaceAccountId: number;
  userId: number;
  assignerId: number;
  metadata: number;
  role: number;
  status: number;
  createdAt: number;
  updatedAt: number;
  _all: number;
};

export type SharedWorkspaceAccountAccessMinAggregateInputType = {
  id?: true;
  workspaceAccountId?: true;
  userId?: true;
  assignerId?: true;
  role?: true;
  status?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type SharedWorkspaceAccountAccessMaxAggregateInputType = {
  id?: true;
  workspaceAccountId?: true;
  userId?: true;
  assignerId?: true;
  role?: true;
  status?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type SharedWorkspaceAccountAccessCountAggregateInputType = {
  id?: true;
  workspaceAccountId?: true;
  userId?: true;
  assignerId?: true;
  metadata?: true;
  role?: true;
  status?: true;
  createdAt?: true;
  updatedAt?: true;
  _all?: true;
};

export type SharedWorkspaceAccountAccessAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which SharedWorkspaceAccountAccess to aggregate.
   */
  where?: Prisma.SharedWorkspaceAccountAccessWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of SharedWorkspaceAccountAccesses to fetch.
   */
  orderBy?:
    | Prisma.SharedWorkspaceAccountAccessOrderByWithRelationInput
    | Prisma.SharedWorkspaceAccountAccessOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` SharedWorkspaceAccountAccesses from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` SharedWorkspaceAccountAccesses.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned SharedWorkspaceAccountAccesses
   **/
  _count?: true | SharedWorkspaceAccountAccessCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: SharedWorkspaceAccountAccessMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: SharedWorkspaceAccountAccessMaxAggregateInputType;
};

export type GetSharedWorkspaceAccountAccessAggregateType<
  T extends SharedWorkspaceAccountAccessAggregateArgs,
> = {
  [P in keyof T & keyof AggregateSharedWorkspaceAccountAccess]: P extends
    | "_count"
    | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSharedWorkspaceAccountAccess[P]>
    : Prisma.GetScalarType<T[P], AggregateSharedWorkspaceAccountAccess[P]>;
};

export type SharedWorkspaceAccountAccessGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.SharedWorkspaceAccountAccessWhereInput;
  orderBy?:
    | Prisma.SharedWorkspaceAccountAccessOrderByWithAggregationInput
    | Prisma.SharedWorkspaceAccountAccessOrderByWithAggregationInput[];
  by:
    | Prisma.SharedWorkspaceAccountAccessScalarFieldEnum[]
    | Prisma.SharedWorkspaceAccountAccessScalarFieldEnum;
  having?: Prisma.SharedWorkspaceAccountAccessScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: SharedWorkspaceAccountAccessCountAggregateInputType | true;
  _min?: SharedWorkspaceAccountAccessMinAggregateInputType;
  _max?: SharedWorkspaceAccountAccessMaxAggregateInputType;
};

export type SharedWorkspaceAccountAccessGroupByOutputType = {
  id: string;
  workspaceAccountId: string;
  userId: string;
  assignerId: string;
  metadata: runtime.JsonValue | null;
  role: $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status: $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt: Date;
  updatedAt: Date;
  _count: SharedWorkspaceAccountAccessCountAggregateOutputType | null;
  _min: SharedWorkspaceAccountAccessMinAggregateOutputType | null;
  _max: SharedWorkspaceAccountAccessMaxAggregateOutputType | null;
};

type GetSharedWorkspaceAccountAccessGroupByPayload<
  T extends SharedWorkspaceAccountAccessGroupByArgs,
> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<
      SharedWorkspaceAccountAccessGroupByOutputType,
      T["by"]
    > & {
      [P in keyof T &
        keyof SharedWorkspaceAccountAccessGroupByOutputType]: P extends "_count"
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<
              T[P],
              SharedWorkspaceAccountAccessGroupByOutputType[P]
            >
        : Prisma.GetScalarType<
            T[P],
            SharedWorkspaceAccountAccessGroupByOutputType[P]
          >;
    }
  >
>;

export type SharedWorkspaceAccountAccessWhereInput = {
  AND?:
    | Prisma.SharedWorkspaceAccountAccessWhereInput
    | Prisma.SharedWorkspaceAccountAccessWhereInput[];
  OR?: Prisma.SharedWorkspaceAccountAccessWhereInput[];
  NOT?:
    | Prisma.SharedWorkspaceAccountAccessWhereInput
    | Prisma.SharedWorkspaceAccountAccessWhereInput[];
  id?: Prisma.StringFilter<"SharedWorkspaceAccountAccess"> | string;
  workspaceAccountId?:
    | Prisma.StringFilter<"SharedWorkspaceAccountAccess">
    | string;
  userId?: Prisma.StringFilter<"SharedWorkspaceAccountAccess"> | string;
  assignerId?: Prisma.StringFilter<"SharedWorkspaceAccountAccess"> | string;
  metadata?: Prisma.JsonNullableFilter<"SharedWorkspaceAccountAccess">;
  role?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFilter<"SharedWorkspaceAccountAccess">
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_STATUSFilter<"SharedWorkspaceAccountAccess">
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?:
    | Prisma.DateTimeFilter<"SharedWorkspaceAccountAccess">
    | Date
    | string;
  updatedAt?:
    | Prisma.DateTimeFilter<"SharedWorkspaceAccountAccess">
    | Date
    | string;
  workspaceAccount?: Prisma.XOR<
    Prisma.WorkspaceAccountScalarRelationFilter,
    Prisma.WorkspaceAccountWhereInput
  >;
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
  assigner?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
};

export type SharedWorkspaceAccountAccessOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  workspaceAccountId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  assignerId?: Prisma.SortOrder;
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder;
  role?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  workspaceAccount?: Prisma.WorkspaceAccountOrderByWithRelationInput;
  user?: Prisma.UserOrderByWithRelationInput;
  assigner?: Prisma.UserOrderByWithRelationInput;
};

export type SharedWorkspaceAccountAccessWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    AND?:
      | Prisma.SharedWorkspaceAccountAccessWhereInput
      | Prisma.SharedWorkspaceAccountAccessWhereInput[];
    OR?: Prisma.SharedWorkspaceAccountAccessWhereInput[];
    NOT?:
      | Prisma.SharedWorkspaceAccountAccessWhereInput
      | Prisma.SharedWorkspaceAccountAccessWhereInput[];
    workspaceAccountId?:
      | Prisma.StringFilter<"SharedWorkspaceAccountAccess">
      | string;
    userId?: Prisma.StringFilter<"SharedWorkspaceAccountAccess"> | string;
    assignerId?: Prisma.StringFilter<"SharedWorkspaceAccountAccess"> | string;
    metadata?: Prisma.JsonNullableFilter<"SharedWorkspaceAccountAccess">;
    role?:
      | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFilter<"SharedWorkspaceAccountAccess">
      | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
    status?:
      | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_STATUSFilter<"SharedWorkspaceAccountAccess">
      | $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
    createdAt?:
      | Prisma.DateTimeFilter<"SharedWorkspaceAccountAccess">
      | Date
      | string;
    updatedAt?:
      | Prisma.DateTimeFilter<"SharedWorkspaceAccountAccess">
      | Date
      | string;
    workspaceAccount?: Prisma.XOR<
      Prisma.WorkspaceAccountScalarRelationFilter,
      Prisma.WorkspaceAccountWhereInput
    >;
    user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
    assigner?: Prisma.XOR<
      Prisma.UserScalarRelationFilter,
      Prisma.UserWhereInput
    >;
  },
  "id"
>;

export type SharedWorkspaceAccountAccessOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  workspaceAccountId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  assignerId?: Prisma.SortOrder;
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder;
  role?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  _count?: Prisma.SharedWorkspaceAccountAccessCountOrderByAggregateInput;
  _max?: Prisma.SharedWorkspaceAccountAccessMaxOrderByAggregateInput;
  _min?: Prisma.SharedWorkspaceAccountAccessMinOrderByAggregateInput;
};

export type SharedWorkspaceAccountAccessScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.SharedWorkspaceAccountAccessScalarWhereWithAggregatesInput
    | Prisma.SharedWorkspaceAccountAccessScalarWhereWithAggregatesInput[];
  OR?: Prisma.SharedWorkspaceAccountAccessScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.SharedWorkspaceAccountAccessScalarWhereWithAggregatesInput
    | Prisma.SharedWorkspaceAccountAccessScalarWhereWithAggregatesInput[];
  id?:
    | Prisma.StringWithAggregatesFilter<"SharedWorkspaceAccountAccess">
    | string;
  workspaceAccountId?:
    | Prisma.StringWithAggregatesFilter<"SharedWorkspaceAccountAccess">
    | string;
  userId?:
    | Prisma.StringWithAggregatesFilter<"SharedWorkspaceAccountAccess">
    | string;
  assignerId?:
    | Prisma.StringWithAggregatesFilter<"SharedWorkspaceAccountAccess">
    | string;
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"SharedWorkspaceAccountAccess">;
  role?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEWithAggregatesFilter<"SharedWorkspaceAccountAccess">
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_STATUSWithAggregatesFilter<"SharedWorkspaceAccountAccess">
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?:
    | Prisma.DateTimeWithAggregatesFilter<"SharedWorkspaceAccountAccess">
    | Date
    | string;
  updatedAt?:
    | Prisma.DateTimeWithAggregatesFilter<"SharedWorkspaceAccountAccess">
    | Date
    | string;
};

export type SharedWorkspaceAccountAccessCreateInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?: $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?: $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  workspaceAccount: Prisma.WorkspaceAccountCreateNestedOneWithoutSharedAccessesInput;
  user: Prisma.UserCreateNestedOneWithoutSharedWorkspaceAccountAccessesInput;
  assigner: Prisma.UserCreateNestedOneWithoutAssignedWorkspaceAccountAccessesInput;
};

export type SharedWorkspaceAccountAccessUncheckedCreateInput = {
  id?: string;
  workspaceAccountId: string;
  userId: string;
  assignerId: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?: $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?: $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type SharedWorkspaceAccountAccessUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_STATUSFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  workspaceAccount?: Prisma.WorkspaceAccountUpdateOneRequiredWithoutSharedAccessesNestedInput;
  user?: Prisma.UserUpdateOneRequiredWithoutSharedWorkspaceAccountAccessesNestedInput;
  assigner?: Prisma.UserUpdateOneRequiredWithoutAssignedWorkspaceAccountAccessesNestedInput;
};

export type SharedWorkspaceAccountAccessUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  assignerId?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_STATUSFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type SharedWorkspaceAccountAccessCreateManyInput = {
  id?: string;
  workspaceAccountId: string;
  userId: string;
  assignerId: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?: $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?: $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type SharedWorkspaceAccountAccessUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_STATUSFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type SharedWorkspaceAccountAccessUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  assignerId?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_STATUSFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type SharedWorkspaceAccountAccessListRelationFilter = {
  every?: Prisma.SharedWorkspaceAccountAccessWhereInput;
  some?: Prisma.SharedWorkspaceAccountAccessWhereInput;
  none?: Prisma.SharedWorkspaceAccountAccessWhereInput;
};

export type SharedWorkspaceAccountAccessOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type SharedWorkspaceAccountAccessCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  workspaceAccountId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  assignerId?: Prisma.SortOrder;
  metadata?: Prisma.SortOrder;
  role?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type SharedWorkspaceAccountAccessMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  workspaceAccountId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  assignerId?: Prisma.SortOrder;
  role?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type SharedWorkspaceAccountAccessMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  workspaceAccountId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  assignerId?: Prisma.SortOrder;
  role?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type SharedWorkspaceAccountAccessCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.SharedWorkspaceAccountAccessCreateWithoutUserInput,
        Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutUserInput
      >
    | Prisma.SharedWorkspaceAccountAccessCreateWithoutUserInput[]
    | Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutUserInput
    | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutUserInput[];
  createMany?: Prisma.SharedWorkspaceAccountAccessCreateManyUserInputEnvelope;
  connect?:
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
};

export type SharedWorkspaceAccountAccessCreateNestedManyWithoutAssignerInput = {
  create?:
    | Prisma.XOR<
        Prisma.SharedWorkspaceAccountAccessCreateWithoutAssignerInput,
        Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutAssignerInput
      >
    | Prisma.SharedWorkspaceAccountAccessCreateWithoutAssignerInput[]
    | Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutAssignerInput[];
  connectOrCreate?:
    | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutAssignerInput
    | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutAssignerInput[];
  createMany?: Prisma.SharedWorkspaceAccountAccessCreateManyAssignerInputEnvelope;
  connect?:
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
};

export type SharedWorkspaceAccountAccessUncheckedCreateNestedManyWithoutUserInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.SharedWorkspaceAccountAccessCreateWithoutUserInput,
          Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutUserInput
        >
      | Prisma.SharedWorkspaceAccountAccessCreateWithoutUserInput[]
      | Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
      | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutUserInput
      | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutUserInput[];
    createMany?: Prisma.SharedWorkspaceAccountAccessCreateManyUserInputEnvelope;
    connect?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
  };

export type SharedWorkspaceAccountAccessUncheckedCreateNestedManyWithoutAssignerInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.SharedWorkspaceAccountAccessCreateWithoutAssignerInput,
          Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutAssignerInput
        >
      | Prisma.SharedWorkspaceAccountAccessCreateWithoutAssignerInput[]
      | Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutAssignerInput[];
    connectOrCreate?:
      | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutAssignerInput
      | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutAssignerInput[];
    createMany?: Prisma.SharedWorkspaceAccountAccessCreateManyAssignerInputEnvelope;
    connect?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
  };

export type SharedWorkspaceAccountAccessUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.SharedWorkspaceAccountAccessCreateWithoutUserInput,
        Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutUserInput
      >
    | Prisma.SharedWorkspaceAccountAccessCreateWithoutUserInput[]
    | Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutUserInput
    | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutUserInput[];
  upsert?:
    | Prisma.SharedWorkspaceAccountAccessUpsertWithWhereUniqueWithoutUserInput
    | Prisma.SharedWorkspaceAccountAccessUpsertWithWhereUniqueWithoutUserInput[];
  createMany?: Prisma.SharedWorkspaceAccountAccessCreateManyUserInputEnvelope;
  set?:
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
  disconnect?:
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
  delete?:
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
  connect?:
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
  update?:
    | Prisma.SharedWorkspaceAccountAccessUpdateWithWhereUniqueWithoutUserInput
    | Prisma.SharedWorkspaceAccountAccessUpdateWithWhereUniqueWithoutUserInput[];
  updateMany?:
    | Prisma.SharedWorkspaceAccountAccessUpdateManyWithWhereWithoutUserInput
    | Prisma.SharedWorkspaceAccountAccessUpdateManyWithWhereWithoutUserInput[];
  deleteMany?:
    | Prisma.SharedWorkspaceAccountAccessScalarWhereInput
    | Prisma.SharedWorkspaceAccountAccessScalarWhereInput[];
};

export type SharedWorkspaceAccountAccessUpdateManyWithoutAssignerNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.SharedWorkspaceAccountAccessCreateWithoutAssignerInput,
        Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutAssignerInput
      >
    | Prisma.SharedWorkspaceAccountAccessCreateWithoutAssignerInput[]
    | Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutAssignerInput[];
  connectOrCreate?:
    | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutAssignerInput
    | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutAssignerInput[];
  upsert?:
    | Prisma.SharedWorkspaceAccountAccessUpsertWithWhereUniqueWithoutAssignerInput
    | Prisma.SharedWorkspaceAccountAccessUpsertWithWhereUniqueWithoutAssignerInput[];
  createMany?: Prisma.SharedWorkspaceAccountAccessCreateManyAssignerInputEnvelope;
  set?:
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
  disconnect?:
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
  delete?:
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
  connect?:
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
    | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
  update?:
    | Prisma.SharedWorkspaceAccountAccessUpdateWithWhereUniqueWithoutAssignerInput
    | Prisma.SharedWorkspaceAccountAccessUpdateWithWhereUniqueWithoutAssignerInput[];
  updateMany?:
    | Prisma.SharedWorkspaceAccountAccessUpdateManyWithWhereWithoutAssignerInput
    | Prisma.SharedWorkspaceAccountAccessUpdateManyWithWhereWithoutAssignerInput[];
  deleteMany?:
    | Prisma.SharedWorkspaceAccountAccessScalarWhereInput
    | Prisma.SharedWorkspaceAccountAccessScalarWhereInput[];
};

export type SharedWorkspaceAccountAccessUncheckedUpdateManyWithoutUserNestedInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.SharedWorkspaceAccountAccessCreateWithoutUserInput,
          Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutUserInput
        >
      | Prisma.SharedWorkspaceAccountAccessCreateWithoutUserInput[]
      | Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
      | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutUserInput
      | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutUserInput[];
    upsert?:
      | Prisma.SharedWorkspaceAccountAccessUpsertWithWhereUniqueWithoutUserInput
      | Prisma.SharedWorkspaceAccountAccessUpsertWithWhereUniqueWithoutUserInput[];
    createMany?: Prisma.SharedWorkspaceAccountAccessCreateManyUserInputEnvelope;
    set?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
    disconnect?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
    delete?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
    connect?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
    update?:
      | Prisma.SharedWorkspaceAccountAccessUpdateWithWhereUniqueWithoutUserInput
      | Prisma.SharedWorkspaceAccountAccessUpdateWithWhereUniqueWithoutUserInput[];
    updateMany?:
      | Prisma.SharedWorkspaceAccountAccessUpdateManyWithWhereWithoutUserInput
      | Prisma.SharedWorkspaceAccountAccessUpdateManyWithWhereWithoutUserInput[];
    deleteMany?:
      | Prisma.SharedWorkspaceAccountAccessScalarWhereInput
      | Prisma.SharedWorkspaceAccountAccessScalarWhereInput[];
  };

export type SharedWorkspaceAccountAccessUncheckedUpdateManyWithoutAssignerNestedInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.SharedWorkspaceAccountAccessCreateWithoutAssignerInput,
          Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutAssignerInput
        >
      | Prisma.SharedWorkspaceAccountAccessCreateWithoutAssignerInput[]
      | Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutAssignerInput[];
    connectOrCreate?:
      | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutAssignerInput
      | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutAssignerInput[];
    upsert?:
      | Prisma.SharedWorkspaceAccountAccessUpsertWithWhereUniqueWithoutAssignerInput
      | Prisma.SharedWorkspaceAccountAccessUpsertWithWhereUniqueWithoutAssignerInput[];
    createMany?: Prisma.SharedWorkspaceAccountAccessCreateManyAssignerInputEnvelope;
    set?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
    disconnect?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
    delete?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
    connect?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
    update?:
      | Prisma.SharedWorkspaceAccountAccessUpdateWithWhereUniqueWithoutAssignerInput
      | Prisma.SharedWorkspaceAccountAccessUpdateWithWhereUniqueWithoutAssignerInput[];
    updateMany?:
      | Prisma.SharedWorkspaceAccountAccessUpdateManyWithWhereWithoutAssignerInput
      | Prisma.SharedWorkspaceAccountAccessUpdateManyWithWhereWithoutAssignerInput[];
    deleteMany?:
      | Prisma.SharedWorkspaceAccountAccessScalarWhereInput
      | Prisma.SharedWorkspaceAccountAccessScalarWhereInput[];
  };

export type SharedWorkspaceAccountAccessCreateNestedManyWithoutWorkspaceAccountInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.SharedWorkspaceAccountAccessCreateWithoutWorkspaceAccountInput,
          Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutWorkspaceAccountInput
        >
      | Prisma.SharedWorkspaceAccountAccessCreateWithoutWorkspaceAccountInput[]
      | Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutWorkspaceAccountInput[];
    connectOrCreate?:
      | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutWorkspaceAccountInput
      | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutWorkspaceAccountInput[];
    createMany?: Prisma.SharedWorkspaceAccountAccessCreateManyWorkspaceAccountInputEnvelope;
    connect?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
  };

export type SharedWorkspaceAccountAccessUncheckedCreateNestedManyWithoutWorkspaceAccountInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.SharedWorkspaceAccountAccessCreateWithoutWorkspaceAccountInput,
          Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutWorkspaceAccountInput
        >
      | Prisma.SharedWorkspaceAccountAccessCreateWithoutWorkspaceAccountInput[]
      | Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutWorkspaceAccountInput[];
    connectOrCreate?:
      | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutWorkspaceAccountInput
      | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutWorkspaceAccountInput[];
    createMany?: Prisma.SharedWorkspaceAccountAccessCreateManyWorkspaceAccountInputEnvelope;
    connect?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
  };

export type SharedWorkspaceAccountAccessUpdateManyWithoutWorkspaceAccountNestedInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.SharedWorkspaceAccountAccessCreateWithoutWorkspaceAccountInput,
          Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutWorkspaceAccountInput
        >
      | Prisma.SharedWorkspaceAccountAccessCreateWithoutWorkspaceAccountInput[]
      | Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutWorkspaceAccountInput[];
    connectOrCreate?:
      | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutWorkspaceAccountInput
      | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutWorkspaceAccountInput[];
    upsert?:
      | Prisma.SharedWorkspaceAccountAccessUpsertWithWhereUniqueWithoutWorkspaceAccountInput
      | Prisma.SharedWorkspaceAccountAccessUpsertWithWhereUniqueWithoutWorkspaceAccountInput[];
    createMany?: Prisma.SharedWorkspaceAccountAccessCreateManyWorkspaceAccountInputEnvelope;
    set?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
    disconnect?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
    delete?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
    connect?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
    update?:
      | Prisma.SharedWorkspaceAccountAccessUpdateWithWhereUniqueWithoutWorkspaceAccountInput
      | Prisma.SharedWorkspaceAccountAccessUpdateWithWhereUniqueWithoutWorkspaceAccountInput[];
    updateMany?:
      | Prisma.SharedWorkspaceAccountAccessUpdateManyWithWhereWithoutWorkspaceAccountInput
      | Prisma.SharedWorkspaceAccountAccessUpdateManyWithWhereWithoutWorkspaceAccountInput[];
    deleteMany?:
      | Prisma.SharedWorkspaceAccountAccessScalarWhereInput
      | Prisma.SharedWorkspaceAccountAccessScalarWhereInput[];
  };

export type SharedWorkspaceAccountAccessUncheckedUpdateManyWithoutWorkspaceAccountNestedInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.SharedWorkspaceAccountAccessCreateWithoutWorkspaceAccountInput,
          Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutWorkspaceAccountInput
        >
      | Prisma.SharedWorkspaceAccountAccessCreateWithoutWorkspaceAccountInput[]
      | Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutWorkspaceAccountInput[];
    connectOrCreate?:
      | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutWorkspaceAccountInput
      | Prisma.SharedWorkspaceAccountAccessCreateOrConnectWithoutWorkspaceAccountInput[];
    upsert?:
      | Prisma.SharedWorkspaceAccountAccessUpsertWithWhereUniqueWithoutWorkspaceAccountInput
      | Prisma.SharedWorkspaceAccountAccessUpsertWithWhereUniqueWithoutWorkspaceAccountInput[];
    createMany?: Prisma.SharedWorkspaceAccountAccessCreateManyWorkspaceAccountInputEnvelope;
    set?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
    disconnect?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
    delete?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
    connect?:
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput
      | Prisma.SharedWorkspaceAccountAccessWhereUniqueInput[];
    update?:
      | Prisma.SharedWorkspaceAccountAccessUpdateWithWhereUniqueWithoutWorkspaceAccountInput
      | Prisma.SharedWorkspaceAccountAccessUpdateWithWhereUniqueWithoutWorkspaceAccountInput[];
    updateMany?:
      | Prisma.SharedWorkspaceAccountAccessUpdateManyWithWhereWithoutWorkspaceAccountInput
      | Prisma.SharedWorkspaceAccountAccessUpdateManyWithWhereWithoutWorkspaceAccountInput[];
    deleteMany?:
      | Prisma.SharedWorkspaceAccountAccessScalarWhereInput
      | Prisma.SharedWorkspaceAccountAccessScalarWhereInput[];
  };

export type EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldUpdateOperationsInput = {
  set?: $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
};

export type EnumWORKSPACE_ACCOUNT_ACCESS_STATUSFieldUpdateOperationsInput = {
  set?: $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
};

export type SharedWorkspaceAccountAccessCreateWithoutUserInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?: $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?: $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  workspaceAccount: Prisma.WorkspaceAccountCreateNestedOneWithoutSharedAccessesInput;
  assigner: Prisma.UserCreateNestedOneWithoutAssignedWorkspaceAccountAccessesInput;
};

export type SharedWorkspaceAccountAccessUncheckedCreateWithoutUserInput = {
  id?: string;
  workspaceAccountId: string;
  assignerId: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?: $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?: $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type SharedWorkspaceAccountAccessCreateOrConnectWithoutUserInput = {
  where: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.SharedWorkspaceAccountAccessCreateWithoutUserInput,
    Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutUserInput
  >;
};

export type SharedWorkspaceAccountAccessCreateManyUserInputEnvelope = {
  data:
    | Prisma.SharedWorkspaceAccountAccessCreateManyUserInput
    | Prisma.SharedWorkspaceAccountAccessCreateManyUserInput[];
  skipDuplicates?: boolean;
};

export type SharedWorkspaceAccountAccessCreateWithoutAssignerInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?: $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?: $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  workspaceAccount: Prisma.WorkspaceAccountCreateNestedOneWithoutSharedAccessesInput;
  user: Prisma.UserCreateNestedOneWithoutSharedWorkspaceAccountAccessesInput;
};

export type SharedWorkspaceAccountAccessUncheckedCreateWithoutAssignerInput = {
  id?: string;
  workspaceAccountId: string;
  userId: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?: $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?: $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type SharedWorkspaceAccountAccessCreateOrConnectWithoutAssignerInput = {
  where: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.SharedWorkspaceAccountAccessCreateWithoutAssignerInput,
    Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutAssignerInput
  >;
};

export type SharedWorkspaceAccountAccessCreateManyAssignerInputEnvelope = {
  data:
    | Prisma.SharedWorkspaceAccountAccessCreateManyAssignerInput
    | Prisma.SharedWorkspaceAccountAccessCreateManyAssignerInput[];
  skipDuplicates?: boolean;
};

export type SharedWorkspaceAccountAccessUpsertWithWhereUniqueWithoutUserInput =
  {
    where: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
    update: Prisma.XOR<
      Prisma.SharedWorkspaceAccountAccessUpdateWithoutUserInput,
      Prisma.SharedWorkspaceAccountAccessUncheckedUpdateWithoutUserInput
    >;
    create: Prisma.XOR<
      Prisma.SharedWorkspaceAccountAccessCreateWithoutUserInput,
      Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutUserInput
    >;
  };

export type SharedWorkspaceAccountAccessUpdateWithWhereUniqueWithoutUserInput =
  {
    where: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
    data: Prisma.XOR<
      Prisma.SharedWorkspaceAccountAccessUpdateWithoutUserInput,
      Prisma.SharedWorkspaceAccountAccessUncheckedUpdateWithoutUserInput
    >;
  };

export type SharedWorkspaceAccountAccessUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.SharedWorkspaceAccountAccessScalarWhereInput;
  data: Prisma.XOR<
    Prisma.SharedWorkspaceAccountAccessUpdateManyMutationInput,
    Prisma.SharedWorkspaceAccountAccessUncheckedUpdateManyWithoutUserInput
  >;
};

export type SharedWorkspaceAccountAccessScalarWhereInput = {
  AND?:
    | Prisma.SharedWorkspaceAccountAccessScalarWhereInput
    | Prisma.SharedWorkspaceAccountAccessScalarWhereInput[];
  OR?: Prisma.SharedWorkspaceAccountAccessScalarWhereInput[];
  NOT?:
    | Prisma.SharedWorkspaceAccountAccessScalarWhereInput
    | Prisma.SharedWorkspaceAccountAccessScalarWhereInput[];
  id?: Prisma.StringFilter<"SharedWorkspaceAccountAccess"> | string;
  workspaceAccountId?:
    | Prisma.StringFilter<"SharedWorkspaceAccountAccess">
    | string;
  userId?: Prisma.StringFilter<"SharedWorkspaceAccountAccess"> | string;
  assignerId?: Prisma.StringFilter<"SharedWorkspaceAccountAccess"> | string;
  metadata?: Prisma.JsonNullableFilter<"SharedWorkspaceAccountAccess">;
  role?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFilter<"SharedWorkspaceAccountAccess">
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_STATUSFilter<"SharedWorkspaceAccountAccess">
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?:
    | Prisma.DateTimeFilter<"SharedWorkspaceAccountAccess">
    | Date
    | string;
  updatedAt?:
    | Prisma.DateTimeFilter<"SharedWorkspaceAccountAccess">
    | Date
    | string;
};

export type SharedWorkspaceAccountAccessUpsertWithWhereUniqueWithoutAssignerInput =
  {
    where: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
    update: Prisma.XOR<
      Prisma.SharedWorkspaceAccountAccessUpdateWithoutAssignerInput,
      Prisma.SharedWorkspaceAccountAccessUncheckedUpdateWithoutAssignerInput
    >;
    create: Prisma.XOR<
      Prisma.SharedWorkspaceAccountAccessCreateWithoutAssignerInput,
      Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutAssignerInput
    >;
  };

export type SharedWorkspaceAccountAccessUpdateWithWhereUniqueWithoutAssignerInput =
  {
    where: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
    data: Prisma.XOR<
      Prisma.SharedWorkspaceAccountAccessUpdateWithoutAssignerInput,
      Prisma.SharedWorkspaceAccountAccessUncheckedUpdateWithoutAssignerInput
    >;
  };

export type SharedWorkspaceAccountAccessUpdateManyWithWhereWithoutAssignerInput =
  {
    where: Prisma.SharedWorkspaceAccountAccessScalarWhereInput;
    data: Prisma.XOR<
      Prisma.SharedWorkspaceAccountAccessUpdateManyMutationInput,
      Prisma.SharedWorkspaceAccountAccessUncheckedUpdateManyWithoutAssignerInput
    >;
  };

export type SharedWorkspaceAccountAccessCreateWithoutWorkspaceAccountInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?: $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?: $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  user: Prisma.UserCreateNestedOneWithoutSharedWorkspaceAccountAccessesInput;
  assigner: Prisma.UserCreateNestedOneWithoutAssignedWorkspaceAccountAccessesInput;
};

export type SharedWorkspaceAccountAccessUncheckedCreateWithoutWorkspaceAccountInput =
  {
    id?: string;
    userId: string;
    assignerId: string;
    metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
    role?: $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
    status?: $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
    createdAt?: Date | string;
    updatedAt?: Date | string;
  };

export type SharedWorkspaceAccountAccessCreateOrConnectWithoutWorkspaceAccountInput =
  {
    where: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
    create: Prisma.XOR<
      Prisma.SharedWorkspaceAccountAccessCreateWithoutWorkspaceAccountInput,
      Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutWorkspaceAccountInput
    >;
  };

export type SharedWorkspaceAccountAccessCreateManyWorkspaceAccountInputEnvelope =
  {
    data:
      | Prisma.SharedWorkspaceAccountAccessCreateManyWorkspaceAccountInput
      | Prisma.SharedWorkspaceAccountAccessCreateManyWorkspaceAccountInput[];
    skipDuplicates?: boolean;
  };

export type SharedWorkspaceAccountAccessUpsertWithWhereUniqueWithoutWorkspaceAccountInput =
  {
    where: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
    update: Prisma.XOR<
      Prisma.SharedWorkspaceAccountAccessUpdateWithoutWorkspaceAccountInput,
      Prisma.SharedWorkspaceAccountAccessUncheckedUpdateWithoutWorkspaceAccountInput
    >;
    create: Prisma.XOR<
      Prisma.SharedWorkspaceAccountAccessCreateWithoutWorkspaceAccountInput,
      Prisma.SharedWorkspaceAccountAccessUncheckedCreateWithoutWorkspaceAccountInput
    >;
  };

export type SharedWorkspaceAccountAccessUpdateWithWhereUniqueWithoutWorkspaceAccountInput =
  {
    where: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
    data: Prisma.XOR<
      Prisma.SharedWorkspaceAccountAccessUpdateWithoutWorkspaceAccountInput,
      Prisma.SharedWorkspaceAccountAccessUncheckedUpdateWithoutWorkspaceAccountInput
    >;
  };

export type SharedWorkspaceAccountAccessUpdateManyWithWhereWithoutWorkspaceAccountInput =
  {
    where: Prisma.SharedWorkspaceAccountAccessScalarWhereInput;
    data: Prisma.XOR<
      Prisma.SharedWorkspaceAccountAccessUpdateManyMutationInput,
      Prisma.SharedWorkspaceAccountAccessUncheckedUpdateManyWithoutWorkspaceAccountInput
    >;
  };

export type SharedWorkspaceAccountAccessCreateManyUserInput = {
  id?: string;
  workspaceAccountId: string;
  assignerId: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?: $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?: $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type SharedWorkspaceAccountAccessCreateManyAssignerInput = {
  id?: string;
  workspaceAccountId: string;
  userId: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?: $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?: $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type SharedWorkspaceAccountAccessUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_STATUSFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  workspaceAccount?: Prisma.WorkspaceAccountUpdateOneRequiredWithoutSharedAccessesNestedInput;
  assigner?: Prisma.UserUpdateOneRequiredWithoutAssignedWorkspaceAccountAccessesNestedInput;
};

export type SharedWorkspaceAccountAccessUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
  assignerId?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_STATUSFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type SharedWorkspaceAccountAccessUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
  assignerId?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_STATUSFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type SharedWorkspaceAccountAccessUpdateWithoutAssignerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_STATUSFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  workspaceAccount?: Prisma.WorkspaceAccountUpdateOneRequiredWithoutSharedAccessesNestedInput;
  user?: Prisma.UserUpdateOneRequiredWithoutSharedWorkspaceAccountAccessesNestedInput;
};

export type SharedWorkspaceAccountAccessUncheckedUpdateWithoutAssignerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_STATUSFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type SharedWorkspaceAccountAccessUncheckedUpdateManyWithoutAssignerInput =
  {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
    userId?: Prisma.StringFieldUpdateOperationsInput | string;
    metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
    role?:
      | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldUpdateOperationsInput
      | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
    status?:
      | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_STATUSFieldUpdateOperationsInput
      | $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  };

export type SharedWorkspaceAccountAccessCreateManyWorkspaceAccountInput = {
  id?: string;
  userId: string;
  assignerId: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?: $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?: $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type SharedWorkspaceAccountAccessUpdateWithoutWorkspaceAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  role?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
  status?:
    | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_STATUSFieldUpdateOperationsInput
    | $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  user?: Prisma.UserUpdateOneRequiredWithoutSharedWorkspaceAccountAccessesNestedInput;
  assigner?: Prisma.UserUpdateOneRequiredWithoutAssignedWorkspaceAccountAccessesNestedInput;
};

export type SharedWorkspaceAccountAccessUncheckedUpdateWithoutWorkspaceAccountInput =
  {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    userId?: Prisma.StringFieldUpdateOperationsInput | string;
    assignerId?: Prisma.StringFieldUpdateOperationsInput | string;
    metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
    role?:
      | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldUpdateOperationsInput
      | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
    status?:
      | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_STATUSFieldUpdateOperationsInput
      | $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  };

export type SharedWorkspaceAccountAccessUncheckedUpdateManyWithoutWorkspaceAccountInput =
  {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    userId?: Prisma.StringFieldUpdateOperationsInput | string;
    assignerId?: Prisma.StringFieldUpdateOperationsInput | string;
    metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
    role?:
      | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_ROLEFieldUpdateOperationsInput
      | $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
    status?:
      | Prisma.EnumWORKSPACE_ACCOUNT_ACCESS_STATUSFieldUpdateOperationsInput
      | $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  };

export type SharedWorkspaceAccountAccessSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    workspaceAccountId?: boolean;
    userId?: boolean;
    assignerId?: boolean;
    metadata?: boolean;
    role?: boolean;
    status?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    assigner?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["sharedWorkspaceAccountAccess"]
>;

export type SharedWorkspaceAccountAccessSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    workspaceAccountId?: boolean;
    userId?: boolean;
    assignerId?: boolean;
    metadata?: boolean;
    role?: boolean;
    status?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    assigner?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["sharedWorkspaceAccountAccess"]
>;

export type SharedWorkspaceAccountAccessSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    workspaceAccountId?: boolean;
    userId?: boolean;
    assignerId?: boolean;
    metadata?: boolean;
    role?: boolean;
    status?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    assigner?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["sharedWorkspaceAccountAccess"]
>;

export type SharedWorkspaceAccountAccessSelectScalar = {
  id?: boolean;
  workspaceAccountId?: boolean;
  userId?: boolean;
  assignerId?: boolean;
  metadata?: boolean;
  role?: boolean;
  status?: boolean;
  createdAt?: boolean;
  updatedAt?: boolean;
};

export type SharedWorkspaceAccountAccessOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | "id"
  | "workspaceAccountId"
  | "userId"
  | "assignerId"
  | "metadata"
  | "role"
  | "status"
  | "createdAt"
  | "updatedAt",
  ExtArgs["result"]["sharedWorkspaceAccountAccess"]
>;
export type SharedWorkspaceAccountAccessInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  assigner?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};
export type SharedWorkspaceAccountAccessIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  assigner?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};
export type SharedWorkspaceAccountAccessIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  assigner?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};

export type $SharedWorkspaceAccountAccessPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: "SharedWorkspaceAccountAccess";
  objects: {
    workspaceAccount: Prisma.$WorkspaceAccountPayload<ExtArgs>;
    user: Prisma.$UserPayload<ExtArgs>;
    assigner: Prisma.$UserPayload<ExtArgs>;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      workspaceAccountId: string;
      userId: string;
      assignerId: string;
      metadata: runtime.JsonValue | null;
      role: $Enums.WORKSPACE_ACCOUNT_ACCESS_ROLE;
      status: $Enums.WORKSPACE_ACCOUNT_ACCESS_STATUS;
      createdAt: Date;
      updatedAt: Date;
    },
    ExtArgs["result"]["sharedWorkspaceAccountAccess"]
  >;
  composites: {};
};

export type SharedWorkspaceAccountAccessGetPayload<
  S extends
    | boolean
    | null
    | undefined
    | SharedWorkspaceAccountAccessDefaultArgs,
> = runtime.Types.Result.GetResult<
  Prisma.$SharedWorkspaceAccountAccessPayload,
  S
>;

export type SharedWorkspaceAccountAccessCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<
  SharedWorkspaceAccountAccessFindManyArgs,
  "select" | "include" | "distinct" | "omit"
> & {
  select?: SharedWorkspaceAccountAccessCountAggregateInputType | true;
};

export interface SharedWorkspaceAccountAccessDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["SharedWorkspaceAccountAccess"];
    meta: { name: "SharedWorkspaceAccountAccess" };
  };
  /**
   * Find zero or one SharedWorkspaceAccountAccess that matches the filter.
   * @param {SharedWorkspaceAccountAccessFindUniqueArgs} args - Arguments to find a SharedWorkspaceAccountAccess
   * @example
   * // Get one SharedWorkspaceAccountAccess
   * const sharedWorkspaceAccountAccess = await prisma.sharedWorkspaceAccountAccess.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SharedWorkspaceAccountAccessFindUniqueArgs>(
    args: Prisma.SelectSubset<
      T,
      SharedWorkspaceAccountAccessFindUniqueArgs<ExtArgs>
    >
  ): Prisma.Prisma__SharedWorkspaceAccountAccessClient<
    runtime.Types.Result.GetResult<
      Prisma.$SharedWorkspaceAccountAccessPayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one SharedWorkspaceAccountAccess that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SharedWorkspaceAccountAccessFindUniqueOrThrowArgs} args - Arguments to find a SharedWorkspaceAccountAccess
   * @example
   * // Get one SharedWorkspaceAccountAccess
   * const sharedWorkspaceAccountAccess = await prisma.sharedWorkspaceAccountAccess.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<
    T extends SharedWorkspaceAccountAccessFindUniqueOrThrowArgs,
  >(
    args: Prisma.SelectSubset<
      T,
      SharedWorkspaceAccountAccessFindUniqueOrThrowArgs<ExtArgs>
    >
  ): Prisma.Prisma__SharedWorkspaceAccountAccessClient<
    runtime.Types.Result.GetResult<
      Prisma.$SharedWorkspaceAccountAccessPayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first SharedWorkspaceAccountAccess that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SharedWorkspaceAccountAccessFindFirstArgs} args - Arguments to find a SharedWorkspaceAccountAccess
   * @example
   * // Get one SharedWorkspaceAccountAccess
   * const sharedWorkspaceAccountAccess = await prisma.sharedWorkspaceAccountAccess.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SharedWorkspaceAccountAccessFindFirstArgs>(
    args?: Prisma.SelectSubset<
      T,
      SharedWorkspaceAccountAccessFindFirstArgs<ExtArgs>
    >
  ): Prisma.Prisma__SharedWorkspaceAccountAccessClient<
    runtime.Types.Result.GetResult<
      Prisma.$SharedWorkspaceAccountAccessPayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first SharedWorkspaceAccountAccess that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SharedWorkspaceAccountAccessFindFirstOrThrowArgs} args - Arguments to find a SharedWorkspaceAccountAccess
   * @example
   * // Get one SharedWorkspaceAccountAccess
   * const sharedWorkspaceAccountAccess = await prisma.sharedWorkspaceAccountAccess.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SharedWorkspaceAccountAccessFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<
      T,
      SharedWorkspaceAccountAccessFindFirstOrThrowArgs<ExtArgs>
    >
  ): Prisma.Prisma__SharedWorkspaceAccountAccessClient<
    runtime.Types.Result.GetResult<
      Prisma.$SharedWorkspaceAccountAccessPayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more SharedWorkspaceAccountAccesses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SharedWorkspaceAccountAccessFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SharedWorkspaceAccountAccesses
   * const sharedWorkspaceAccountAccesses = await prisma.sharedWorkspaceAccountAccess.findMany()
   *
   * // Get first 10 SharedWorkspaceAccountAccesses
   * const sharedWorkspaceAccountAccesses = await prisma.sharedWorkspaceAccountAccess.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const sharedWorkspaceAccountAccessWithIdOnly = await prisma.sharedWorkspaceAccountAccess.findMany({ select: { id: true } })
   *
   */
  findMany<T extends SharedWorkspaceAccountAccessFindManyArgs>(
    args?: Prisma.SelectSubset<
      T,
      SharedWorkspaceAccountAccessFindManyArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$SharedWorkspaceAccountAccessPayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >;

  /**
   * Create a SharedWorkspaceAccountAccess.
   * @param {SharedWorkspaceAccountAccessCreateArgs} args - Arguments to create a SharedWorkspaceAccountAccess.
   * @example
   * // Create one SharedWorkspaceAccountAccess
   * const SharedWorkspaceAccountAccess = await prisma.sharedWorkspaceAccountAccess.create({
   *   data: {
   *     // ... data to create a SharedWorkspaceAccountAccess
   *   }
   * })
   *
   */
  create<T extends SharedWorkspaceAccountAccessCreateArgs>(
    args: Prisma.SelectSubset<
      T,
      SharedWorkspaceAccountAccessCreateArgs<ExtArgs>
    >
  ): Prisma.Prisma__SharedWorkspaceAccountAccessClient<
    runtime.Types.Result.GetResult<
      Prisma.$SharedWorkspaceAccountAccessPayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many SharedWorkspaceAccountAccesses.
   * @param {SharedWorkspaceAccountAccessCreateManyArgs} args - Arguments to create many SharedWorkspaceAccountAccesses.
   * @example
   * // Create many SharedWorkspaceAccountAccesses
   * const sharedWorkspaceAccountAccess = await prisma.sharedWorkspaceAccountAccess.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends SharedWorkspaceAccountAccessCreateManyArgs>(
    args?: Prisma.SelectSubset<
      T,
      SharedWorkspaceAccountAccessCreateManyArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many SharedWorkspaceAccountAccesses and returns the data saved in the database.
   * @param {SharedWorkspaceAccountAccessCreateManyAndReturnArgs} args - Arguments to create many SharedWorkspaceAccountAccesses.
   * @example
   * // Create many SharedWorkspaceAccountAccesses
   * const sharedWorkspaceAccountAccess = await prisma.sharedWorkspaceAccountAccess.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many SharedWorkspaceAccountAccesses and only return the `id`
   * const sharedWorkspaceAccountAccessWithIdOnly = await prisma.sharedWorkspaceAccountAccess.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<
    T extends SharedWorkspaceAccountAccessCreateManyAndReturnArgs,
  >(
    args?: Prisma.SelectSubset<
      T,
      SharedWorkspaceAccountAccessCreateManyAndReturnArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$SharedWorkspaceAccountAccessPayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a SharedWorkspaceAccountAccess.
   * @param {SharedWorkspaceAccountAccessDeleteArgs} args - Arguments to delete one SharedWorkspaceAccountAccess.
   * @example
   * // Delete one SharedWorkspaceAccountAccess
   * const SharedWorkspaceAccountAccess = await prisma.sharedWorkspaceAccountAccess.delete({
   *   where: {
   *     // ... filter to delete one SharedWorkspaceAccountAccess
   *   }
   * })
   *
   */
  delete<T extends SharedWorkspaceAccountAccessDeleteArgs>(
    args: Prisma.SelectSubset<
      T,
      SharedWorkspaceAccountAccessDeleteArgs<ExtArgs>
    >
  ): Prisma.Prisma__SharedWorkspaceAccountAccessClient<
    runtime.Types.Result.GetResult<
      Prisma.$SharedWorkspaceAccountAccessPayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one SharedWorkspaceAccountAccess.
   * @param {SharedWorkspaceAccountAccessUpdateArgs} args - Arguments to update one SharedWorkspaceAccountAccess.
   * @example
   * // Update one SharedWorkspaceAccountAccess
   * const sharedWorkspaceAccountAccess = await prisma.sharedWorkspaceAccountAccess.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends SharedWorkspaceAccountAccessUpdateArgs>(
    args: Prisma.SelectSubset<
      T,
      SharedWorkspaceAccountAccessUpdateArgs<ExtArgs>
    >
  ): Prisma.Prisma__SharedWorkspaceAccountAccessClient<
    runtime.Types.Result.GetResult<
      Prisma.$SharedWorkspaceAccountAccessPayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more SharedWorkspaceAccountAccesses.
   * @param {SharedWorkspaceAccountAccessDeleteManyArgs} args - Arguments to filter SharedWorkspaceAccountAccesses to delete.
   * @example
   * // Delete a few SharedWorkspaceAccountAccesses
   * const { count } = await prisma.sharedWorkspaceAccountAccess.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends SharedWorkspaceAccountAccessDeleteManyArgs>(
    args?: Prisma.SelectSubset<
      T,
      SharedWorkspaceAccountAccessDeleteManyArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more SharedWorkspaceAccountAccesses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SharedWorkspaceAccountAccessUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SharedWorkspaceAccountAccesses
   * const sharedWorkspaceAccountAccess = await prisma.sharedWorkspaceAccountAccess.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends SharedWorkspaceAccountAccessUpdateManyArgs>(
    args: Prisma.SelectSubset<
      T,
      SharedWorkspaceAccountAccessUpdateManyArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more SharedWorkspaceAccountAccesses and returns the data updated in the database.
   * @param {SharedWorkspaceAccountAccessUpdateManyAndReturnArgs} args - Arguments to update many SharedWorkspaceAccountAccesses.
   * @example
   * // Update many SharedWorkspaceAccountAccesses
   * const sharedWorkspaceAccountAccess = await prisma.sharedWorkspaceAccountAccess.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more SharedWorkspaceAccountAccesses and only return the `id`
   * const sharedWorkspaceAccountAccessWithIdOnly = await prisma.sharedWorkspaceAccountAccess.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<
    T extends SharedWorkspaceAccountAccessUpdateManyAndReturnArgs,
  >(
    args: Prisma.SelectSubset<
      T,
      SharedWorkspaceAccountAccessUpdateManyAndReturnArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$SharedWorkspaceAccountAccessPayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one SharedWorkspaceAccountAccess.
   * @param {SharedWorkspaceAccountAccessUpsertArgs} args - Arguments to update or create a SharedWorkspaceAccountAccess.
   * @example
   * // Update or create a SharedWorkspaceAccountAccess
   * const sharedWorkspaceAccountAccess = await prisma.sharedWorkspaceAccountAccess.upsert({
   *   create: {
   *     // ... data to create a SharedWorkspaceAccountAccess
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SharedWorkspaceAccountAccess we want to update
   *   }
   * })
   */
  upsert<T extends SharedWorkspaceAccountAccessUpsertArgs>(
    args: Prisma.SelectSubset<
      T,
      SharedWorkspaceAccountAccessUpsertArgs<ExtArgs>
    >
  ): Prisma.Prisma__SharedWorkspaceAccountAccessClient<
    runtime.Types.Result.GetResult<
      Prisma.$SharedWorkspaceAccountAccessPayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of SharedWorkspaceAccountAccesses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SharedWorkspaceAccountAccessCountArgs} args - Arguments to filter SharedWorkspaceAccountAccesses to count.
   * @example
   * // Count the number of SharedWorkspaceAccountAccesses
   * const count = await prisma.sharedWorkspaceAccountAccess.count({
   *   where: {
   *     // ... the filter for the SharedWorkspaceAccountAccesses we want to count
   *   }
   * })
   **/
  count<T extends SharedWorkspaceAccountAccessCountArgs>(
    args?: Prisma.Subset<T, SharedWorkspaceAccountAccessCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<
            T["select"],
            SharedWorkspaceAccountAccessCountAggregateOutputType
          >
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a SharedWorkspaceAccountAccess.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SharedWorkspaceAccountAccessAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends SharedWorkspaceAccountAccessAggregateArgs>(
    args: Prisma.Subset<T, SharedWorkspaceAccountAccessAggregateArgs>
  ): Prisma.PrismaPromise<GetSharedWorkspaceAccountAccessAggregateType<T>>;

  /**
   * Group by SharedWorkspaceAccountAccess.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SharedWorkspaceAccountAccessGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends SharedWorkspaceAccountAccessGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SharedWorkspaceAccountAccessGroupByArgs["orderBy"] }
      : { orderBy?: SharedWorkspaceAccountAccessGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    "Field ",
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ];
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<
      T,
      SharedWorkspaceAccountAccessGroupByArgs,
      OrderByArg
    > &
      InputErrors
  ): {} extends InputErrors
    ? GetSharedWorkspaceAccountAccessGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the SharedWorkspaceAccountAccess model
   */
  readonly fields: SharedWorkspaceAccountAccessFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SharedWorkspaceAccountAccess.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SharedWorkspaceAccountAccessClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise";
  workspaceAccount<T extends Prisma.WorkspaceAccountDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.WorkspaceAccountDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__WorkspaceAccountClient<
    | runtime.Types.Result.GetResult<
        Prisma.$WorkspaceAccountPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__UserClient<
    | runtime.Types.Result.GetResult<
        Prisma.$UserPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  assigner<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__UserClient<
    | runtime.Types.Result.GetResult<
        Prisma.$UserPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the SharedWorkspaceAccountAccess model
 */
export interface SharedWorkspaceAccountAccessFieldRefs {
  readonly id: Prisma.FieldRef<"SharedWorkspaceAccountAccess", "String">;
  readonly workspaceAccountId: Prisma.FieldRef<
    "SharedWorkspaceAccountAccess",
    "String"
  >;
  readonly userId: Prisma.FieldRef<"SharedWorkspaceAccountAccess", "String">;
  readonly assignerId: Prisma.FieldRef<
    "SharedWorkspaceAccountAccess",
    "String"
  >;
  readonly metadata: Prisma.FieldRef<"SharedWorkspaceAccountAccess", "Json">;
  readonly role: Prisma.FieldRef<
    "SharedWorkspaceAccountAccess",
    "WORKSPACE_ACCOUNT_ACCESS_ROLE"
  >;
  readonly status: Prisma.FieldRef<
    "SharedWorkspaceAccountAccess",
    "WORKSPACE_ACCOUNT_ACCESS_STATUS"
  >;
  readonly createdAt: Prisma.FieldRef<
    "SharedWorkspaceAccountAccess",
    "DateTime"
  >;
  readonly updatedAt: Prisma.FieldRef<
    "SharedWorkspaceAccountAccess",
    "DateTime"
  >;
}

// Custom InputTypes
/**
 * SharedWorkspaceAccountAccess findUnique
 */
export type SharedWorkspaceAccountAccessFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SharedWorkspaceAccountAccess
   */
  select?: Prisma.SharedWorkspaceAccountAccessSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the SharedWorkspaceAccountAccess
   */
  omit?: Prisma.SharedWorkspaceAccountAccessOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SharedWorkspaceAccountAccessInclude<ExtArgs> | null;
  /**
   * Filter, which SharedWorkspaceAccountAccess to fetch.
   */
  where: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
};

/**
 * SharedWorkspaceAccountAccess findUniqueOrThrow
 */
export type SharedWorkspaceAccountAccessFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SharedWorkspaceAccountAccess
   */
  select?: Prisma.SharedWorkspaceAccountAccessSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the SharedWorkspaceAccountAccess
   */
  omit?: Prisma.SharedWorkspaceAccountAccessOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SharedWorkspaceAccountAccessInclude<ExtArgs> | null;
  /**
   * Filter, which SharedWorkspaceAccountAccess to fetch.
   */
  where: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
};

/**
 * SharedWorkspaceAccountAccess findFirst
 */
export type SharedWorkspaceAccountAccessFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SharedWorkspaceAccountAccess
   */
  select?: Prisma.SharedWorkspaceAccountAccessSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the SharedWorkspaceAccountAccess
   */
  omit?: Prisma.SharedWorkspaceAccountAccessOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SharedWorkspaceAccountAccessInclude<ExtArgs> | null;
  /**
   * Filter, which SharedWorkspaceAccountAccess to fetch.
   */
  where?: Prisma.SharedWorkspaceAccountAccessWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of SharedWorkspaceAccountAccesses to fetch.
   */
  orderBy?:
    | Prisma.SharedWorkspaceAccountAccessOrderByWithRelationInput
    | Prisma.SharedWorkspaceAccountAccessOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for SharedWorkspaceAccountAccesses.
   */
  cursor?: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` SharedWorkspaceAccountAccesses from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` SharedWorkspaceAccountAccesses.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of SharedWorkspaceAccountAccesses.
   */
  distinct?:
    | Prisma.SharedWorkspaceAccountAccessScalarFieldEnum
    | Prisma.SharedWorkspaceAccountAccessScalarFieldEnum[];
};

/**
 * SharedWorkspaceAccountAccess findFirstOrThrow
 */
export type SharedWorkspaceAccountAccessFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SharedWorkspaceAccountAccess
   */
  select?: Prisma.SharedWorkspaceAccountAccessSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the SharedWorkspaceAccountAccess
   */
  omit?: Prisma.SharedWorkspaceAccountAccessOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SharedWorkspaceAccountAccessInclude<ExtArgs> | null;
  /**
   * Filter, which SharedWorkspaceAccountAccess to fetch.
   */
  where?: Prisma.SharedWorkspaceAccountAccessWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of SharedWorkspaceAccountAccesses to fetch.
   */
  orderBy?:
    | Prisma.SharedWorkspaceAccountAccessOrderByWithRelationInput
    | Prisma.SharedWorkspaceAccountAccessOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for SharedWorkspaceAccountAccesses.
   */
  cursor?: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` SharedWorkspaceAccountAccesses from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` SharedWorkspaceAccountAccesses.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of SharedWorkspaceAccountAccesses.
   */
  distinct?:
    | Prisma.SharedWorkspaceAccountAccessScalarFieldEnum
    | Prisma.SharedWorkspaceAccountAccessScalarFieldEnum[];
};

/**
 * SharedWorkspaceAccountAccess findMany
 */
export type SharedWorkspaceAccountAccessFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SharedWorkspaceAccountAccess
   */
  select?: Prisma.SharedWorkspaceAccountAccessSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the SharedWorkspaceAccountAccess
   */
  omit?: Prisma.SharedWorkspaceAccountAccessOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SharedWorkspaceAccountAccessInclude<ExtArgs> | null;
  /**
   * Filter, which SharedWorkspaceAccountAccesses to fetch.
   */
  where?: Prisma.SharedWorkspaceAccountAccessWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of SharedWorkspaceAccountAccesses to fetch.
   */
  orderBy?:
    | Prisma.SharedWorkspaceAccountAccessOrderByWithRelationInput
    | Prisma.SharedWorkspaceAccountAccessOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing SharedWorkspaceAccountAccesses.
   */
  cursor?: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` SharedWorkspaceAccountAccesses from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` SharedWorkspaceAccountAccesses.
   */
  skip?: number;
  distinct?:
    | Prisma.SharedWorkspaceAccountAccessScalarFieldEnum
    | Prisma.SharedWorkspaceAccountAccessScalarFieldEnum[];
};

/**
 * SharedWorkspaceAccountAccess create
 */
export type SharedWorkspaceAccountAccessCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SharedWorkspaceAccountAccess
   */
  select?: Prisma.SharedWorkspaceAccountAccessSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the SharedWorkspaceAccountAccess
   */
  omit?: Prisma.SharedWorkspaceAccountAccessOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SharedWorkspaceAccountAccessInclude<ExtArgs> | null;
  /**
   * The data needed to create a SharedWorkspaceAccountAccess.
   */
  data: Prisma.XOR<
    Prisma.SharedWorkspaceAccountAccessCreateInput,
    Prisma.SharedWorkspaceAccountAccessUncheckedCreateInput
  >;
};

/**
 * SharedWorkspaceAccountAccess createMany
 */
export type SharedWorkspaceAccountAccessCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many SharedWorkspaceAccountAccesses.
   */
  data:
    | Prisma.SharedWorkspaceAccountAccessCreateManyInput
    | Prisma.SharedWorkspaceAccountAccessCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * SharedWorkspaceAccountAccess createManyAndReturn
 */
export type SharedWorkspaceAccountAccessCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SharedWorkspaceAccountAccess
   */
  select?: Prisma.SharedWorkspaceAccountAccessSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the SharedWorkspaceAccountAccess
   */
  omit?: Prisma.SharedWorkspaceAccountAccessOmit<ExtArgs> | null;
  /**
   * The data used to create many SharedWorkspaceAccountAccesses.
   */
  data:
    | Prisma.SharedWorkspaceAccountAccessCreateManyInput
    | Prisma.SharedWorkspaceAccountAccessCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SharedWorkspaceAccountAccessIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * SharedWorkspaceAccountAccess update
 */
export type SharedWorkspaceAccountAccessUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SharedWorkspaceAccountAccess
   */
  select?: Prisma.SharedWorkspaceAccountAccessSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the SharedWorkspaceAccountAccess
   */
  omit?: Prisma.SharedWorkspaceAccountAccessOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SharedWorkspaceAccountAccessInclude<ExtArgs> | null;
  /**
   * The data needed to update a SharedWorkspaceAccountAccess.
   */
  data: Prisma.XOR<
    Prisma.SharedWorkspaceAccountAccessUpdateInput,
    Prisma.SharedWorkspaceAccountAccessUncheckedUpdateInput
  >;
  /**
   * Choose, which SharedWorkspaceAccountAccess to update.
   */
  where: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
};

/**
 * SharedWorkspaceAccountAccess updateMany
 */
export type SharedWorkspaceAccountAccessUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update SharedWorkspaceAccountAccesses.
   */
  data: Prisma.XOR<
    Prisma.SharedWorkspaceAccountAccessUpdateManyMutationInput,
    Prisma.SharedWorkspaceAccountAccessUncheckedUpdateManyInput
  >;
  /**
   * Filter which SharedWorkspaceAccountAccesses to update
   */
  where?: Prisma.SharedWorkspaceAccountAccessWhereInput;
  /**
   * Limit how many SharedWorkspaceAccountAccesses to update.
   */
  limit?: number;
};

/**
 * SharedWorkspaceAccountAccess updateManyAndReturn
 */
export type SharedWorkspaceAccountAccessUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SharedWorkspaceAccountAccess
   */
  select?: Prisma.SharedWorkspaceAccountAccessSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the SharedWorkspaceAccountAccess
   */
  omit?: Prisma.SharedWorkspaceAccountAccessOmit<ExtArgs> | null;
  /**
   * The data used to update SharedWorkspaceAccountAccesses.
   */
  data: Prisma.XOR<
    Prisma.SharedWorkspaceAccountAccessUpdateManyMutationInput,
    Prisma.SharedWorkspaceAccountAccessUncheckedUpdateManyInput
  >;
  /**
   * Filter which SharedWorkspaceAccountAccesses to update
   */
  where?: Prisma.SharedWorkspaceAccountAccessWhereInput;
  /**
   * Limit how many SharedWorkspaceAccountAccesses to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SharedWorkspaceAccountAccessIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * SharedWorkspaceAccountAccess upsert
 */
export type SharedWorkspaceAccountAccessUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SharedWorkspaceAccountAccess
   */
  select?: Prisma.SharedWorkspaceAccountAccessSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the SharedWorkspaceAccountAccess
   */
  omit?: Prisma.SharedWorkspaceAccountAccessOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SharedWorkspaceAccountAccessInclude<ExtArgs> | null;
  /**
   * The filter to search for the SharedWorkspaceAccountAccess to update in case it exists.
   */
  where: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
  /**
   * In case the SharedWorkspaceAccountAccess found by the `where` argument doesn't exist, create a new SharedWorkspaceAccountAccess with this data.
   */
  create: Prisma.XOR<
    Prisma.SharedWorkspaceAccountAccessCreateInput,
    Prisma.SharedWorkspaceAccountAccessUncheckedCreateInput
  >;
  /**
   * In case the SharedWorkspaceAccountAccess was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.SharedWorkspaceAccountAccessUpdateInput,
    Prisma.SharedWorkspaceAccountAccessUncheckedUpdateInput
  >;
};

/**
 * SharedWorkspaceAccountAccess delete
 */
export type SharedWorkspaceAccountAccessDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SharedWorkspaceAccountAccess
   */
  select?: Prisma.SharedWorkspaceAccountAccessSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the SharedWorkspaceAccountAccess
   */
  omit?: Prisma.SharedWorkspaceAccountAccessOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SharedWorkspaceAccountAccessInclude<ExtArgs> | null;
  /**
   * Filter which SharedWorkspaceAccountAccess to delete.
   */
  where: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
};

/**
 * SharedWorkspaceAccountAccess deleteMany
 */
export type SharedWorkspaceAccountAccessDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which SharedWorkspaceAccountAccesses to delete
   */
  where?: Prisma.SharedWorkspaceAccountAccessWhereInput;
  /**
   * Limit how many SharedWorkspaceAccountAccesses to delete.
   */
  limit?: number;
};

/**
 * SharedWorkspaceAccountAccess without action
 */
export type SharedWorkspaceAccountAccessDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SharedWorkspaceAccountAccess
   */
  select?: Prisma.SharedWorkspaceAccountAccessSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the SharedWorkspaceAccountAccess
   */
  omit?: Prisma.SharedWorkspaceAccountAccessOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SharedWorkspaceAccountAccessInclude<ExtArgs> | null;
};
