/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `Video` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums";
import type * as Prisma from "../internal/prismaNamespace";

/**
 * Model Video
 *
 */
export type VideoModel =
  runtime.Types.Result.DefaultSelection<Prisma.$VideoPayload>;

export type AggregateVideo = {
  _count: VideoCountAggregateOutputType | null;
  _min: VideoMinAggregateOutputType | null;
  _max: VideoMaxAggregateOutputType | null;
};

export type VideoMinAggregateOutputType = {
  id: string | null;
  workspaceAccountId: string | null;
  status: $Enums.VIDEO_STATUS | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type VideoMaxAggregateOutputType = {
  id: string | null;
  workspaceAccountId: string | null;
  status: $Enums.VIDEO_STATUS | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type VideoCountAggregateOutputType = {
  id: number;
  workspaceAccountId: number;
  metadata: number;
  status: number;
  createdAt: number;
  updatedAt: number;
  _all: number;
};

export type VideoMinAggregateInputType = {
  id?: true;
  workspaceAccountId?: true;
  status?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type VideoMaxAggregateInputType = {
  id?: true;
  workspaceAccountId?: true;
  status?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type VideoCountAggregateInputType = {
  id?: true;
  workspaceAccountId?: true;
  metadata?: true;
  status?: true;
  createdAt?: true;
  updatedAt?: true;
  _all?: true;
};

export type VideoAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which Video to aggregate.
   */
  where?: Prisma.VideoWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Videos to fetch.
   */
  orderBy?:
    | Prisma.VideoOrderByWithRelationInput
    | Prisma.VideoOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.VideoWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Videos from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Videos.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned Videos
   **/
  _count?: true | VideoCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: VideoMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: VideoMaxAggregateInputType;
};

export type GetVideoAggregateType<T extends VideoAggregateArgs> = {
  [P in keyof T & keyof AggregateVideo]: P extends "_count" | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVideo[P]>
    : Prisma.GetScalarType<T[P], AggregateVideo[P]>;
};

export type VideoGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.VideoWhereInput;
  orderBy?:
    | Prisma.VideoOrderByWithAggregationInput
    | Prisma.VideoOrderByWithAggregationInput[];
  by: Prisma.VideoScalarFieldEnum[] | Prisma.VideoScalarFieldEnum;
  having?: Prisma.VideoScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: VideoCountAggregateInputType | true;
  _min?: VideoMinAggregateInputType;
  _max?: VideoMaxAggregateInputType;
};

export type VideoGroupByOutputType = {
  id: string;
  workspaceAccountId: string;
  metadata: runtime.JsonValue | null;
  status: $Enums.VIDEO_STATUS;
  createdAt: Date;
  updatedAt: Date;
  _count: VideoCountAggregateOutputType | null;
  _min: VideoMinAggregateOutputType | null;
  _max: VideoMaxAggregateOutputType | null;
};

type GetVideoGroupByPayload<T extends VideoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VideoGroupByOutputType, T["by"]> & {
      [P in keyof T & keyof VideoGroupByOutputType]: P extends "_count"
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], VideoGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], VideoGroupByOutputType[P]>;
    }
  >
>;

export type VideoWhereInput = {
  AND?: Prisma.VideoWhereInput | Prisma.VideoWhereInput[];
  OR?: Prisma.VideoWhereInput[];
  NOT?: Prisma.VideoWhereInput | Prisma.VideoWhereInput[];
  id?: Prisma.StringFilter<"Video"> | string;
  workspaceAccountId?: Prisma.StringFilter<"Video"> | string;
  metadata?: Prisma.JsonNullableFilter<"Video">;
  status?: Prisma.EnumVIDEO_STATUSFilter<"Video"> | $Enums.VIDEO_STATUS;
  createdAt?: Prisma.DateTimeFilter<"Video"> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<"Video"> | Date | string;
  workspaceAccount?: Prisma.XOR<
    Prisma.WorkspaceAccountScalarRelationFilter,
    Prisma.WorkspaceAccountWhereInput
  >;
  sharedWorkspaceAccountAccesses?: Prisma.SharedWorkspaceAccountAccessListRelationFilter;
  label?: Prisma.LabelListRelationFilter;
};

export type VideoOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  workspaceAccountId?: Prisma.SortOrder;
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  workspaceAccount?: Prisma.WorkspaceAccountOrderByWithRelationInput;
  sharedWorkspaceAccountAccesses?: Prisma.SharedWorkspaceAccountAccessOrderByRelationAggregateInput;
  label?: Prisma.LabelOrderByRelationAggregateInput;
};

export type VideoWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    AND?: Prisma.VideoWhereInput | Prisma.VideoWhereInput[];
    OR?: Prisma.VideoWhereInput[];
    NOT?: Prisma.VideoWhereInput | Prisma.VideoWhereInput[];
    workspaceAccountId?: Prisma.StringFilter<"Video"> | string;
    metadata?: Prisma.JsonNullableFilter<"Video">;
    status?: Prisma.EnumVIDEO_STATUSFilter<"Video"> | $Enums.VIDEO_STATUS;
    createdAt?: Prisma.DateTimeFilter<"Video"> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<"Video"> | Date | string;
    workspaceAccount?: Prisma.XOR<
      Prisma.WorkspaceAccountScalarRelationFilter,
      Prisma.WorkspaceAccountWhereInput
    >;
    sharedWorkspaceAccountAccesses?: Prisma.SharedWorkspaceAccountAccessListRelationFilter;
    label?: Prisma.LabelListRelationFilter;
  },
  "id"
>;

export type VideoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  workspaceAccountId?: Prisma.SortOrder;
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  _count?: Prisma.VideoCountOrderByAggregateInput;
  _max?: Prisma.VideoMaxOrderByAggregateInput;
  _min?: Prisma.VideoMinOrderByAggregateInput;
};

export type VideoScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.VideoScalarWhereWithAggregatesInput
    | Prisma.VideoScalarWhereWithAggregatesInput[];
  OR?: Prisma.VideoScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.VideoScalarWhereWithAggregatesInput
    | Prisma.VideoScalarWhereWithAggregatesInput[];
  id?: Prisma.StringWithAggregatesFilter<"Video"> | string;
  workspaceAccountId?: Prisma.StringWithAggregatesFilter<"Video"> | string;
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"Video">;
  status?:
    | Prisma.EnumVIDEO_STATUSWithAggregatesFilter<"Video">
    | $Enums.VIDEO_STATUS;
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Video"> | Date | string;
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Video"> | Date | string;
};

export type VideoCreateInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.VIDEO_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  workspaceAccount: Prisma.WorkspaceAccountCreateNestedOneWithoutVideosInput;
  sharedWorkspaceAccountAccesses?: Prisma.SharedWorkspaceAccountAccessCreateNestedManyWithoutVideosInput;
  label?: Prisma.LabelCreateNestedManyWithoutVideosInput;
};

export type VideoUncheckedCreateInput = {
  id?: string;
  workspaceAccountId: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.VIDEO_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  sharedWorkspaceAccountAccesses?: Prisma.SharedWorkspaceAccountAccessUncheckedCreateNestedManyWithoutVideosInput;
  label?: Prisma.LabelUncheckedCreateNestedManyWithoutVideosInput;
};

export type VideoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumVIDEO_STATUSFieldUpdateOperationsInput
    | $Enums.VIDEO_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  workspaceAccount?: Prisma.WorkspaceAccountUpdateOneRequiredWithoutVideosNestedInput;
  sharedWorkspaceAccountAccesses?: Prisma.SharedWorkspaceAccountAccessUpdateManyWithoutVideosNestedInput;
  label?: Prisma.LabelUpdateManyWithoutVideosNestedInput;
};

export type VideoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumVIDEO_STATUSFieldUpdateOperationsInput
    | $Enums.VIDEO_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  sharedWorkspaceAccountAccesses?: Prisma.SharedWorkspaceAccountAccessUncheckedUpdateManyWithoutVideosNestedInput;
  label?: Prisma.LabelUncheckedUpdateManyWithoutVideosNestedInput;
};

export type VideoCreateManyInput = {
  id?: string;
  workspaceAccountId: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.VIDEO_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type VideoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumVIDEO_STATUSFieldUpdateOperationsInput
    | $Enums.VIDEO_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type VideoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumVIDEO_STATUSFieldUpdateOperationsInput
    | $Enums.VIDEO_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type VideoListRelationFilter = {
  every?: Prisma.VideoWhereInput;
  some?: Prisma.VideoWhereInput;
  none?: Prisma.VideoWhereInput;
};

export type VideoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type VideoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  workspaceAccountId?: Prisma.SortOrder;
  metadata?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type VideoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  workspaceAccountId?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type VideoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  workspaceAccountId?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type VideoCreateNestedManyWithoutWorkspaceAccountInput = {
  create?:
    | Prisma.XOR<
        Prisma.VideoCreateWithoutWorkspaceAccountInput,
        Prisma.VideoUncheckedCreateWithoutWorkspaceAccountInput
      >
    | Prisma.VideoCreateWithoutWorkspaceAccountInput[]
    | Prisma.VideoUncheckedCreateWithoutWorkspaceAccountInput[];
  connectOrCreate?:
    | Prisma.VideoCreateOrConnectWithoutWorkspaceAccountInput
    | Prisma.VideoCreateOrConnectWithoutWorkspaceAccountInput[];
  createMany?: Prisma.VideoCreateManyWorkspaceAccountInputEnvelope;
  connect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
};

export type VideoUncheckedCreateNestedManyWithoutWorkspaceAccountInput = {
  create?:
    | Prisma.XOR<
        Prisma.VideoCreateWithoutWorkspaceAccountInput,
        Prisma.VideoUncheckedCreateWithoutWorkspaceAccountInput
      >
    | Prisma.VideoCreateWithoutWorkspaceAccountInput[]
    | Prisma.VideoUncheckedCreateWithoutWorkspaceAccountInput[];
  connectOrCreate?:
    | Prisma.VideoCreateOrConnectWithoutWorkspaceAccountInput
    | Prisma.VideoCreateOrConnectWithoutWorkspaceAccountInput[];
  createMany?: Prisma.VideoCreateManyWorkspaceAccountInputEnvelope;
  connect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
};

export type VideoUpdateManyWithoutWorkspaceAccountNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.VideoCreateWithoutWorkspaceAccountInput,
        Prisma.VideoUncheckedCreateWithoutWorkspaceAccountInput
      >
    | Prisma.VideoCreateWithoutWorkspaceAccountInput[]
    | Prisma.VideoUncheckedCreateWithoutWorkspaceAccountInput[];
  connectOrCreate?:
    | Prisma.VideoCreateOrConnectWithoutWorkspaceAccountInput
    | Prisma.VideoCreateOrConnectWithoutWorkspaceAccountInput[];
  upsert?:
    | Prisma.VideoUpsertWithWhereUniqueWithoutWorkspaceAccountInput
    | Prisma.VideoUpsertWithWhereUniqueWithoutWorkspaceAccountInput[];
  createMany?: Prisma.VideoCreateManyWorkspaceAccountInputEnvelope;
  set?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  disconnect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  delete?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  connect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  update?:
    | Prisma.VideoUpdateWithWhereUniqueWithoutWorkspaceAccountInput
    | Prisma.VideoUpdateWithWhereUniqueWithoutWorkspaceAccountInput[];
  updateMany?:
    | Prisma.VideoUpdateManyWithWhereWithoutWorkspaceAccountInput
    | Prisma.VideoUpdateManyWithWhereWithoutWorkspaceAccountInput[];
  deleteMany?: Prisma.VideoScalarWhereInput | Prisma.VideoScalarWhereInput[];
};

export type VideoUncheckedUpdateManyWithoutWorkspaceAccountNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.VideoCreateWithoutWorkspaceAccountInput,
        Prisma.VideoUncheckedCreateWithoutWorkspaceAccountInput
      >
    | Prisma.VideoCreateWithoutWorkspaceAccountInput[]
    | Prisma.VideoUncheckedCreateWithoutWorkspaceAccountInput[];
  connectOrCreate?:
    | Prisma.VideoCreateOrConnectWithoutWorkspaceAccountInput
    | Prisma.VideoCreateOrConnectWithoutWorkspaceAccountInput[];
  upsert?:
    | Prisma.VideoUpsertWithWhereUniqueWithoutWorkspaceAccountInput
    | Prisma.VideoUpsertWithWhereUniqueWithoutWorkspaceAccountInput[];
  createMany?: Prisma.VideoCreateManyWorkspaceAccountInputEnvelope;
  set?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  disconnect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  delete?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  connect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  update?:
    | Prisma.VideoUpdateWithWhereUniqueWithoutWorkspaceAccountInput
    | Prisma.VideoUpdateWithWhereUniqueWithoutWorkspaceAccountInput[];
  updateMany?:
    | Prisma.VideoUpdateManyWithWhereWithoutWorkspaceAccountInput
    | Prisma.VideoUpdateManyWithWhereWithoutWorkspaceAccountInput[];
  deleteMany?: Prisma.VideoScalarWhereInput | Prisma.VideoScalarWhereInput[];
};

export type EnumVIDEO_STATUSFieldUpdateOperationsInput = {
  set?: $Enums.VIDEO_STATUS;
};

export type VideoCreateNestedManyWithoutLabelInput = {
  create?:
    | Prisma.XOR<
        Prisma.VideoCreateWithoutLabelInput,
        Prisma.VideoUncheckedCreateWithoutLabelInput
      >
    | Prisma.VideoCreateWithoutLabelInput[]
    | Prisma.VideoUncheckedCreateWithoutLabelInput[];
  connectOrCreate?:
    | Prisma.VideoCreateOrConnectWithoutLabelInput
    | Prisma.VideoCreateOrConnectWithoutLabelInput[];
  connect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
};

export type VideoUncheckedCreateNestedManyWithoutLabelInput = {
  create?:
    | Prisma.XOR<
        Prisma.VideoCreateWithoutLabelInput,
        Prisma.VideoUncheckedCreateWithoutLabelInput
      >
    | Prisma.VideoCreateWithoutLabelInput[]
    | Prisma.VideoUncheckedCreateWithoutLabelInput[];
  connectOrCreate?:
    | Prisma.VideoCreateOrConnectWithoutLabelInput
    | Prisma.VideoCreateOrConnectWithoutLabelInput[];
  connect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
};

export type VideoUpdateManyWithoutLabelNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.VideoCreateWithoutLabelInput,
        Prisma.VideoUncheckedCreateWithoutLabelInput
      >
    | Prisma.VideoCreateWithoutLabelInput[]
    | Prisma.VideoUncheckedCreateWithoutLabelInput[];
  connectOrCreate?:
    | Prisma.VideoCreateOrConnectWithoutLabelInput
    | Prisma.VideoCreateOrConnectWithoutLabelInput[];
  upsert?:
    | Prisma.VideoUpsertWithWhereUniqueWithoutLabelInput
    | Prisma.VideoUpsertWithWhereUniqueWithoutLabelInput[];
  set?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  disconnect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  delete?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  connect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  update?:
    | Prisma.VideoUpdateWithWhereUniqueWithoutLabelInput
    | Prisma.VideoUpdateWithWhereUniqueWithoutLabelInput[];
  updateMany?:
    | Prisma.VideoUpdateManyWithWhereWithoutLabelInput
    | Prisma.VideoUpdateManyWithWhereWithoutLabelInput[];
  deleteMany?: Prisma.VideoScalarWhereInput | Prisma.VideoScalarWhereInput[];
};

export type VideoUncheckedUpdateManyWithoutLabelNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.VideoCreateWithoutLabelInput,
        Prisma.VideoUncheckedCreateWithoutLabelInput
      >
    | Prisma.VideoCreateWithoutLabelInput[]
    | Prisma.VideoUncheckedCreateWithoutLabelInput[];
  connectOrCreate?:
    | Prisma.VideoCreateOrConnectWithoutLabelInput
    | Prisma.VideoCreateOrConnectWithoutLabelInput[];
  upsert?:
    | Prisma.VideoUpsertWithWhereUniqueWithoutLabelInput
    | Prisma.VideoUpsertWithWhereUniqueWithoutLabelInput[];
  set?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  disconnect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  delete?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  connect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  update?:
    | Prisma.VideoUpdateWithWhereUniqueWithoutLabelInput
    | Prisma.VideoUpdateWithWhereUniqueWithoutLabelInput[];
  updateMany?:
    | Prisma.VideoUpdateManyWithWhereWithoutLabelInput
    | Prisma.VideoUpdateManyWithWhereWithoutLabelInput[];
  deleteMany?: Prisma.VideoScalarWhereInput | Prisma.VideoScalarWhereInput[];
};

export type VideoCreateNestedManyWithoutSharedWorkspaceAccountAccessesInput = {
  create?:
    | Prisma.XOR<
        Prisma.VideoCreateWithoutSharedWorkspaceAccountAccessesInput,
        Prisma.VideoUncheckedCreateWithoutSharedWorkspaceAccountAccessesInput
      >
    | Prisma.VideoCreateWithoutSharedWorkspaceAccountAccessesInput[]
    | Prisma.VideoUncheckedCreateWithoutSharedWorkspaceAccountAccessesInput[];
  connectOrCreate?:
    | Prisma.VideoCreateOrConnectWithoutSharedWorkspaceAccountAccessesInput
    | Prisma.VideoCreateOrConnectWithoutSharedWorkspaceAccountAccessesInput[];
  connect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
};

export type VideoUncheckedCreateNestedManyWithoutSharedWorkspaceAccountAccessesInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.VideoCreateWithoutSharedWorkspaceAccountAccessesInput,
          Prisma.VideoUncheckedCreateWithoutSharedWorkspaceAccountAccessesInput
        >
      | Prisma.VideoCreateWithoutSharedWorkspaceAccountAccessesInput[]
      | Prisma.VideoUncheckedCreateWithoutSharedWorkspaceAccountAccessesInput[];
    connectOrCreate?:
      | Prisma.VideoCreateOrConnectWithoutSharedWorkspaceAccountAccessesInput
      | Prisma.VideoCreateOrConnectWithoutSharedWorkspaceAccountAccessesInput[];
    connect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  };

export type VideoUpdateManyWithoutSharedWorkspaceAccountAccessesNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.VideoCreateWithoutSharedWorkspaceAccountAccessesInput,
        Prisma.VideoUncheckedCreateWithoutSharedWorkspaceAccountAccessesInput
      >
    | Prisma.VideoCreateWithoutSharedWorkspaceAccountAccessesInput[]
    | Prisma.VideoUncheckedCreateWithoutSharedWorkspaceAccountAccessesInput[];
  connectOrCreate?:
    | Prisma.VideoCreateOrConnectWithoutSharedWorkspaceAccountAccessesInput
    | Prisma.VideoCreateOrConnectWithoutSharedWorkspaceAccountAccessesInput[];
  upsert?:
    | Prisma.VideoUpsertWithWhereUniqueWithoutSharedWorkspaceAccountAccessesInput
    | Prisma.VideoUpsertWithWhereUniqueWithoutSharedWorkspaceAccountAccessesInput[];
  set?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  disconnect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  delete?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  connect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
  update?:
    | Prisma.VideoUpdateWithWhereUniqueWithoutSharedWorkspaceAccountAccessesInput
    | Prisma.VideoUpdateWithWhereUniqueWithoutSharedWorkspaceAccountAccessesInput[];
  updateMany?:
    | Prisma.VideoUpdateManyWithWhereWithoutSharedWorkspaceAccountAccessesInput
    | Prisma.VideoUpdateManyWithWhereWithoutSharedWorkspaceAccountAccessesInput[];
  deleteMany?: Prisma.VideoScalarWhereInput | Prisma.VideoScalarWhereInput[];
};

export type VideoUncheckedUpdateManyWithoutSharedWorkspaceAccountAccessesNestedInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.VideoCreateWithoutSharedWorkspaceAccountAccessesInput,
          Prisma.VideoUncheckedCreateWithoutSharedWorkspaceAccountAccessesInput
        >
      | Prisma.VideoCreateWithoutSharedWorkspaceAccountAccessesInput[]
      | Prisma.VideoUncheckedCreateWithoutSharedWorkspaceAccountAccessesInput[];
    connectOrCreate?:
      | Prisma.VideoCreateOrConnectWithoutSharedWorkspaceAccountAccessesInput
      | Prisma.VideoCreateOrConnectWithoutSharedWorkspaceAccountAccessesInput[];
    upsert?:
      | Prisma.VideoUpsertWithWhereUniqueWithoutSharedWorkspaceAccountAccessesInput
      | Prisma.VideoUpsertWithWhereUniqueWithoutSharedWorkspaceAccountAccessesInput[];
    set?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
    disconnect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
    delete?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
    connect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[];
    update?:
      | Prisma.VideoUpdateWithWhereUniqueWithoutSharedWorkspaceAccountAccessesInput
      | Prisma.VideoUpdateWithWhereUniqueWithoutSharedWorkspaceAccountAccessesInput[];
    updateMany?:
      | Prisma.VideoUpdateManyWithWhereWithoutSharedWorkspaceAccountAccessesInput
      | Prisma.VideoUpdateManyWithWhereWithoutSharedWorkspaceAccountAccessesInput[];
    deleteMany?: Prisma.VideoScalarWhereInput | Prisma.VideoScalarWhereInput[];
  };

export type VideoCreateWithoutWorkspaceAccountInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.VIDEO_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  sharedWorkspaceAccountAccesses?: Prisma.SharedWorkspaceAccountAccessCreateNestedManyWithoutVideosInput;
  label?: Prisma.LabelCreateNestedManyWithoutVideosInput;
};

export type VideoUncheckedCreateWithoutWorkspaceAccountInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.VIDEO_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  sharedWorkspaceAccountAccesses?: Prisma.SharedWorkspaceAccountAccessUncheckedCreateNestedManyWithoutVideosInput;
  label?: Prisma.LabelUncheckedCreateNestedManyWithoutVideosInput;
};

export type VideoCreateOrConnectWithoutWorkspaceAccountInput = {
  where: Prisma.VideoWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.VideoCreateWithoutWorkspaceAccountInput,
    Prisma.VideoUncheckedCreateWithoutWorkspaceAccountInput
  >;
};

export type VideoCreateManyWorkspaceAccountInputEnvelope = {
  data:
    | Prisma.VideoCreateManyWorkspaceAccountInput
    | Prisma.VideoCreateManyWorkspaceAccountInput[];
  skipDuplicates?: boolean;
};

export type VideoUpsertWithWhereUniqueWithoutWorkspaceAccountInput = {
  where: Prisma.VideoWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.VideoUpdateWithoutWorkspaceAccountInput,
    Prisma.VideoUncheckedUpdateWithoutWorkspaceAccountInput
  >;
  create: Prisma.XOR<
    Prisma.VideoCreateWithoutWorkspaceAccountInput,
    Prisma.VideoUncheckedCreateWithoutWorkspaceAccountInput
  >;
};

export type VideoUpdateWithWhereUniqueWithoutWorkspaceAccountInput = {
  where: Prisma.VideoWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.VideoUpdateWithoutWorkspaceAccountInput,
    Prisma.VideoUncheckedUpdateWithoutWorkspaceAccountInput
  >;
};

export type VideoUpdateManyWithWhereWithoutWorkspaceAccountInput = {
  where: Prisma.VideoScalarWhereInput;
  data: Prisma.XOR<
    Prisma.VideoUpdateManyMutationInput,
    Prisma.VideoUncheckedUpdateManyWithoutWorkspaceAccountInput
  >;
};

export type VideoScalarWhereInput = {
  AND?: Prisma.VideoScalarWhereInput | Prisma.VideoScalarWhereInput[];
  OR?: Prisma.VideoScalarWhereInput[];
  NOT?: Prisma.VideoScalarWhereInput | Prisma.VideoScalarWhereInput[];
  id?: Prisma.StringFilter<"Video"> | string;
  workspaceAccountId?: Prisma.StringFilter<"Video"> | string;
  metadata?: Prisma.JsonNullableFilter<"Video">;
  status?: Prisma.EnumVIDEO_STATUSFilter<"Video"> | $Enums.VIDEO_STATUS;
  createdAt?: Prisma.DateTimeFilter<"Video"> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<"Video"> | Date | string;
};

export type VideoCreateWithoutLabelInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.VIDEO_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  workspaceAccount: Prisma.WorkspaceAccountCreateNestedOneWithoutVideosInput;
  sharedWorkspaceAccountAccesses?: Prisma.SharedWorkspaceAccountAccessCreateNestedManyWithoutVideosInput;
};

export type VideoUncheckedCreateWithoutLabelInput = {
  id?: string;
  workspaceAccountId: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.VIDEO_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  sharedWorkspaceAccountAccesses?: Prisma.SharedWorkspaceAccountAccessUncheckedCreateNestedManyWithoutVideosInput;
};

export type VideoCreateOrConnectWithoutLabelInput = {
  where: Prisma.VideoWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.VideoCreateWithoutLabelInput,
    Prisma.VideoUncheckedCreateWithoutLabelInput
  >;
};

export type VideoUpsertWithWhereUniqueWithoutLabelInput = {
  where: Prisma.VideoWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.VideoUpdateWithoutLabelInput,
    Prisma.VideoUncheckedUpdateWithoutLabelInput
  >;
  create: Prisma.XOR<
    Prisma.VideoCreateWithoutLabelInput,
    Prisma.VideoUncheckedCreateWithoutLabelInput
  >;
};

export type VideoUpdateWithWhereUniqueWithoutLabelInput = {
  where: Prisma.VideoWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.VideoUpdateWithoutLabelInput,
    Prisma.VideoUncheckedUpdateWithoutLabelInput
  >;
};

export type VideoUpdateManyWithWhereWithoutLabelInput = {
  where: Prisma.VideoScalarWhereInput;
  data: Prisma.XOR<
    Prisma.VideoUpdateManyMutationInput,
    Prisma.VideoUncheckedUpdateManyWithoutLabelInput
  >;
};

export type VideoCreateWithoutSharedWorkspaceAccountAccessesInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.VIDEO_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  workspaceAccount: Prisma.WorkspaceAccountCreateNestedOneWithoutVideosInput;
  label?: Prisma.LabelCreateNestedManyWithoutVideosInput;
};

export type VideoUncheckedCreateWithoutSharedWorkspaceAccountAccessesInput = {
  id?: string;
  workspaceAccountId: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.VIDEO_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  label?: Prisma.LabelUncheckedCreateNestedManyWithoutVideosInput;
};

export type VideoCreateOrConnectWithoutSharedWorkspaceAccountAccessesInput = {
  where: Prisma.VideoWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.VideoCreateWithoutSharedWorkspaceAccountAccessesInput,
    Prisma.VideoUncheckedCreateWithoutSharedWorkspaceAccountAccessesInput
  >;
};

export type VideoUpsertWithWhereUniqueWithoutSharedWorkspaceAccountAccessesInput =
  {
    where: Prisma.VideoWhereUniqueInput;
    update: Prisma.XOR<
      Prisma.VideoUpdateWithoutSharedWorkspaceAccountAccessesInput,
      Prisma.VideoUncheckedUpdateWithoutSharedWorkspaceAccountAccessesInput
    >;
    create: Prisma.XOR<
      Prisma.VideoCreateWithoutSharedWorkspaceAccountAccessesInput,
      Prisma.VideoUncheckedCreateWithoutSharedWorkspaceAccountAccessesInput
    >;
  };

export type VideoUpdateWithWhereUniqueWithoutSharedWorkspaceAccountAccessesInput =
  {
    where: Prisma.VideoWhereUniqueInput;
    data: Prisma.XOR<
      Prisma.VideoUpdateWithoutSharedWorkspaceAccountAccessesInput,
      Prisma.VideoUncheckedUpdateWithoutSharedWorkspaceAccountAccessesInput
    >;
  };

export type VideoUpdateManyWithWhereWithoutSharedWorkspaceAccountAccessesInput =
  {
    where: Prisma.VideoScalarWhereInput;
    data: Prisma.XOR<
      Prisma.VideoUpdateManyMutationInput,
      Prisma.VideoUncheckedUpdateManyWithoutSharedWorkspaceAccountAccessesInput
    >;
  };

export type VideoCreateManyWorkspaceAccountInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.VIDEO_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type VideoUpdateWithoutWorkspaceAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumVIDEO_STATUSFieldUpdateOperationsInput
    | $Enums.VIDEO_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  sharedWorkspaceAccountAccesses?: Prisma.SharedWorkspaceAccountAccessUpdateManyWithoutVideosNestedInput;
  label?: Prisma.LabelUpdateManyWithoutVideosNestedInput;
};

export type VideoUncheckedUpdateWithoutWorkspaceAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumVIDEO_STATUSFieldUpdateOperationsInput
    | $Enums.VIDEO_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  sharedWorkspaceAccountAccesses?: Prisma.SharedWorkspaceAccountAccessUncheckedUpdateManyWithoutVideosNestedInput;
  label?: Prisma.LabelUncheckedUpdateManyWithoutVideosNestedInput;
};

export type VideoUncheckedUpdateManyWithoutWorkspaceAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumVIDEO_STATUSFieldUpdateOperationsInput
    | $Enums.VIDEO_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type VideoUpdateWithoutLabelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumVIDEO_STATUSFieldUpdateOperationsInput
    | $Enums.VIDEO_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  workspaceAccount?: Prisma.WorkspaceAccountUpdateOneRequiredWithoutVideosNestedInput;
  sharedWorkspaceAccountAccesses?: Prisma.SharedWorkspaceAccountAccessUpdateManyWithoutVideosNestedInput;
};

export type VideoUncheckedUpdateWithoutLabelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumVIDEO_STATUSFieldUpdateOperationsInput
    | $Enums.VIDEO_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  sharedWorkspaceAccountAccesses?: Prisma.SharedWorkspaceAccountAccessUncheckedUpdateManyWithoutVideosNestedInput;
};

export type VideoUncheckedUpdateManyWithoutLabelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumVIDEO_STATUSFieldUpdateOperationsInput
    | $Enums.VIDEO_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type VideoUpdateWithoutSharedWorkspaceAccountAccessesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumVIDEO_STATUSFieldUpdateOperationsInput
    | $Enums.VIDEO_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  workspaceAccount?: Prisma.WorkspaceAccountUpdateOneRequiredWithoutVideosNestedInput;
  label?: Prisma.LabelUpdateManyWithoutVideosNestedInput;
};

export type VideoUncheckedUpdateWithoutSharedWorkspaceAccountAccessesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumVIDEO_STATUSFieldUpdateOperationsInput
    | $Enums.VIDEO_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  label?: Prisma.LabelUncheckedUpdateManyWithoutVideosNestedInput;
};

export type VideoUncheckedUpdateManyWithoutSharedWorkspaceAccountAccessesInput =
  {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
    metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
    status?:
      | Prisma.EnumVIDEO_STATUSFieldUpdateOperationsInput
      | $Enums.VIDEO_STATUS;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  };

/**
 * Count Type VideoCountOutputType
 */

export type VideoCountOutputType = {
  sharedWorkspaceAccountAccesses: number;
  label: number;
};

export type VideoCountOutputTypeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  sharedWorkspaceAccountAccesses?:
    | boolean
    | VideoCountOutputTypeCountSharedWorkspaceAccountAccessesArgs;
  label?: boolean | VideoCountOutputTypeCountLabelArgs;
};

/**
 * VideoCountOutputType without action
 */
export type VideoCountOutputTypeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VideoCountOutputType
   */
  select?: Prisma.VideoCountOutputTypeSelect<ExtArgs> | null;
};

/**
 * VideoCountOutputType without action
 */
export type VideoCountOutputTypeCountSharedWorkspaceAccountAccessesArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.SharedWorkspaceAccountAccessWhereInput;
};

/**
 * VideoCountOutputType without action
 */
export type VideoCountOutputTypeCountLabelArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.LabelWhereInput;
};

export type VideoSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    workspaceAccountId?: boolean;
    metadata?: boolean;
    status?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
    sharedWorkspaceAccountAccesses?:
      | boolean
      | Prisma.Video$sharedWorkspaceAccountAccessesArgs<ExtArgs>;
    label?: boolean | Prisma.Video$labelArgs<ExtArgs>;
    _count?: boolean | Prisma.VideoCountOutputTypeDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["video"]
>;

export type VideoSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    workspaceAccountId?: boolean;
    metadata?: boolean;
    status?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["video"]
>;

export type VideoSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    workspaceAccountId?: boolean;
    metadata?: boolean;
    status?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["video"]
>;

export type VideoSelectScalar = {
  id?: boolean;
  workspaceAccountId?: boolean;
  metadata?: boolean;
  status?: boolean;
  createdAt?: boolean;
  updatedAt?: boolean;
};

export type VideoOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | "id"
  | "workspaceAccountId"
  | "metadata"
  | "status"
  | "createdAt"
  | "updatedAt",
  ExtArgs["result"]["video"]
>;
export type VideoInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
  sharedWorkspaceAccountAccesses?:
    | boolean
    | Prisma.Video$sharedWorkspaceAccountAccessesArgs<ExtArgs>;
  label?: boolean | Prisma.Video$labelArgs<ExtArgs>;
  _count?: boolean | Prisma.VideoCountOutputTypeDefaultArgs<ExtArgs>;
};
export type VideoIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
};
export type VideoIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
};

export type $VideoPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: "Video";
  objects: {
    workspaceAccount: Prisma.$WorkspaceAccountPayload<ExtArgs>;
    sharedWorkspaceAccountAccesses: Prisma.$SharedWorkspaceAccountAccessPayload<ExtArgs>[];
    label: Prisma.$LabelPayload<ExtArgs>[];
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      workspaceAccountId: string;
      metadata: runtime.JsonValue | null;
      status: $Enums.VIDEO_STATUS;
      createdAt: Date;
      updatedAt: Date;
    },
    ExtArgs["result"]["video"]
  >;
  composites: {};
};

export type VideoGetPayload<
  S extends boolean | null | undefined | VideoDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$VideoPayload, S>;

export type VideoCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<VideoFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
  select?: VideoCountAggregateInputType | true;
};

export interface VideoDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["Video"];
    meta: { name: "Video" };
  };
  /**
   * Find zero or one Video that matches the filter.
   * @param {VideoFindUniqueArgs} args - Arguments to find a Video
   * @example
   * // Get one Video
   * const video = await prisma.video.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VideoFindUniqueArgs>(
    args: Prisma.SelectSubset<T, VideoFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__VideoClient<
    runtime.Types.Result.GetResult<
      Prisma.$VideoPayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one Video that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VideoFindUniqueOrThrowArgs} args - Arguments to find a Video
   * @example
   * // Get one Video
   * const video = await prisma.video.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VideoFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, VideoFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__VideoClient<
    runtime.Types.Result.GetResult<
      Prisma.$VideoPayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first Video that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoFindFirstArgs} args - Arguments to find a Video
   * @example
   * // Get one Video
   * const video = await prisma.video.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VideoFindFirstArgs>(
    args?: Prisma.SelectSubset<T, VideoFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__VideoClient<
    runtime.Types.Result.GetResult<
      Prisma.$VideoPayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first Video that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoFindFirstOrThrowArgs} args - Arguments to find a Video
   * @example
   * // Get one Video
   * const video = await prisma.video.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VideoFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, VideoFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__VideoClient<
    runtime.Types.Result.GetResult<
      Prisma.$VideoPayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more Videos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Videos
   * const videos = await prisma.video.findMany()
   *
   * // Get first 10 Videos
   * const videos = await prisma.video.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const videoWithIdOnly = await prisma.video.findMany({ select: { id: true } })
   *
   */
  findMany<T extends VideoFindManyArgs>(
    args?: Prisma.SelectSubset<T, VideoFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$VideoPayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >;

  /**
   * Create a Video.
   * @param {VideoCreateArgs} args - Arguments to create a Video.
   * @example
   * // Create one Video
   * const Video = await prisma.video.create({
   *   data: {
   *     // ... data to create a Video
   *   }
   * })
   *
   */
  create<T extends VideoCreateArgs>(
    args: Prisma.SelectSubset<T, VideoCreateArgs<ExtArgs>>
  ): Prisma.Prisma__VideoClient<
    runtime.Types.Result.GetResult<
      Prisma.$VideoPayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many Videos.
   * @param {VideoCreateManyArgs} args - Arguments to create many Videos.
   * @example
   * // Create many Videos
   * const video = await prisma.video.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends VideoCreateManyArgs>(
    args?: Prisma.SelectSubset<T, VideoCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many Videos and returns the data saved in the database.
   * @param {VideoCreateManyAndReturnArgs} args - Arguments to create many Videos.
   * @example
   * // Create many Videos
   * const video = await prisma.video.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many Videos and only return the `id`
   * const videoWithIdOnly = await prisma.video.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends VideoCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, VideoCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$VideoPayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a Video.
   * @param {VideoDeleteArgs} args - Arguments to delete one Video.
   * @example
   * // Delete one Video
   * const Video = await prisma.video.delete({
   *   where: {
   *     // ... filter to delete one Video
   *   }
   * })
   *
   */
  delete<T extends VideoDeleteArgs>(
    args: Prisma.SelectSubset<T, VideoDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__VideoClient<
    runtime.Types.Result.GetResult<
      Prisma.$VideoPayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one Video.
   * @param {VideoUpdateArgs} args - Arguments to update one Video.
   * @example
   * // Update one Video
   * const video = await prisma.video.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends VideoUpdateArgs>(
    args: Prisma.SelectSubset<T, VideoUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__VideoClient<
    runtime.Types.Result.GetResult<
      Prisma.$VideoPayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more Videos.
   * @param {VideoDeleteManyArgs} args - Arguments to filter Videos to delete.
   * @example
   * // Delete a few Videos
   * const { count } = await prisma.video.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends VideoDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, VideoDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more Videos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Videos
   * const video = await prisma.video.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends VideoUpdateManyArgs>(
    args: Prisma.SelectSubset<T, VideoUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more Videos and returns the data updated in the database.
   * @param {VideoUpdateManyAndReturnArgs} args - Arguments to update many Videos.
   * @example
   * // Update many Videos
   * const video = await prisma.video.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more Videos and only return the `id`
   * const videoWithIdOnly = await prisma.video.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends VideoUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, VideoUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$VideoPayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one Video.
   * @param {VideoUpsertArgs} args - Arguments to update or create a Video.
   * @example
   * // Update or create a Video
   * const video = await prisma.video.upsert({
   *   create: {
   *     // ... data to create a Video
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Video we want to update
   *   }
   * })
   */
  upsert<T extends VideoUpsertArgs>(
    args: Prisma.SelectSubset<T, VideoUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__VideoClient<
    runtime.Types.Result.GetResult<
      Prisma.$VideoPayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of Videos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoCountArgs} args - Arguments to filter Videos to count.
   * @example
   * // Count the number of Videos
   * const count = await prisma.video.count({
   *   where: {
   *     // ... the filter for the Videos we want to count
   *   }
   * })
   **/
  count<T extends VideoCountArgs>(
    args?: Prisma.Subset<T, VideoCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<T["select"], VideoCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a Video.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends VideoAggregateArgs>(
    args: Prisma.Subset<T, VideoAggregateArgs>
  ): Prisma.PrismaPromise<GetVideoAggregateType<T>>;

  /**
   * Group by Video.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends VideoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VideoGroupByArgs["orderBy"] }
      : { orderBy?: VideoGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    "Field ",
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ];
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, VideoGroupByArgs, OrderByArg> &
      InputErrors
  ): {} extends InputErrors
    ? GetVideoGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the Video model
   */
  readonly fields: VideoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Video.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VideoClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise";
  workspaceAccount<T extends Prisma.WorkspaceAccountDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.WorkspaceAccountDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__WorkspaceAccountClient<
    | runtime.Types.Result.GetResult<
        Prisma.$WorkspaceAccountPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  sharedWorkspaceAccountAccesses<
    T extends Prisma.Video$sharedWorkspaceAccountAccessesArgs<ExtArgs> = {},
  >(
    args?: Prisma.Subset<
      T,
      Prisma.Video$sharedWorkspaceAccountAccessesArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$SharedWorkspaceAccountAccessPayload<ExtArgs>,
        T,
        "findMany",
        GlobalOmitOptions
      >
    | Null
  >;
  label<T extends Prisma.Video$labelArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.Video$labelArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$LabelPayload<ExtArgs>,
        T,
        "findMany",
        GlobalOmitOptions
      >
    | Null
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the Video model
 */
export interface VideoFieldRefs {
  readonly id: Prisma.FieldRef<"Video", "String">;
  readonly workspaceAccountId: Prisma.FieldRef<"Video", "String">;
  readonly metadata: Prisma.FieldRef<"Video", "Json">;
  readonly status: Prisma.FieldRef<"Video", "VIDEO_STATUS">;
  readonly createdAt: Prisma.FieldRef<"Video", "DateTime">;
  readonly updatedAt: Prisma.FieldRef<"Video", "DateTime">;
}

// Custom InputTypes
/**
 * Video findUnique
 */
export type VideoFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null;
  /**
   * Filter, which Video to fetch.
   */
  where: Prisma.VideoWhereUniqueInput;
};

/**
 * Video findUniqueOrThrow
 */
export type VideoFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null;
  /**
   * Filter, which Video to fetch.
   */
  where: Prisma.VideoWhereUniqueInput;
};

/**
 * Video findFirst
 */
export type VideoFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null;
  /**
   * Filter, which Video to fetch.
   */
  where?: Prisma.VideoWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Videos to fetch.
   */
  orderBy?:
    | Prisma.VideoOrderByWithRelationInput
    | Prisma.VideoOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for Videos.
   */
  cursor?: Prisma.VideoWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Videos from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Videos.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of Videos.
   */
  distinct?: Prisma.VideoScalarFieldEnum | Prisma.VideoScalarFieldEnum[];
};

/**
 * Video findFirstOrThrow
 */
export type VideoFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null;
  /**
   * Filter, which Video to fetch.
   */
  where?: Prisma.VideoWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Videos to fetch.
   */
  orderBy?:
    | Prisma.VideoOrderByWithRelationInput
    | Prisma.VideoOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for Videos.
   */
  cursor?: Prisma.VideoWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Videos from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Videos.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of Videos.
   */
  distinct?: Prisma.VideoScalarFieldEnum | Prisma.VideoScalarFieldEnum[];
};

/**
 * Video findMany
 */
export type VideoFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null;
  /**
   * Filter, which Videos to fetch.
   */
  where?: Prisma.VideoWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Videos to fetch.
   */
  orderBy?:
    | Prisma.VideoOrderByWithRelationInput
    | Prisma.VideoOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing Videos.
   */
  cursor?: Prisma.VideoWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Videos from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Videos.
   */
  skip?: number;
  distinct?: Prisma.VideoScalarFieldEnum | Prisma.VideoScalarFieldEnum[];
};

/**
 * Video create
 */
export type VideoCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null;
  /**
   * The data needed to create a Video.
   */
  data: Prisma.XOR<Prisma.VideoCreateInput, Prisma.VideoUncheckedCreateInput>;
};

/**
 * Video createMany
 */
export type VideoCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many Videos.
   */
  data: Prisma.VideoCreateManyInput | Prisma.VideoCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * Video createManyAndReturn
 */
export type VideoCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null;
  /**
   * The data used to create many Videos.
   */
  data: Prisma.VideoCreateManyInput | Prisma.VideoCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * Video update
 */
export type VideoUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null;
  /**
   * The data needed to update a Video.
   */
  data: Prisma.XOR<Prisma.VideoUpdateInput, Prisma.VideoUncheckedUpdateInput>;
  /**
   * Choose, which Video to update.
   */
  where: Prisma.VideoWhereUniqueInput;
};

/**
 * Video updateMany
 */
export type VideoUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update Videos.
   */
  data: Prisma.XOR<
    Prisma.VideoUpdateManyMutationInput,
    Prisma.VideoUncheckedUpdateManyInput
  >;
  /**
   * Filter which Videos to update
   */
  where?: Prisma.VideoWhereInput;
  /**
   * Limit how many Videos to update.
   */
  limit?: number;
};

/**
 * Video updateManyAndReturn
 */
export type VideoUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null;
  /**
   * The data used to update Videos.
   */
  data: Prisma.XOR<
    Prisma.VideoUpdateManyMutationInput,
    Prisma.VideoUncheckedUpdateManyInput
  >;
  /**
   * Filter which Videos to update
   */
  where?: Prisma.VideoWhereInput;
  /**
   * Limit how many Videos to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * Video upsert
 */
export type VideoUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null;
  /**
   * The filter to search for the Video to update in case it exists.
   */
  where: Prisma.VideoWhereUniqueInput;
  /**
   * In case the Video found by the `where` argument doesn't exist, create a new Video with this data.
   */
  create: Prisma.XOR<Prisma.VideoCreateInput, Prisma.VideoUncheckedCreateInput>;
  /**
   * In case the Video was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VideoUpdateInput, Prisma.VideoUncheckedUpdateInput>;
};

/**
 * Video delete
 */
export type VideoDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null;
  /**
   * Filter which Video to delete.
   */
  where: Prisma.VideoWhereUniqueInput;
};

/**
 * Video deleteMany
 */
export type VideoDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which Videos to delete
   */
  where?: Prisma.VideoWhereInput;
  /**
   * Limit how many Videos to delete.
   */
  limit?: number;
};

/**
 * Video.sharedWorkspaceAccountAccesses
 */
export type Video$sharedWorkspaceAccountAccessesArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SharedWorkspaceAccountAccess
   */
  select?: Prisma.SharedWorkspaceAccountAccessSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the SharedWorkspaceAccountAccess
   */
  omit?: Prisma.SharedWorkspaceAccountAccessOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SharedWorkspaceAccountAccessInclude<ExtArgs> | null;
  where?: Prisma.SharedWorkspaceAccountAccessWhereInput;
  orderBy?:
    | Prisma.SharedWorkspaceAccountAccessOrderByWithRelationInput
    | Prisma.SharedWorkspaceAccountAccessOrderByWithRelationInput[];
  cursor?: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?:
    | Prisma.SharedWorkspaceAccountAccessScalarFieldEnum
    | Prisma.SharedWorkspaceAccountAccessScalarFieldEnum[];
};

/**
 * Video.label
 */
export type Video$labelArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Label
   */
  select?: Prisma.LabelSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Label
   */
  omit?: Prisma.LabelOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LabelInclude<ExtArgs> | null;
  where?: Prisma.LabelWhereInput;
  orderBy?:
    | Prisma.LabelOrderByWithRelationInput
    | Prisma.LabelOrderByWithRelationInput[];
  cursor?: Prisma.LabelWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?: Prisma.LabelScalarFieldEnum | Prisma.LabelScalarFieldEnum[];
};

/**
 * Video without action
 */
export type VideoDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null;
};
