/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `Writer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums";
import type * as Prisma from "../internal/prismaNamespace";

/**
 * Model Writer
 *
 */
export type WriterModel =
  runtime.Types.Result.DefaultSelection<Prisma.$WriterPayload>;

export type AggregateWriter = {
  _count: WriterCountAggregateOutputType | null;
  _min: WriterMinAggregateOutputType | null;
  _max: WriterMaxAggregateOutputType | null;
};

export type WriterMinAggregateOutputType = {
  id: string | null;
  workspaceAccountId: string | null;
  status: $Enums.WRITER_STATUS | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type WriterMaxAggregateOutputType = {
  id: string | null;
  workspaceAccountId: string | null;
  status: $Enums.WRITER_STATUS | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type WriterCountAggregateOutputType = {
  id: number;
  workspaceAccountId: number;
  metadata: number;
  status: number;
  createdAt: number;
  updatedAt: number;
  _all: number;
};

export type WriterMinAggregateInputType = {
  id?: true;
  workspaceAccountId?: true;
  status?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type WriterMaxAggregateInputType = {
  id?: true;
  workspaceAccountId?: true;
  status?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type WriterCountAggregateInputType = {
  id?: true;
  workspaceAccountId?: true;
  metadata?: true;
  status?: true;
  createdAt?: true;
  updatedAt?: true;
  _all?: true;
};

export type WriterAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which Writer to aggregate.
   */
  where?: Prisma.WriterWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Writers to fetch.
   */
  orderBy?:
    | Prisma.WriterOrderByWithRelationInput
    | Prisma.WriterOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.WriterWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Writers from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Writers.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned Writers
   **/
  _count?: true | WriterCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: WriterMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: WriterMaxAggregateInputType;
};

export type GetWriterAggregateType<T extends WriterAggregateArgs> = {
  [P in keyof T & keyof AggregateWriter]: P extends "_count" | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWriter[P]>
    : Prisma.GetScalarType<T[P], AggregateWriter[P]>;
};

export type WriterGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.WriterWhereInput;
  orderBy?:
    | Prisma.WriterOrderByWithAggregationInput
    | Prisma.WriterOrderByWithAggregationInput[];
  by: Prisma.WriterScalarFieldEnum[] | Prisma.WriterScalarFieldEnum;
  having?: Prisma.WriterScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: WriterCountAggregateInputType | true;
  _min?: WriterMinAggregateInputType;
  _max?: WriterMaxAggregateInputType;
};

export type WriterGroupByOutputType = {
  id: string;
  workspaceAccountId: string;
  metadata: runtime.JsonValue | null;
  status: $Enums.WRITER_STATUS;
  createdAt: Date;
  updatedAt: Date;
  _count: WriterCountAggregateOutputType | null;
  _min: WriterMinAggregateOutputType | null;
  _max: WriterMaxAggregateOutputType | null;
};

type GetWriterGroupByPayload<T extends WriterGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<WriterGroupByOutputType, T["by"]> & {
        [P in keyof T & keyof WriterGroupByOutputType]: P extends "_count"
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WriterGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WriterGroupByOutputType[P]>;
      }
    >
  >;

export type WriterWhereInput = {
  AND?: Prisma.WriterWhereInput | Prisma.WriterWhereInput[];
  OR?: Prisma.WriterWhereInput[];
  NOT?: Prisma.WriterWhereInput | Prisma.WriterWhereInput[];
  id?: Prisma.StringFilter<"Writer"> | string;
  workspaceAccountId?: Prisma.StringFilter<"Writer"> | string;
  metadata?: Prisma.JsonNullableFilter<"Writer">;
  status?: Prisma.EnumWRITER_STATUSFilter<"Writer"> | $Enums.WRITER_STATUS;
  createdAt?: Prisma.DateTimeFilter<"Writer"> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<"Writer"> | Date | string;
  workspaceAccount?: Prisma.XOR<
    Prisma.WorkspaceAccountScalarRelationFilter,
    Prisma.WorkspaceAccountWhereInput
  >;
  sharedWorkspaceAccountAccess?: Prisma.SharedWorkspaceAccountAccessListRelationFilter;
  label?: Prisma.LabelListRelationFilter;
};

export type WriterOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  workspaceAccountId?: Prisma.SortOrder;
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  workspaceAccount?: Prisma.WorkspaceAccountOrderByWithRelationInput;
  sharedWorkspaceAccountAccess?: Prisma.SharedWorkspaceAccountAccessOrderByRelationAggregateInput;
  label?: Prisma.LabelOrderByRelationAggregateInput;
};

export type WriterWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    workspaceAccountId?: string;
    AND?: Prisma.WriterWhereInput | Prisma.WriterWhereInput[];
    OR?: Prisma.WriterWhereInput[];
    NOT?: Prisma.WriterWhereInput | Prisma.WriterWhereInput[];
    metadata?: Prisma.JsonNullableFilter<"Writer">;
    status?: Prisma.EnumWRITER_STATUSFilter<"Writer"> | $Enums.WRITER_STATUS;
    createdAt?: Prisma.DateTimeFilter<"Writer"> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<"Writer"> | Date | string;
    workspaceAccount?: Prisma.XOR<
      Prisma.WorkspaceAccountScalarRelationFilter,
      Prisma.WorkspaceAccountWhereInput
    >;
    sharedWorkspaceAccountAccess?: Prisma.SharedWorkspaceAccountAccessListRelationFilter;
    label?: Prisma.LabelListRelationFilter;
  },
  "id" | "workspaceAccountId"
>;

export type WriterOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  workspaceAccountId?: Prisma.SortOrder;
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  _count?: Prisma.WriterCountOrderByAggregateInput;
  _max?: Prisma.WriterMaxOrderByAggregateInput;
  _min?: Prisma.WriterMinOrderByAggregateInput;
};

export type WriterScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.WriterScalarWhereWithAggregatesInput
    | Prisma.WriterScalarWhereWithAggregatesInput[];
  OR?: Prisma.WriterScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.WriterScalarWhereWithAggregatesInput
    | Prisma.WriterScalarWhereWithAggregatesInput[];
  id?: Prisma.StringWithAggregatesFilter<"Writer"> | string;
  workspaceAccountId?: Prisma.StringWithAggregatesFilter<"Writer"> | string;
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"Writer">;
  status?:
    | Prisma.EnumWRITER_STATUSWithAggregatesFilter<"Writer">
    | $Enums.WRITER_STATUS;
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Writer"> | Date | string;
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Writer"> | Date | string;
};

export type WriterCreateInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.WRITER_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  workspaceAccount: Prisma.WorkspaceAccountCreateNestedOneWithoutWritersInput;
  sharedWorkspaceAccountAccess?: Prisma.SharedWorkspaceAccountAccessCreateNestedManyWithoutWritersInput;
  label?: Prisma.LabelCreateNestedManyWithoutWritersInput;
};

export type WriterUncheckedCreateInput = {
  id?: string;
  workspaceAccountId: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.WRITER_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  sharedWorkspaceAccountAccess?: Prisma.SharedWorkspaceAccountAccessUncheckedCreateNestedManyWithoutWritersInput;
  label?: Prisma.LabelUncheckedCreateNestedManyWithoutWritersInput;
};

export type WriterUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumWRITER_STATUSFieldUpdateOperationsInput
    | $Enums.WRITER_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  workspaceAccount?: Prisma.WorkspaceAccountUpdateOneRequiredWithoutWritersNestedInput;
  sharedWorkspaceAccountAccess?: Prisma.SharedWorkspaceAccountAccessUpdateManyWithoutWritersNestedInput;
  label?: Prisma.LabelUpdateManyWithoutWritersNestedInput;
};

export type WriterUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumWRITER_STATUSFieldUpdateOperationsInput
    | $Enums.WRITER_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  sharedWorkspaceAccountAccess?: Prisma.SharedWorkspaceAccountAccessUncheckedUpdateManyWithoutWritersNestedInput;
  label?: Prisma.LabelUncheckedUpdateManyWithoutWritersNestedInput;
};

export type WriterCreateManyInput = {
  id?: string;
  workspaceAccountId: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.WRITER_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type WriterUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumWRITER_STATUSFieldUpdateOperationsInput
    | $Enums.WRITER_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type WriterUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumWRITER_STATUSFieldUpdateOperationsInput
    | $Enums.WRITER_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type WriterListRelationFilter = {
  every?: Prisma.WriterWhereInput;
  some?: Prisma.WriterWhereInput;
  none?: Prisma.WriterWhereInput;
};

export type WriterOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type WriterCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  workspaceAccountId?: Prisma.SortOrder;
  metadata?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type WriterMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  workspaceAccountId?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type WriterMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  workspaceAccountId?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type WriterCreateNestedManyWithoutWorkspaceAccountInput = {
  create?:
    | Prisma.XOR<
        Prisma.WriterCreateWithoutWorkspaceAccountInput,
        Prisma.WriterUncheckedCreateWithoutWorkspaceAccountInput
      >
    | Prisma.WriterCreateWithoutWorkspaceAccountInput[]
    | Prisma.WriterUncheckedCreateWithoutWorkspaceAccountInput[];
  connectOrCreate?:
    | Prisma.WriterCreateOrConnectWithoutWorkspaceAccountInput
    | Prisma.WriterCreateOrConnectWithoutWorkspaceAccountInput[];
  createMany?: Prisma.WriterCreateManyWorkspaceAccountInputEnvelope;
  connect?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
};

export type WriterUncheckedCreateNestedManyWithoutWorkspaceAccountInput = {
  create?:
    | Prisma.XOR<
        Prisma.WriterCreateWithoutWorkspaceAccountInput,
        Prisma.WriterUncheckedCreateWithoutWorkspaceAccountInput
      >
    | Prisma.WriterCreateWithoutWorkspaceAccountInput[]
    | Prisma.WriterUncheckedCreateWithoutWorkspaceAccountInput[];
  connectOrCreate?:
    | Prisma.WriterCreateOrConnectWithoutWorkspaceAccountInput
    | Prisma.WriterCreateOrConnectWithoutWorkspaceAccountInput[];
  createMany?: Prisma.WriterCreateManyWorkspaceAccountInputEnvelope;
  connect?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
};

export type WriterUpdateManyWithoutWorkspaceAccountNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.WriterCreateWithoutWorkspaceAccountInput,
        Prisma.WriterUncheckedCreateWithoutWorkspaceAccountInput
      >
    | Prisma.WriterCreateWithoutWorkspaceAccountInput[]
    | Prisma.WriterUncheckedCreateWithoutWorkspaceAccountInput[];
  connectOrCreate?:
    | Prisma.WriterCreateOrConnectWithoutWorkspaceAccountInput
    | Prisma.WriterCreateOrConnectWithoutWorkspaceAccountInput[];
  upsert?:
    | Prisma.WriterUpsertWithWhereUniqueWithoutWorkspaceAccountInput
    | Prisma.WriterUpsertWithWhereUniqueWithoutWorkspaceAccountInput[];
  createMany?: Prisma.WriterCreateManyWorkspaceAccountInputEnvelope;
  set?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  disconnect?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  delete?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  connect?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  update?:
    | Prisma.WriterUpdateWithWhereUniqueWithoutWorkspaceAccountInput
    | Prisma.WriterUpdateWithWhereUniqueWithoutWorkspaceAccountInput[];
  updateMany?:
    | Prisma.WriterUpdateManyWithWhereWithoutWorkspaceAccountInput
    | Prisma.WriterUpdateManyWithWhereWithoutWorkspaceAccountInput[];
  deleteMany?: Prisma.WriterScalarWhereInput | Prisma.WriterScalarWhereInput[];
};

export type WriterUncheckedUpdateManyWithoutWorkspaceAccountNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.WriterCreateWithoutWorkspaceAccountInput,
        Prisma.WriterUncheckedCreateWithoutWorkspaceAccountInput
      >
    | Prisma.WriterCreateWithoutWorkspaceAccountInput[]
    | Prisma.WriterUncheckedCreateWithoutWorkspaceAccountInput[];
  connectOrCreate?:
    | Prisma.WriterCreateOrConnectWithoutWorkspaceAccountInput
    | Prisma.WriterCreateOrConnectWithoutWorkspaceAccountInput[];
  upsert?:
    | Prisma.WriterUpsertWithWhereUniqueWithoutWorkspaceAccountInput
    | Prisma.WriterUpsertWithWhereUniqueWithoutWorkspaceAccountInput[];
  createMany?: Prisma.WriterCreateManyWorkspaceAccountInputEnvelope;
  set?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  disconnect?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  delete?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  connect?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  update?:
    | Prisma.WriterUpdateWithWhereUniqueWithoutWorkspaceAccountInput
    | Prisma.WriterUpdateWithWhereUniqueWithoutWorkspaceAccountInput[];
  updateMany?:
    | Prisma.WriterUpdateManyWithWhereWithoutWorkspaceAccountInput
    | Prisma.WriterUpdateManyWithWhereWithoutWorkspaceAccountInput[];
  deleteMany?: Prisma.WriterScalarWhereInput | Prisma.WriterScalarWhereInput[];
};

export type EnumWRITER_STATUSFieldUpdateOperationsInput = {
  set?: $Enums.WRITER_STATUS;
};

export type WriterCreateNestedManyWithoutLabelInput = {
  create?:
    | Prisma.XOR<
        Prisma.WriterCreateWithoutLabelInput,
        Prisma.WriterUncheckedCreateWithoutLabelInput
      >
    | Prisma.WriterCreateWithoutLabelInput[]
    | Prisma.WriterUncheckedCreateWithoutLabelInput[];
  connectOrCreate?:
    | Prisma.WriterCreateOrConnectWithoutLabelInput
    | Prisma.WriterCreateOrConnectWithoutLabelInput[];
  connect?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
};

export type WriterUncheckedCreateNestedManyWithoutLabelInput = {
  create?:
    | Prisma.XOR<
        Prisma.WriterCreateWithoutLabelInput,
        Prisma.WriterUncheckedCreateWithoutLabelInput
      >
    | Prisma.WriterCreateWithoutLabelInput[]
    | Prisma.WriterUncheckedCreateWithoutLabelInput[];
  connectOrCreate?:
    | Prisma.WriterCreateOrConnectWithoutLabelInput
    | Prisma.WriterCreateOrConnectWithoutLabelInput[];
  connect?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
};

export type WriterUpdateManyWithoutLabelNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.WriterCreateWithoutLabelInput,
        Prisma.WriterUncheckedCreateWithoutLabelInput
      >
    | Prisma.WriterCreateWithoutLabelInput[]
    | Prisma.WriterUncheckedCreateWithoutLabelInput[];
  connectOrCreate?:
    | Prisma.WriterCreateOrConnectWithoutLabelInput
    | Prisma.WriterCreateOrConnectWithoutLabelInput[];
  upsert?:
    | Prisma.WriterUpsertWithWhereUniqueWithoutLabelInput
    | Prisma.WriterUpsertWithWhereUniqueWithoutLabelInput[];
  set?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  disconnect?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  delete?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  connect?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  update?:
    | Prisma.WriterUpdateWithWhereUniqueWithoutLabelInput
    | Prisma.WriterUpdateWithWhereUniqueWithoutLabelInput[];
  updateMany?:
    | Prisma.WriterUpdateManyWithWhereWithoutLabelInput
    | Prisma.WriterUpdateManyWithWhereWithoutLabelInput[];
  deleteMany?: Prisma.WriterScalarWhereInput | Prisma.WriterScalarWhereInput[];
};

export type WriterUncheckedUpdateManyWithoutLabelNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.WriterCreateWithoutLabelInput,
        Prisma.WriterUncheckedCreateWithoutLabelInput
      >
    | Prisma.WriterCreateWithoutLabelInput[]
    | Prisma.WriterUncheckedCreateWithoutLabelInput[];
  connectOrCreate?:
    | Prisma.WriterCreateOrConnectWithoutLabelInput
    | Prisma.WriterCreateOrConnectWithoutLabelInput[];
  upsert?:
    | Prisma.WriterUpsertWithWhereUniqueWithoutLabelInput
    | Prisma.WriterUpsertWithWhereUniqueWithoutLabelInput[];
  set?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  disconnect?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  delete?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  connect?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  update?:
    | Prisma.WriterUpdateWithWhereUniqueWithoutLabelInput
    | Prisma.WriterUpdateWithWhereUniqueWithoutLabelInput[];
  updateMany?:
    | Prisma.WriterUpdateManyWithWhereWithoutLabelInput
    | Prisma.WriterUpdateManyWithWhereWithoutLabelInput[];
  deleteMany?: Prisma.WriterScalarWhereInput | Prisma.WriterScalarWhereInput[];
};

export type WriterCreateNestedManyWithoutSharedWorkspaceAccountAccessInput = {
  create?:
    | Prisma.XOR<
        Prisma.WriterCreateWithoutSharedWorkspaceAccountAccessInput,
        Prisma.WriterUncheckedCreateWithoutSharedWorkspaceAccountAccessInput
      >
    | Prisma.WriterCreateWithoutSharedWorkspaceAccountAccessInput[]
    | Prisma.WriterUncheckedCreateWithoutSharedWorkspaceAccountAccessInput[];
  connectOrCreate?:
    | Prisma.WriterCreateOrConnectWithoutSharedWorkspaceAccountAccessInput
    | Prisma.WriterCreateOrConnectWithoutSharedWorkspaceAccountAccessInput[];
  connect?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
};

export type WriterUncheckedCreateNestedManyWithoutSharedWorkspaceAccountAccessInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.WriterCreateWithoutSharedWorkspaceAccountAccessInput,
          Prisma.WriterUncheckedCreateWithoutSharedWorkspaceAccountAccessInput
        >
      | Prisma.WriterCreateWithoutSharedWorkspaceAccountAccessInput[]
      | Prisma.WriterUncheckedCreateWithoutSharedWorkspaceAccountAccessInput[];
    connectOrCreate?:
      | Prisma.WriterCreateOrConnectWithoutSharedWorkspaceAccountAccessInput
      | Prisma.WriterCreateOrConnectWithoutSharedWorkspaceAccountAccessInput[];
    connect?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  };

export type WriterUpdateManyWithoutSharedWorkspaceAccountAccessNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.WriterCreateWithoutSharedWorkspaceAccountAccessInput,
        Prisma.WriterUncheckedCreateWithoutSharedWorkspaceAccountAccessInput
      >
    | Prisma.WriterCreateWithoutSharedWorkspaceAccountAccessInput[]
    | Prisma.WriterUncheckedCreateWithoutSharedWorkspaceAccountAccessInput[];
  connectOrCreate?:
    | Prisma.WriterCreateOrConnectWithoutSharedWorkspaceAccountAccessInput
    | Prisma.WriterCreateOrConnectWithoutSharedWorkspaceAccountAccessInput[];
  upsert?:
    | Prisma.WriterUpsertWithWhereUniqueWithoutSharedWorkspaceAccountAccessInput
    | Prisma.WriterUpsertWithWhereUniqueWithoutSharedWorkspaceAccountAccessInput[];
  set?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  disconnect?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  delete?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  connect?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
  update?:
    | Prisma.WriterUpdateWithWhereUniqueWithoutSharedWorkspaceAccountAccessInput
    | Prisma.WriterUpdateWithWhereUniqueWithoutSharedWorkspaceAccountAccessInput[];
  updateMany?:
    | Prisma.WriterUpdateManyWithWhereWithoutSharedWorkspaceAccountAccessInput
    | Prisma.WriterUpdateManyWithWhereWithoutSharedWorkspaceAccountAccessInput[];
  deleteMany?: Prisma.WriterScalarWhereInput | Prisma.WriterScalarWhereInput[];
};

export type WriterUncheckedUpdateManyWithoutSharedWorkspaceAccountAccessNestedInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.WriterCreateWithoutSharedWorkspaceAccountAccessInput,
          Prisma.WriterUncheckedCreateWithoutSharedWorkspaceAccountAccessInput
        >
      | Prisma.WriterCreateWithoutSharedWorkspaceAccountAccessInput[]
      | Prisma.WriterUncheckedCreateWithoutSharedWorkspaceAccountAccessInput[];
    connectOrCreate?:
      | Prisma.WriterCreateOrConnectWithoutSharedWorkspaceAccountAccessInput
      | Prisma.WriterCreateOrConnectWithoutSharedWorkspaceAccountAccessInput[];
    upsert?:
      | Prisma.WriterUpsertWithWhereUniqueWithoutSharedWorkspaceAccountAccessInput
      | Prisma.WriterUpsertWithWhereUniqueWithoutSharedWorkspaceAccountAccessInput[];
    set?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
    disconnect?:
      | Prisma.WriterWhereUniqueInput
      | Prisma.WriterWhereUniqueInput[];
    delete?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
    connect?: Prisma.WriterWhereUniqueInput | Prisma.WriterWhereUniqueInput[];
    update?:
      | Prisma.WriterUpdateWithWhereUniqueWithoutSharedWorkspaceAccountAccessInput
      | Prisma.WriterUpdateWithWhereUniqueWithoutSharedWorkspaceAccountAccessInput[];
    updateMany?:
      | Prisma.WriterUpdateManyWithWhereWithoutSharedWorkspaceAccountAccessInput
      | Prisma.WriterUpdateManyWithWhereWithoutSharedWorkspaceAccountAccessInput[];
    deleteMany?:
      | Prisma.WriterScalarWhereInput
      | Prisma.WriterScalarWhereInput[];
  };

export type WriterCreateWithoutWorkspaceAccountInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.WRITER_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  sharedWorkspaceAccountAccess?: Prisma.SharedWorkspaceAccountAccessCreateNestedManyWithoutWritersInput;
  label?: Prisma.LabelCreateNestedManyWithoutWritersInput;
};

export type WriterUncheckedCreateWithoutWorkspaceAccountInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.WRITER_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  sharedWorkspaceAccountAccess?: Prisma.SharedWorkspaceAccountAccessUncheckedCreateNestedManyWithoutWritersInput;
  label?: Prisma.LabelUncheckedCreateNestedManyWithoutWritersInput;
};

export type WriterCreateOrConnectWithoutWorkspaceAccountInput = {
  where: Prisma.WriterWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.WriterCreateWithoutWorkspaceAccountInput,
    Prisma.WriterUncheckedCreateWithoutWorkspaceAccountInput
  >;
};

export type WriterCreateManyWorkspaceAccountInputEnvelope = {
  data:
    | Prisma.WriterCreateManyWorkspaceAccountInput
    | Prisma.WriterCreateManyWorkspaceAccountInput[];
  skipDuplicates?: boolean;
};

export type WriterUpsertWithWhereUniqueWithoutWorkspaceAccountInput = {
  where: Prisma.WriterWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.WriterUpdateWithoutWorkspaceAccountInput,
    Prisma.WriterUncheckedUpdateWithoutWorkspaceAccountInput
  >;
  create: Prisma.XOR<
    Prisma.WriterCreateWithoutWorkspaceAccountInput,
    Prisma.WriterUncheckedCreateWithoutWorkspaceAccountInput
  >;
};

export type WriterUpdateWithWhereUniqueWithoutWorkspaceAccountInput = {
  where: Prisma.WriterWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.WriterUpdateWithoutWorkspaceAccountInput,
    Prisma.WriterUncheckedUpdateWithoutWorkspaceAccountInput
  >;
};

export type WriterUpdateManyWithWhereWithoutWorkspaceAccountInput = {
  where: Prisma.WriterScalarWhereInput;
  data: Prisma.XOR<
    Prisma.WriterUpdateManyMutationInput,
    Prisma.WriterUncheckedUpdateManyWithoutWorkspaceAccountInput
  >;
};

export type WriterScalarWhereInput = {
  AND?: Prisma.WriterScalarWhereInput | Prisma.WriterScalarWhereInput[];
  OR?: Prisma.WriterScalarWhereInput[];
  NOT?: Prisma.WriterScalarWhereInput | Prisma.WriterScalarWhereInput[];
  id?: Prisma.StringFilter<"Writer"> | string;
  workspaceAccountId?: Prisma.StringFilter<"Writer"> | string;
  metadata?: Prisma.JsonNullableFilter<"Writer">;
  status?: Prisma.EnumWRITER_STATUSFilter<"Writer"> | $Enums.WRITER_STATUS;
  createdAt?: Prisma.DateTimeFilter<"Writer"> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<"Writer"> | Date | string;
};

export type WriterCreateWithoutLabelInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.WRITER_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  workspaceAccount: Prisma.WorkspaceAccountCreateNestedOneWithoutWritersInput;
  sharedWorkspaceAccountAccess?: Prisma.SharedWorkspaceAccountAccessCreateNestedManyWithoutWritersInput;
};

export type WriterUncheckedCreateWithoutLabelInput = {
  id?: string;
  workspaceAccountId: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.WRITER_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  sharedWorkspaceAccountAccess?: Prisma.SharedWorkspaceAccountAccessUncheckedCreateNestedManyWithoutWritersInput;
};

export type WriterCreateOrConnectWithoutLabelInput = {
  where: Prisma.WriterWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.WriterCreateWithoutLabelInput,
    Prisma.WriterUncheckedCreateWithoutLabelInput
  >;
};

export type WriterUpsertWithWhereUniqueWithoutLabelInput = {
  where: Prisma.WriterWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.WriterUpdateWithoutLabelInput,
    Prisma.WriterUncheckedUpdateWithoutLabelInput
  >;
  create: Prisma.XOR<
    Prisma.WriterCreateWithoutLabelInput,
    Prisma.WriterUncheckedCreateWithoutLabelInput
  >;
};

export type WriterUpdateWithWhereUniqueWithoutLabelInput = {
  where: Prisma.WriterWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.WriterUpdateWithoutLabelInput,
    Prisma.WriterUncheckedUpdateWithoutLabelInput
  >;
};

export type WriterUpdateManyWithWhereWithoutLabelInput = {
  where: Prisma.WriterScalarWhereInput;
  data: Prisma.XOR<
    Prisma.WriterUpdateManyMutationInput,
    Prisma.WriterUncheckedUpdateManyWithoutLabelInput
  >;
};

export type WriterCreateWithoutSharedWorkspaceAccountAccessInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.WRITER_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  workspaceAccount: Prisma.WorkspaceAccountCreateNestedOneWithoutWritersInput;
  label?: Prisma.LabelCreateNestedManyWithoutWritersInput;
};

export type WriterUncheckedCreateWithoutSharedWorkspaceAccountAccessInput = {
  id?: string;
  workspaceAccountId: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.WRITER_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  label?: Prisma.LabelUncheckedCreateNestedManyWithoutWritersInput;
};

export type WriterCreateOrConnectWithoutSharedWorkspaceAccountAccessInput = {
  where: Prisma.WriterWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.WriterCreateWithoutSharedWorkspaceAccountAccessInput,
    Prisma.WriterUncheckedCreateWithoutSharedWorkspaceAccountAccessInput
  >;
};

export type WriterUpsertWithWhereUniqueWithoutSharedWorkspaceAccountAccessInput =
  {
    where: Prisma.WriterWhereUniqueInput;
    update: Prisma.XOR<
      Prisma.WriterUpdateWithoutSharedWorkspaceAccountAccessInput,
      Prisma.WriterUncheckedUpdateWithoutSharedWorkspaceAccountAccessInput
    >;
    create: Prisma.XOR<
      Prisma.WriterCreateWithoutSharedWorkspaceAccountAccessInput,
      Prisma.WriterUncheckedCreateWithoutSharedWorkspaceAccountAccessInput
    >;
  };

export type WriterUpdateWithWhereUniqueWithoutSharedWorkspaceAccountAccessInput =
  {
    where: Prisma.WriterWhereUniqueInput;
    data: Prisma.XOR<
      Prisma.WriterUpdateWithoutSharedWorkspaceAccountAccessInput,
      Prisma.WriterUncheckedUpdateWithoutSharedWorkspaceAccountAccessInput
    >;
  };

export type WriterUpdateManyWithWhereWithoutSharedWorkspaceAccountAccessInput =
  {
    where: Prisma.WriterScalarWhereInput;
    data: Prisma.XOR<
      Prisma.WriterUpdateManyMutationInput,
      Prisma.WriterUncheckedUpdateManyWithoutSharedWorkspaceAccountAccessInput
    >;
  };

export type WriterCreateManyWorkspaceAccountInput = {
  id?: string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?: $Enums.WRITER_STATUS;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type WriterUpdateWithoutWorkspaceAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumWRITER_STATUSFieldUpdateOperationsInput
    | $Enums.WRITER_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  sharedWorkspaceAccountAccess?: Prisma.SharedWorkspaceAccountAccessUpdateManyWithoutWritersNestedInput;
  label?: Prisma.LabelUpdateManyWithoutWritersNestedInput;
};

export type WriterUncheckedUpdateWithoutWorkspaceAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumWRITER_STATUSFieldUpdateOperationsInput
    | $Enums.WRITER_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  sharedWorkspaceAccountAccess?: Prisma.SharedWorkspaceAccountAccessUncheckedUpdateManyWithoutWritersNestedInput;
  label?: Prisma.LabelUncheckedUpdateManyWithoutWritersNestedInput;
};

export type WriterUncheckedUpdateManyWithoutWorkspaceAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumWRITER_STATUSFieldUpdateOperationsInput
    | $Enums.WRITER_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type WriterUpdateWithoutLabelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumWRITER_STATUSFieldUpdateOperationsInput
    | $Enums.WRITER_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  workspaceAccount?: Prisma.WorkspaceAccountUpdateOneRequiredWithoutWritersNestedInput;
  sharedWorkspaceAccountAccess?: Prisma.SharedWorkspaceAccountAccessUpdateManyWithoutWritersNestedInput;
};

export type WriterUncheckedUpdateWithoutLabelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumWRITER_STATUSFieldUpdateOperationsInput
    | $Enums.WRITER_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  sharedWorkspaceAccountAccess?: Prisma.SharedWorkspaceAccountAccessUncheckedUpdateManyWithoutWritersNestedInput;
};

export type WriterUncheckedUpdateManyWithoutLabelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumWRITER_STATUSFieldUpdateOperationsInput
    | $Enums.WRITER_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type WriterUpdateWithoutSharedWorkspaceAccountAccessInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumWRITER_STATUSFieldUpdateOperationsInput
    | $Enums.WRITER_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  workspaceAccount?: Prisma.WorkspaceAccountUpdateOneRequiredWithoutWritersNestedInput;
  label?: Prisma.LabelUpdateManyWithoutWritersNestedInput;
};

export type WriterUncheckedUpdateWithoutSharedWorkspaceAccountAccessInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  status?:
    | Prisma.EnumWRITER_STATUSFieldUpdateOperationsInput
    | $Enums.WRITER_STATUS;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  label?: Prisma.LabelUncheckedUpdateManyWithoutWritersNestedInput;
};

export type WriterUncheckedUpdateManyWithoutSharedWorkspaceAccountAccessInput =
  {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    workspaceAccountId?: Prisma.StringFieldUpdateOperationsInput | string;
    metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
    status?:
      | Prisma.EnumWRITER_STATUSFieldUpdateOperationsInput
      | $Enums.WRITER_STATUS;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  };

/**
 * Count Type WriterCountOutputType
 */

export type WriterCountOutputType = {
  sharedWorkspaceAccountAccess: number;
  label: number;
};

export type WriterCountOutputTypeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  sharedWorkspaceAccountAccess?:
    | boolean
    | WriterCountOutputTypeCountSharedWorkspaceAccountAccessArgs;
  label?: boolean | WriterCountOutputTypeCountLabelArgs;
};

/**
 * WriterCountOutputType without action
 */
export type WriterCountOutputTypeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WriterCountOutputType
   */
  select?: Prisma.WriterCountOutputTypeSelect<ExtArgs> | null;
};

/**
 * WriterCountOutputType without action
 */
export type WriterCountOutputTypeCountSharedWorkspaceAccountAccessArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.SharedWorkspaceAccountAccessWhereInput;
};

/**
 * WriterCountOutputType without action
 */
export type WriterCountOutputTypeCountLabelArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.LabelWhereInput;
};

export type WriterSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    workspaceAccountId?: boolean;
    metadata?: boolean;
    status?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
    sharedWorkspaceAccountAccess?:
      | boolean
      | Prisma.Writer$sharedWorkspaceAccountAccessArgs<ExtArgs>;
    label?: boolean | Prisma.Writer$labelArgs<ExtArgs>;
    _count?: boolean | Prisma.WriterCountOutputTypeDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["writer"]
>;

export type WriterSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    workspaceAccountId?: boolean;
    metadata?: boolean;
    status?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["writer"]
>;

export type WriterSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    workspaceAccountId?: boolean;
    metadata?: boolean;
    status?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["writer"]
>;

export type WriterSelectScalar = {
  id?: boolean;
  workspaceAccountId?: boolean;
  metadata?: boolean;
  status?: boolean;
  createdAt?: boolean;
  updatedAt?: boolean;
};

export type WriterOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | "id"
  | "workspaceAccountId"
  | "metadata"
  | "status"
  | "createdAt"
  | "updatedAt",
  ExtArgs["result"]["writer"]
>;
export type WriterInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
  sharedWorkspaceAccountAccess?:
    | boolean
    | Prisma.Writer$sharedWorkspaceAccountAccessArgs<ExtArgs>;
  label?: boolean | Prisma.Writer$labelArgs<ExtArgs>;
  _count?: boolean | Prisma.WriterCountOutputTypeDefaultArgs<ExtArgs>;
};
export type WriterIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
};
export type WriterIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  workspaceAccount?: boolean | Prisma.WorkspaceAccountDefaultArgs<ExtArgs>;
};

export type $WriterPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: "Writer";
  objects: {
    workspaceAccount: Prisma.$WorkspaceAccountPayload<ExtArgs>;
    sharedWorkspaceAccountAccess: Prisma.$SharedWorkspaceAccountAccessPayload<ExtArgs>[];
    label: Prisma.$LabelPayload<ExtArgs>[];
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      workspaceAccountId: string;
      metadata: runtime.JsonValue | null;
      status: $Enums.WRITER_STATUS;
      createdAt: Date;
      updatedAt: Date;
    },
    ExtArgs["result"]["writer"]
  >;
  composites: {};
};

export type WriterGetPayload<
  S extends boolean | null | undefined | WriterDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$WriterPayload, S>;

export type WriterCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<WriterFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
  select?: WriterCountAggregateInputType | true;
};

export interface WriterDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["Writer"];
    meta: { name: "Writer" };
  };
  /**
   * Find zero or one Writer that matches the filter.
   * @param {WriterFindUniqueArgs} args - Arguments to find a Writer
   * @example
   * // Get one Writer
   * const writer = await prisma.writer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WriterFindUniqueArgs>(
    args: Prisma.SelectSubset<T, WriterFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__WriterClient<
    runtime.Types.Result.GetResult<
      Prisma.$WriterPayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one Writer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WriterFindUniqueOrThrowArgs} args - Arguments to find a Writer
   * @example
   * // Get one Writer
   * const writer = await prisma.writer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WriterFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, WriterFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__WriterClient<
    runtime.Types.Result.GetResult<
      Prisma.$WriterPayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first Writer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WriterFindFirstArgs} args - Arguments to find a Writer
   * @example
   * // Get one Writer
   * const writer = await prisma.writer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WriterFindFirstArgs>(
    args?: Prisma.SelectSubset<T, WriterFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__WriterClient<
    runtime.Types.Result.GetResult<
      Prisma.$WriterPayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first Writer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WriterFindFirstOrThrowArgs} args - Arguments to find a Writer
   * @example
   * // Get one Writer
   * const writer = await prisma.writer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WriterFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, WriterFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__WriterClient<
    runtime.Types.Result.GetResult<
      Prisma.$WriterPayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more Writers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WriterFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Writers
   * const writers = await prisma.writer.findMany()
   *
   * // Get first 10 Writers
   * const writers = await prisma.writer.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const writerWithIdOnly = await prisma.writer.findMany({ select: { id: true } })
   *
   */
  findMany<T extends WriterFindManyArgs>(
    args?: Prisma.SelectSubset<T, WriterFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$WriterPayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >;

  /**
   * Create a Writer.
   * @param {WriterCreateArgs} args - Arguments to create a Writer.
   * @example
   * // Create one Writer
   * const Writer = await prisma.writer.create({
   *   data: {
   *     // ... data to create a Writer
   *   }
   * })
   *
   */
  create<T extends WriterCreateArgs>(
    args: Prisma.SelectSubset<T, WriterCreateArgs<ExtArgs>>
  ): Prisma.Prisma__WriterClient<
    runtime.Types.Result.GetResult<
      Prisma.$WriterPayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many Writers.
   * @param {WriterCreateManyArgs} args - Arguments to create many Writers.
   * @example
   * // Create many Writers
   * const writer = await prisma.writer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends WriterCreateManyArgs>(
    args?: Prisma.SelectSubset<T, WriterCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many Writers and returns the data saved in the database.
   * @param {WriterCreateManyAndReturnArgs} args - Arguments to create many Writers.
   * @example
   * // Create many Writers
   * const writer = await prisma.writer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many Writers and only return the `id`
   * const writerWithIdOnly = await prisma.writer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends WriterCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, WriterCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$WriterPayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a Writer.
   * @param {WriterDeleteArgs} args - Arguments to delete one Writer.
   * @example
   * // Delete one Writer
   * const Writer = await prisma.writer.delete({
   *   where: {
   *     // ... filter to delete one Writer
   *   }
   * })
   *
   */
  delete<T extends WriterDeleteArgs>(
    args: Prisma.SelectSubset<T, WriterDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__WriterClient<
    runtime.Types.Result.GetResult<
      Prisma.$WriterPayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one Writer.
   * @param {WriterUpdateArgs} args - Arguments to update one Writer.
   * @example
   * // Update one Writer
   * const writer = await prisma.writer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends WriterUpdateArgs>(
    args: Prisma.SelectSubset<T, WriterUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__WriterClient<
    runtime.Types.Result.GetResult<
      Prisma.$WriterPayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more Writers.
   * @param {WriterDeleteManyArgs} args - Arguments to filter Writers to delete.
   * @example
   * // Delete a few Writers
   * const { count } = await prisma.writer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends WriterDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, WriterDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more Writers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WriterUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Writers
   * const writer = await prisma.writer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends WriterUpdateManyArgs>(
    args: Prisma.SelectSubset<T, WriterUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more Writers and returns the data updated in the database.
   * @param {WriterUpdateManyAndReturnArgs} args - Arguments to update many Writers.
   * @example
   * // Update many Writers
   * const writer = await prisma.writer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more Writers and only return the `id`
   * const writerWithIdOnly = await prisma.writer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends WriterUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, WriterUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$WriterPayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one Writer.
   * @param {WriterUpsertArgs} args - Arguments to update or create a Writer.
   * @example
   * // Update or create a Writer
   * const writer = await prisma.writer.upsert({
   *   create: {
   *     // ... data to create a Writer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Writer we want to update
   *   }
   * })
   */
  upsert<T extends WriterUpsertArgs>(
    args: Prisma.SelectSubset<T, WriterUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__WriterClient<
    runtime.Types.Result.GetResult<
      Prisma.$WriterPayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of Writers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WriterCountArgs} args - Arguments to filter Writers to count.
   * @example
   * // Count the number of Writers
   * const count = await prisma.writer.count({
   *   where: {
   *     // ... the filter for the Writers we want to count
   *   }
   * })
   **/
  count<T extends WriterCountArgs>(
    args?: Prisma.Subset<T, WriterCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<T["select"], WriterCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a Writer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WriterAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends WriterAggregateArgs>(
    args: Prisma.Subset<T, WriterAggregateArgs>
  ): Prisma.PrismaPromise<GetWriterAggregateType<T>>;

  /**
   * Group by Writer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WriterGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends WriterGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WriterGroupByArgs["orderBy"] }
      : { orderBy?: WriterGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    "Field ",
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ];
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, WriterGroupByArgs, OrderByArg> &
      InputErrors
  ): {} extends InputErrors
    ? GetWriterGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the Writer model
   */
  readonly fields: WriterFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Writer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WriterClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise";
  workspaceAccount<T extends Prisma.WorkspaceAccountDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.WorkspaceAccountDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__WorkspaceAccountClient<
    | runtime.Types.Result.GetResult<
        Prisma.$WorkspaceAccountPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  sharedWorkspaceAccountAccess<
    T extends Prisma.Writer$sharedWorkspaceAccountAccessArgs<ExtArgs> = {},
  >(
    args?: Prisma.Subset<
      T,
      Prisma.Writer$sharedWorkspaceAccountAccessArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$SharedWorkspaceAccountAccessPayload<ExtArgs>,
        T,
        "findMany",
        GlobalOmitOptions
      >
    | Null
  >;
  label<T extends Prisma.Writer$labelArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.Writer$labelArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$LabelPayload<ExtArgs>,
        T,
        "findMany",
        GlobalOmitOptions
      >
    | Null
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the Writer model
 */
export interface WriterFieldRefs {
  readonly id: Prisma.FieldRef<"Writer", "String">;
  readonly workspaceAccountId: Prisma.FieldRef<"Writer", "String">;
  readonly metadata: Prisma.FieldRef<"Writer", "Json">;
  readonly status: Prisma.FieldRef<"Writer", "WRITER_STATUS">;
  readonly createdAt: Prisma.FieldRef<"Writer", "DateTime">;
  readonly updatedAt: Prisma.FieldRef<"Writer", "DateTime">;
}

// Custom InputTypes
/**
 * Writer findUnique
 */
export type WriterFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Writer
   */
  select?: Prisma.WriterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Writer
   */
  omit?: Prisma.WriterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WriterInclude<ExtArgs> | null;
  /**
   * Filter, which Writer to fetch.
   */
  where: Prisma.WriterWhereUniqueInput;
};

/**
 * Writer findUniqueOrThrow
 */
export type WriterFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Writer
   */
  select?: Prisma.WriterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Writer
   */
  omit?: Prisma.WriterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WriterInclude<ExtArgs> | null;
  /**
   * Filter, which Writer to fetch.
   */
  where: Prisma.WriterWhereUniqueInput;
};

/**
 * Writer findFirst
 */
export type WriterFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Writer
   */
  select?: Prisma.WriterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Writer
   */
  omit?: Prisma.WriterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WriterInclude<ExtArgs> | null;
  /**
   * Filter, which Writer to fetch.
   */
  where?: Prisma.WriterWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Writers to fetch.
   */
  orderBy?:
    | Prisma.WriterOrderByWithRelationInput
    | Prisma.WriterOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for Writers.
   */
  cursor?: Prisma.WriterWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Writers from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Writers.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of Writers.
   */
  distinct?: Prisma.WriterScalarFieldEnum | Prisma.WriterScalarFieldEnum[];
};

/**
 * Writer findFirstOrThrow
 */
export type WriterFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Writer
   */
  select?: Prisma.WriterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Writer
   */
  omit?: Prisma.WriterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WriterInclude<ExtArgs> | null;
  /**
   * Filter, which Writer to fetch.
   */
  where?: Prisma.WriterWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Writers to fetch.
   */
  orderBy?:
    | Prisma.WriterOrderByWithRelationInput
    | Prisma.WriterOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for Writers.
   */
  cursor?: Prisma.WriterWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Writers from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Writers.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of Writers.
   */
  distinct?: Prisma.WriterScalarFieldEnum | Prisma.WriterScalarFieldEnum[];
};

/**
 * Writer findMany
 */
export type WriterFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Writer
   */
  select?: Prisma.WriterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Writer
   */
  omit?: Prisma.WriterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WriterInclude<ExtArgs> | null;
  /**
   * Filter, which Writers to fetch.
   */
  where?: Prisma.WriterWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Writers to fetch.
   */
  orderBy?:
    | Prisma.WriterOrderByWithRelationInput
    | Prisma.WriterOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing Writers.
   */
  cursor?: Prisma.WriterWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Writers from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Writers.
   */
  skip?: number;
  distinct?: Prisma.WriterScalarFieldEnum | Prisma.WriterScalarFieldEnum[];
};

/**
 * Writer create
 */
export type WriterCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Writer
   */
  select?: Prisma.WriterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Writer
   */
  omit?: Prisma.WriterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WriterInclude<ExtArgs> | null;
  /**
   * The data needed to create a Writer.
   */
  data: Prisma.XOR<Prisma.WriterCreateInput, Prisma.WriterUncheckedCreateInput>;
};

/**
 * Writer createMany
 */
export type WriterCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many Writers.
   */
  data: Prisma.WriterCreateManyInput | Prisma.WriterCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * Writer createManyAndReturn
 */
export type WriterCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Writer
   */
  select?: Prisma.WriterSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the Writer
   */
  omit?: Prisma.WriterOmit<ExtArgs> | null;
  /**
   * The data used to create many Writers.
   */
  data: Prisma.WriterCreateManyInput | Prisma.WriterCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WriterIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * Writer update
 */
export type WriterUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Writer
   */
  select?: Prisma.WriterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Writer
   */
  omit?: Prisma.WriterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WriterInclude<ExtArgs> | null;
  /**
   * The data needed to update a Writer.
   */
  data: Prisma.XOR<Prisma.WriterUpdateInput, Prisma.WriterUncheckedUpdateInput>;
  /**
   * Choose, which Writer to update.
   */
  where: Prisma.WriterWhereUniqueInput;
};

/**
 * Writer updateMany
 */
export type WriterUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update Writers.
   */
  data: Prisma.XOR<
    Prisma.WriterUpdateManyMutationInput,
    Prisma.WriterUncheckedUpdateManyInput
  >;
  /**
   * Filter which Writers to update
   */
  where?: Prisma.WriterWhereInput;
  /**
   * Limit how many Writers to update.
   */
  limit?: number;
};

/**
 * Writer updateManyAndReturn
 */
export type WriterUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Writer
   */
  select?: Prisma.WriterSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the Writer
   */
  omit?: Prisma.WriterOmit<ExtArgs> | null;
  /**
   * The data used to update Writers.
   */
  data: Prisma.XOR<
    Prisma.WriterUpdateManyMutationInput,
    Prisma.WriterUncheckedUpdateManyInput
  >;
  /**
   * Filter which Writers to update
   */
  where?: Prisma.WriterWhereInput;
  /**
   * Limit how many Writers to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WriterIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * Writer upsert
 */
export type WriterUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Writer
   */
  select?: Prisma.WriterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Writer
   */
  omit?: Prisma.WriterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WriterInclude<ExtArgs> | null;
  /**
   * The filter to search for the Writer to update in case it exists.
   */
  where: Prisma.WriterWhereUniqueInput;
  /**
   * In case the Writer found by the `where` argument doesn't exist, create a new Writer with this data.
   */
  create: Prisma.XOR<
    Prisma.WriterCreateInput,
    Prisma.WriterUncheckedCreateInput
  >;
  /**
   * In case the Writer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.WriterUpdateInput,
    Prisma.WriterUncheckedUpdateInput
  >;
};

/**
 * Writer delete
 */
export type WriterDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Writer
   */
  select?: Prisma.WriterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Writer
   */
  omit?: Prisma.WriterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WriterInclude<ExtArgs> | null;
  /**
   * Filter which Writer to delete.
   */
  where: Prisma.WriterWhereUniqueInput;
};

/**
 * Writer deleteMany
 */
export type WriterDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which Writers to delete
   */
  where?: Prisma.WriterWhereInput;
  /**
   * Limit how many Writers to delete.
   */
  limit?: number;
};

/**
 * Writer.sharedWorkspaceAccountAccess
 */
export type Writer$sharedWorkspaceAccountAccessArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SharedWorkspaceAccountAccess
   */
  select?: Prisma.SharedWorkspaceAccountAccessSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the SharedWorkspaceAccountAccess
   */
  omit?: Prisma.SharedWorkspaceAccountAccessOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SharedWorkspaceAccountAccessInclude<ExtArgs> | null;
  where?: Prisma.SharedWorkspaceAccountAccessWhereInput;
  orderBy?:
    | Prisma.SharedWorkspaceAccountAccessOrderByWithRelationInput
    | Prisma.SharedWorkspaceAccountAccessOrderByWithRelationInput[];
  cursor?: Prisma.SharedWorkspaceAccountAccessWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?:
    | Prisma.SharedWorkspaceAccountAccessScalarFieldEnum
    | Prisma.SharedWorkspaceAccountAccessScalarFieldEnum[];
};

/**
 * Writer.label
 */
export type Writer$labelArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Label
   */
  select?: Prisma.LabelSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Label
   */
  omit?: Prisma.LabelOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LabelInclude<ExtArgs> | null;
  where?: Prisma.LabelWhereInput;
  orderBy?:
    | Prisma.LabelOrderByWithRelationInput
    | Prisma.LabelOrderByWithRelationInput[];
  cursor?: Prisma.LabelWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?: Prisma.LabelScalarFieldEnum | Prisma.LabelScalarFieldEnum[];
};

/**
 * Writer without action
 */
export type WriterDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Writer
   */
  select?: Prisma.WriterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Writer
   */
  omit?: Prisma.WriterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WriterInclude<ExtArgs> | null;
};
