/*
  Warnings:

  - The values [DRAFT,PUBLISHED,ARCHIVED,PAUSED,TAKEN_DOWN] on the enum `ARTIST_STATUS` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ,WRITE] on the enum `ARTIST_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ] on the enum `CONSUMPTION_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ] on the enum `ENGAGEMENT_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ] on the enum `GEO_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [DRAFT,PUBLISHED,ARCHIVED,PAUSED,TAKEN_DOWN] on the enum `LABEL_STATUS` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ,WRITE] on the enum `LABEL_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ,WRITE] on the enum `PERFORMER_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ,WRITE] on the enum `PRODUCER_AND_ENGINEER_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [DRAFT,PUBLISHED,ARCHIVED,PAUSED,TAKEN_DOWN] on the enum `PUBLISHER_STATUS` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ,WRITE] on the enum `PUBLISHER_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [DRAFT,PUBLISHED,ARCHIVED,PAUSED,TAKEN_DOWN] on the enum `RELEASE_STATUS` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ,WRITE] on the enum `RELEASE_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ,WRITE,UPDATE] on the enum `REPORTING_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ] on the enum `REVENUE_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [CANCELLED] on the enum `RIGHTS_MANAGEMENT_STATUS` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ,WRITE] on the enum `RIGHTS_MANAGEMENT_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [DRAFT,PUBLISHED,ARCHIVED,PAUSED,TAKEN_DOWN] on the enum `RINGTONE_STATUS` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ,WRITE] on the enum `RINGTONE_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ,WRITE] on the enum `TRACK_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [PENDING,ON_HOLD,FAILED,CANCELLED] on the enum `TRANSACTION_STATUS` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ,WRITE] on the enum `TRANSACTION_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ,WRITE] on the enum `USER_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [DRAFT,PUBLISHED,ARCHIVED,PAUSED,TAKEN_DOWN] on the enum `VIDEO_STATUS` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ,WRITE] on the enum `VIDEO_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [ON_HOLD,FAILED,CANCELLED] on the enum `WITHDRAWAL_STATUS` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ,WRITE,UPDATE] on the enum `WITHDRAWS_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ,WRITE] on the enum `WORKSPACE_ACCOUNT_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - The values [READ,WRITE] on the enum `WRITER_SYSTEM_ACCESS_LEVEL` will be removed. If these variants are still used in the database, this will fail.
  - You are about to drop the column `status` on the `Performer` table. All the data in the column will be lost.
  - You are about to drop the column `status` on the `ProducerAndEngineer` table. All the data in the column will be lost.
  - You are about to drop the column `status` on the `Track` table. All the data in the column will be lost.
  - You are about to drop the column `status` on the `Writer` table. All the data in the column will be lost.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ARTIST_STATUS_new" AS ENUM ('PENDING', 'PROCESSING', 'APPROVED', 'REJECTED', 'SUSPENDED', 'ACTIVE');
ALTER TABLE "public"."Artist" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Artist" ALTER COLUMN "status" TYPE "ARTIST_STATUS_new" USING ("status"::text::"ARTIST_STATUS_new");
ALTER TYPE "ARTIST_STATUS" RENAME TO "ARTIST_STATUS_old";
ALTER TYPE "ARTIST_STATUS_new" RENAME TO "ARTIST_STATUS";
DROP TYPE "public"."ARTIST_STATUS_old";
ALTER TABLE "Artist" ALTER COLUMN "status" SET DEFAULT 'PENDING';
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "ARTIST_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'APPROVE', 'STATUS', 'CREATE', 'UPDATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "artistsAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "artistsAccessLevel" TYPE "ARTIST_SYSTEM_ACCESS_LEVEL_new"[] USING ("artistsAccessLevel"::text::"ARTIST_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "ARTIST_SYSTEM_ACCESS_LEVEL" RENAME TO "ARTIST_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "ARTIST_SYSTEM_ACCESS_LEVEL_new" RENAME TO "ARTIST_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."ARTIST_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "artistsAccessLevel" SET DEFAULT ARRAY[]::"ARTIST_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "CONSUMPTION_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "consumptionAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "consumptionAccessLevel" TYPE "CONSUMPTION_SYSTEM_ACCESS_LEVEL_new"[] USING ("consumptionAccessLevel"::text::"CONSUMPTION_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "CONSUMPTION_SYSTEM_ACCESS_LEVEL" RENAME TO "CONSUMPTION_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "CONSUMPTION_SYSTEM_ACCESS_LEVEL_new" RENAME TO "CONSUMPTION_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."CONSUMPTION_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "consumptionAccessLevel" SET DEFAULT ARRAY[]::"CONSUMPTION_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "ENGAGEMENT_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "engagementAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "engagementAccessLevel" TYPE "ENGAGEMENT_SYSTEM_ACCESS_LEVEL_new"[] USING ("engagementAccessLevel"::text::"ENGAGEMENT_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "ENGAGEMENT_SYSTEM_ACCESS_LEVEL" RENAME TO "ENGAGEMENT_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "ENGAGEMENT_SYSTEM_ACCESS_LEVEL_new" RENAME TO "ENGAGEMENT_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."ENGAGEMENT_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "engagementAccessLevel" SET DEFAULT ARRAY[]::"ENGAGEMENT_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "GEO_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "geoAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "geoAccessLevel" TYPE "GEO_SYSTEM_ACCESS_LEVEL_new"[] USING ("geoAccessLevel"::text::"GEO_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "GEO_SYSTEM_ACCESS_LEVEL" RENAME TO "GEO_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "GEO_SYSTEM_ACCESS_LEVEL_new" RENAME TO "GEO_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."GEO_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "geoAccessLevel" SET DEFAULT ARRAY[]::"GEO_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "LABEL_STATUS_new" AS ENUM ('PENDING', 'PROCESSING', 'APPROVED', 'REJECTED', 'SUSPENDED', 'ACTIVE');
ALTER TABLE "public"."Label" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Label" ALTER COLUMN "status" TYPE "LABEL_STATUS_new" USING ("status"::text::"LABEL_STATUS_new");
ALTER TYPE "LABEL_STATUS" RENAME TO "LABEL_STATUS_old";
ALTER TYPE "LABEL_STATUS_new" RENAME TO "LABEL_STATUS";
DROP TYPE "public"."LABEL_STATUS_old";
ALTER TABLE "Label" ALTER COLUMN "status" SET DEFAULT 'PENDING';
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "LABEL_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'APPROVE', 'STATUS', 'CREATE', 'UPDATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "labelsAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "labelsAccessLevel" TYPE "LABEL_SYSTEM_ACCESS_LEVEL_new"[] USING ("labelsAccessLevel"::text::"LABEL_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "LABEL_SYSTEM_ACCESS_LEVEL" RENAME TO "LABEL_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "LABEL_SYSTEM_ACCESS_LEVEL_new" RENAME TO "LABEL_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."LABEL_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "labelsAccessLevel" SET DEFAULT ARRAY[]::"LABEL_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "PERFORMER_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'CREATE', 'UPDATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "performersAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "performersAccessLevel" TYPE "PERFORMER_SYSTEM_ACCESS_LEVEL_new"[] USING ("performersAccessLevel"::text::"PERFORMER_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "PERFORMER_SYSTEM_ACCESS_LEVEL" RENAME TO "PERFORMER_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "PERFORMER_SYSTEM_ACCESS_LEVEL_new" RENAME TO "PERFORMER_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."PERFORMER_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "performersAccessLevel" SET DEFAULT ARRAY[]::"PERFORMER_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "PRODUCER_AND_ENGINEER_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'CREATE', 'UPDATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "producersAndEngineersAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "producersAndEngineersAccessLevel" TYPE "PRODUCER_AND_ENGINEER_SYSTEM_ACCESS_LEVEL_new"[] USING ("producersAndEngineersAccessLevel"::text::"PRODUCER_AND_ENGINEER_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "PRODUCER_AND_ENGINEER_SYSTEM_ACCESS_LEVEL" RENAME TO "PRODUCER_AND_ENGINEER_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "PRODUCER_AND_ENGINEER_SYSTEM_ACCESS_LEVEL_new" RENAME TO "PRODUCER_AND_ENGINEER_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."PRODUCER_AND_ENGINEER_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "producersAndEngineersAccessLevel" SET DEFAULT ARRAY[]::"PRODUCER_AND_ENGINEER_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "PUBLISHER_STATUS_new" AS ENUM ('PENDING', 'PROCESSING', 'APPROVED', 'REJECTED', 'SUSPENDED', 'ACTIVE');
ALTER TABLE "public"."Publisher" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Publisher" ALTER COLUMN "status" TYPE "PUBLISHER_STATUS_new" USING ("status"::text::"PUBLISHER_STATUS_new");
ALTER TYPE "PUBLISHER_STATUS" RENAME TO "PUBLISHER_STATUS_old";
ALTER TYPE "PUBLISHER_STATUS_new" RENAME TO "PUBLISHER_STATUS";
DROP TYPE "public"."PUBLISHER_STATUS_old";
ALTER TABLE "Publisher" ALTER COLUMN "status" SET DEFAULT 'PENDING';
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "PUBLISHER_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'APPROVE', 'STATUS', 'CREATE', 'UPDATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "publishersAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "publishersAccessLevel" TYPE "PUBLISHER_SYSTEM_ACCESS_LEVEL_new"[] USING ("publishersAccessLevel"::text::"PUBLISHER_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "PUBLISHER_SYSTEM_ACCESS_LEVEL" RENAME TO "PUBLISHER_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "PUBLISHER_SYSTEM_ACCESS_LEVEL_new" RENAME TO "PUBLISHER_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."PUBLISHER_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "publishersAccessLevel" SET DEFAULT ARRAY[]::"PUBLISHER_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "RELEASE_STATUS_new" AS ENUM ('PENDING', 'PROCESSING', 'APPROVED', 'REJECTED', 'SUSPENDED', 'TAKENDOWN', 'RELEASED');
ALTER TABLE "public"."Release" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Release" ALTER COLUMN "status" TYPE "RELEASE_STATUS_new" USING ("status"::text::"RELEASE_STATUS_new");
ALTER TYPE "RELEASE_STATUS" RENAME TO "RELEASE_STATUS_old";
ALTER TYPE "RELEASE_STATUS_new" RENAME TO "RELEASE_STATUS";
DROP TYPE "public"."RELEASE_STATUS_old";
ALTER TABLE "Release" ALTER COLUMN "status" SET DEFAULT 'PENDING';
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "RELEASE_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'APPROVE', 'STATUS', 'CREATE', 'UPDATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "releasesAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "releasesAccessLevel" TYPE "RELEASE_SYSTEM_ACCESS_LEVEL_new"[] USING ("releasesAccessLevel"::text::"RELEASE_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "RELEASE_SYSTEM_ACCESS_LEVEL" RENAME TO "RELEASE_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "RELEASE_SYSTEM_ACCESS_LEVEL_new" RENAME TO "RELEASE_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."RELEASE_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "releasesAccessLevel" SET DEFAULT ARRAY[]::"RELEASE_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "REPORTING_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'CREATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "reportingAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "reportingAccessLevel" TYPE "REPORTING_SYSTEM_ACCESS_LEVEL_new"[] USING ("reportingAccessLevel"::text::"REPORTING_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "REPORTING_SYSTEM_ACCESS_LEVEL" RENAME TO "REPORTING_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "REPORTING_SYSTEM_ACCESS_LEVEL_new" RENAME TO "REPORTING_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."REPORTING_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "reportingAccessLevel" SET DEFAULT ARRAY[]::"REPORTING_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "REVENUE_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "revenueAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "revenueAccessLevel" TYPE "REVENUE_SYSTEM_ACCESS_LEVEL_new"[] USING ("revenueAccessLevel"::text::"REVENUE_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "REVENUE_SYSTEM_ACCESS_LEVEL" RENAME TO "REVENUE_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "REVENUE_SYSTEM_ACCESS_LEVEL_new" RENAME TO "REVENUE_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."REVENUE_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "revenueAccessLevel" SET DEFAULT ARRAY[]::"REVENUE_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "RIGHTS_MANAGEMENT_STATUS_new" AS ENUM ('PENDING', 'PROCESSING', 'APPROVED', 'REJECTED', 'FAILED', 'COMPLETED');
ALTER TABLE "public"."RightsManagement" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "RightsManagement" ALTER COLUMN "status" TYPE "RIGHTS_MANAGEMENT_STATUS_new" USING ("status"::text::"RIGHTS_MANAGEMENT_STATUS_new");
ALTER TYPE "RIGHTS_MANAGEMENT_STATUS" RENAME TO "RIGHTS_MANAGEMENT_STATUS_old";
ALTER TYPE "RIGHTS_MANAGEMENT_STATUS_new" RENAME TO "RIGHTS_MANAGEMENT_STATUS";
DROP TYPE "public"."RIGHTS_MANAGEMENT_STATUS_old";
ALTER TABLE "RightsManagement" ALTER COLUMN "status" SET DEFAULT 'PENDING';
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "RIGHTS_MANAGEMENT_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'APPROVE', 'STATUS', 'CREATE', 'UPDATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "rightsManagementAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "rightsManagementAccessLevel" TYPE "RIGHTS_MANAGEMENT_SYSTEM_ACCESS_LEVEL_new"[] USING ("rightsManagementAccessLevel"::text::"RIGHTS_MANAGEMENT_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "RIGHTS_MANAGEMENT_SYSTEM_ACCESS_LEVEL" RENAME TO "RIGHTS_MANAGEMENT_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "RIGHTS_MANAGEMENT_SYSTEM_ACCESS_LEVEL_new" RENAME TO "RIGHTS_MANAGEMENT_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."RIGHTS_MANAGEMENT_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "rightsManagementAccessLevel" SET DEFAULT ARRAY[]::"RIGHTS_MANAGEMENT_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "RINGTONE_STATUS_new" AS ENUM ('PENDING', 'PROCESSING', 'APPROVED', 'REJECTED', 'SUSPENDED', 'TAKENDOWN', 'RELEASED');
ALTER TABLE "public"."Ringtone" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Ringtone" ALTER COLUMN "status" TYPE "RINGTONE_STATUS_new" USING ("status"::text::"RINGTONE_STATUS_new");
ALTER TYPE "RINGTONE_STATUS" RENAME TO "RINGTONE_STATUS_old";
ALTER TYPE "RINGTONE_STATUS_new" RENAME TO "RINGTONE_STATUS";
DROP TYPE "public"."RINGTONE_STATUS_old";
ALTER TABLE "Ringtone" ALTER COLUMN "status" SET DEFAULT 'PENDING';
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "RINGTONE_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'APPROVE', 'STATUS', 'CREATE', 'UPDATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "ringtonesAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "ringtonesAccessLevel" TYPE "RINGTONE_SYSTEM_ACCESS_LEVEL_new"[] USING ("ringtonesAccessLevel"::text::"RINGTONE_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "RINGTONE_SYSTEM_ACCESS_LEVEL" RENAME TO "RINGTONE_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "RINGTONE_SYSTEM_ACCESS_LEVEL_new" RENAME TO "RINGTONE_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."RINGTONE_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "ringtonesAccessLevel" SET DEFAULT ARRAY[]::"RINGTONE_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "TRACK_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'CREATE', 'UPDATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "tracksAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "tracksAccessLevel" TYPE "TRACK_SYSTEM_ACCESS_LEVEL_new"[] USING ("tracksAccessLevel"::text::"TRACK_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "TRACK_SYSTEM_ACCESS_LEVEL" RENAME TO "TRACK_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "TRACK_SYSTEM_ACCESS_LEVEL_new" RENAME TO "TRACK_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."TRACK_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "tracksAccessLevel" SET DEFAULT ARRAY[]::"TRACK_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "TRANSACTION_STATUS_new" AS ENUM ('PROCESSING', 'APPROVED', 'REJECTED', 'COMPLETED');
ALTER TABLE "public"."Transaction" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Transaction" ALTER COLUMN "status" TYPE "TRANSACTION_STATUS_new" USING ("status"::text::"TRANSACTION_STATUS_new");
ALTER TYPE "TRANSACTION_STATUS" RENAME TO "TRANSACTION_STATUS_old";
ALTER TYPE "TRANSACTION_STATUS_new" RENAME TO "TRANSACTION_STATUS";
DROP TYPE "public"."TRANSACTION_STATUS_old";
ALTER TABLE "Transaction" ALTER COLUMN "status" SET DEFAULT 'PROCESSING';
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "TRANSACTION_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'EXPORT', 'STATUS', 'CREATE', 'UPDATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "transactionsAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "transactionsAccessLevel" TYPE "TRANSACTION_SYSTEM_ACCESS_LEVEL_new"[] USING ("transactionsAccessLevel"::text::"TRANSACTION_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "TRANSACTION_SYSTEM_ACCESS_LEVEL" RENAME TO "TRANSACTION_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "TRANSACTION_SYSTEM_ACCESS_LEVEL_new" RENAME TO "TRANSACTION_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."TRANSACTION_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "transactionsAccessLevel" SET DEFAULT ARRAY[]::"TRANSACTION_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "USER_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'APPROVE', 'SUSPEND', 'CREATE', 'UPDATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "usersAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "usersAccessLevel" TYPE "USER_SYSTEM_ACCESS_LEVEL_new"[] USING ("usersAccessLevel"::text::"USER_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "USER_SYSTEM_ACCESS_LEVEL" RENAME TO "USER_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "USER_SYSTEM_ACCESS_LEVEL_new" RENAME TO "USER_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."USER_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "usersAccessLevel" SET DEFAULT ARRAY[]::"USER_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "VIDEO_STATUS_new" AS ENUM ('PENDING', 'PROCESSING', 'APPROVED', 'REJECTED', 'SUSPENDED', 'TAKENDOWN', 'RELEASED');
ALTER TABLE "public"."Video" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Video" ALTER COLUMN "status" TYPE "VIDEO_STATUS_new" USING ("status"::text::"VIDEO_STATUS_new");
ALTER TYPE "VIDEO_STATUS" RENAME TO "VIDEO_STATUS_old";
ALTER TYPE "VIDEO_STATUS_new" RENAME TO "VIDEO_STATUS";
DROP TYPE "public"."VIDEO_STATUS_old";
ALTER TABLE "Video" ALTER COLUMN "status" SET DEFAULT 'PENDING';
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "VIDEO_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'APPROVE', 'STATUS', 'CREATE', 'UPDATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "videosAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "videosAccessLevel" TYPE "VIDEO_SYSTEM_ACCESS_LEVEL_new"[] USING ("videosAccessLevel"::text::"VIDEO_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "VIDEO_SYSTEM_ACCESS_LEVEL" RENAME TO "VIDEO_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "VIDEO_SYSTEM_ACCESS_LEVEL_new" RENAME TO "VIDEO_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."VIDEO_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "videosAccessLevel" SET DEFAULT ARRAY[]::"VIDEO_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "WITHDRAWAL_STATUS_new" AS ENUM ('PENDING', 'PROCESSING', 'APPROVED', 'REJECTED', 'COMPLETED');
ALTER TABLE "public"."Withdrawal" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Withdrawal" ALTER COLUMN "status" TYPE "WITHDRAWAL_STATUS_new" USING ("status"::text::"WITHDRAWAL_STATUS_new");
ALTER TYPE "WITHDRAWAL_STATUS" RENAME TO "WITHDRAWAL_STATUS_old";
ALTER TYPE "WITHDRAWAL_STATUS_new" RENAME TO "WITHDRAWAL_STATUS";
DROP TYPE "public"."WITHDRAWAL_STATUS_old";
ALTER TABLE "Withdrawal" ALTER COLUMN "status" SET DEFAULT 'PENDING';
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "WITHDRAWS_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'APPROVE', 'STATUS', 'CREATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "withdrawsAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "withdrawsAccessLevel" TYPE "WITHDRAWS_SYSTEM_ACCESS_LEVEL_new"[] USING ("withdrawsAccessLevel"::text::"WITHDRAWS_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "WITHDRAWS_SYSTEM_ACCESS_LEVEL" RENAME TO "WITHDRAWS_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "WITHDRAWS_SYSTEM_ACCESS_LEVEL_new" RENAME TO "WITHDRAWS_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."WITHDRAWS_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "withdrawsAccessLevel" SET DEFAULT ARRAY[]::"WITHDRAWS_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "WORKSPACE_ACCOUNT_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'APPROVE', 'SUSPEND', 'TERMINATE', 'CREATE', 'UPDATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "workspaceAccountsAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "workspaceAccountsAccessLevel" TYPE "WORKSPACE_ACCOUNT_SYSTEM_ACCESS_LEVEL_new"[] USING ("workspaceAccountsAccessLevel"::text::"WORKSPACE_ACCOUNT_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "WORKSPACE_ACCOUNT_SYSTEM_ACCESS_LEVEL" RENAME TO "WORKSPACE_ACCOUNT_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "WORKSPACE_ACCOUNT_SYSTEM_ACCESS_LEVEL_new" RENAME TO "WORKSPACE_ACCOUNT_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."WORKSPACE_ACCOUNT_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "workspaceAccountsAccessLevel" SET DEFAULT ARRAY[]::"WORKSPACE_ACCOUNT_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "WRITER_SYSTEM_ACCESS_LEVEL_new" AS ENUM ('VIEW', 'CREATE', 'UPDATE', 'DELETE');
ALTER TABLE "public"."SystemAccess" ALTER COLUMN "writersAccessLevel" DROP DEFAULT;
ALTER TABLE "SystemAccess" ALTER COLUMN "writersAccessLevel" TYPE "WRITER_SYSTEM_ACCESS_LEVEL_new"[] USING ("writersAccessLevel"::text::"WRITER_SYSTEM_ACCESS_LEVEL_new"[]);
ALTER TYPE "WRITER_SYSTEM_ACCESS_LEVEL" RENAME TO "WRITER_SYSTEM_ACCESS_LEVEL_old";
ALTER TYPE "WRITER_SYSTEM_ACCESS_LEVEL_new" RENAME TO "WRITER_SYSTEM_ACCESS_LEVEL";
DROP TYPE "public"."WRITER_SYSTEM_ACCESS_LEVEL_old";
ALTER TABLE "SystemAccess" ALTER COLUMN "writersAccessLevel" SET DEFAULT ARRAY[]::"WRITER_SYSTEM_ACCESS_LEVEL"[];
COMMIT;

-- AlterTable
ALTER TABLE "Artist" ALTER COLUMN "status" SET DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE "Label" ALTER COLUMN "status" SET DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE "Performer" DROP COLUMN "status";

-- AlterTable
ALTER TABLE "ProducerAndEngineer" DROP COLUMN "status";

-- AlterTable
ALTER TABLE "Publisher" ALTER COLUMN "status" SET DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE "Release" ALTER COLUMN "status" SET DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE "Ringtone" ALTER COLUMN "status" SET DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE "Track" DROP COLUMN "status";

-- AlterTable
ALTER TABLE "Transaction" ALTER COLUMN "status" SET DEFAULT 'PROCESSING';

-- AlterTable
ALTER TABLE "Video" ALTER COLUMN "status" SET DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE "WorkspaceAccount" ADD COLUMN     "terminatedAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Writer" DROP COLUMN "status";

-- DropEnum
DROP TYPE "PERFORMER_STATUS";

-- DropEnum
DROP TYPE "PRODUCER_AND_ENGINEER_STATUS";

-- DropEnum
DROP TYPE "TRACK_STATUS";

-- DropEnum
DROP TYPE "WRITER_STATUS";
