-- AlterEnum
ALTER TYPE "RELEASE_SYSTEM_ACCESS_LEVEL" ADD VALUE 'TAKEDOWN';

-- AlterEnum
ALTER TYPE "RINGTONE_SYSTEM_ACCESS_LEVEL" ADD VALUE 'TAKEDOWN';

-- AlterEnum
ALTER TYPE "VIDEO_SYSTEM_ACCESS_LEVEL" ADD VALUE 'TAKEDOWN';
