/*
  Warnings:

  - You are about to drop the column `withdrawalsAccessLevel` on the `SystemAccess` table. All the data in the column will be lost.

*/
-- CreateEnum
CREATE TYPE "REPORTING_SYSTEM_ACCESS_LEVEL" AS ENUM ('READ', 'WRITE', 'UPDATE', 'DELETE');

-- CreateEnum
CREATE TYPE "CONSUMPTION_SYSTEM_ACCESS_LEVEL" AS ENUM ('READ', 'WRITE', 'UPDATE', 'DELETE');

-- CreateEnum
CREATE TYPE "ENGAGEMENT_SYSTEM_ACCESS_LEVEL" AS ENUM ('READ', 'WRITE', 'UPDATE', 'DELETE');

-- CreateEnum
CREATE TYPE "REVENUE_SYSTEM_ACCESS_LEVEL" AS ENUM ('READ', 'WRITE', 'UPDATE', 'DELETE');

-- CreateEnum
CREATE TYPE "GEO_SYSTEM_ACCESS_LEVEL" AS ENUM ('READ', 'WRITE', 'UPDATE', 'DELETE');

-- AlterTable
ALTER TABLE "SystemAccess" DROP COLUMN "withdrawalsAccessLevel",
ADD COLUMN     "consumptionAccessLevel" "CONSUMPTION_SYSTEM_ACCESS_LEVEL"[] DEFAULT ARRAY[]::"CONSUMPTION_SYSTEM_ACCESS_LEVEL"[],
ADD COLUMN     "engagementAccessLevel" "ENGAGEMENT_SYSTEM_ACCESS_LEVEL"[] DEFAULT ARRAY[]::"ENGAGEMENT_SYSTEM_ACCESS_LEVEL"[],
ADD COLUMN     "geoAccessLevel" "GEO_SYSTEM_ACCESS_LEVEL"[] DEFAULT ARRAY[]::"GEO_SYSTEM_ACCESS_LEVEL"[],
ADD COLUMN     "reportingAccessLevel" "REPORTING_SYSTEM_ACCESS_LEVEL"[] DEFAULT ARRAY[]::"REPORTING_SYSTEM_ACCESS_LEVEL"[],
ADD COLUMN     "revenueAccessLevel" "REVENUE_SYSTEM_ACCESS_LEVEL"[] DEFAULT ARRAY[]::"REVENUE_SYSTEM_ACCESS_LEVEL"[],
ADD COLUMN     "withdrawsAccessLevel" "WITHDRAWAL_SYSTEM_ACCESS_LEVEL"[] DEFAULT ARRAY[]::"WITHDRAWAL_SYSTEM_ACCESS_LEVEL"[];
